### ISSUE TITLE
notification-area: Use cairo surfaces to render icons

### ISSUE THREAD

**Issue by vkareh** [mate-desktop/mate-panel#1033] opened 2019-10-16 19:20 UTC
Hi @mate-desktop/core-team 

This is an issue to track this patch: https://gitlab.gnome.org/GNOME/gtk/merge_requests/1135

It replaces a `GdkPixbuf` with a `cairo_surface_t` in `GtkStatusIcon` so that our tray applet can render properly on HiDPI displays.

Please test! Need to rebuild GTK with the patch, then rebuild panel and whichever app uses status icons (mate-settings-daemon, mate-media, mate-power-manager, etc...)

Before:
![before](https://user-images.githubusercontent.com/259780/67026896-a85f5b80-f0d6-11e9-8762-f839c7cf22ab.png)

After:
![after](https://user-images.githubusercontent.com/259780/67026895-a7c6c500-f0d6-11e9-9fc4-c54c5a8bd35f.png)

**Comment by lukefromdc** [comment] 2019-10-17 02:57
I tested with this installed, and with or without rebuilding the panel and mate-settings-daemon and mate-control-center, the monitor status icon would not show up. The first and only the first time I got a "general protection fault" the rest of the times the other applets would move over maybe 1px to make space after the icon started rendering and then appeared to crash but with no error messages and taking up maybe 1px of space, meaning it was actually running but not taking any space for the icon itself. This of was after restarting the panel and mate-settings-daemon or even the whole session.

A try with mate-media's status icon gave a clue: rebuilt against this it too did not show up, but I was able to get useful text running it from terminal:
`
(mate-volume-control-status-icon:12138): Gtk-WARNING **: 22:52:21.750: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 26

`
this appeared twice on trying to start the status icon. Apparently it was running but allocating zero width or width so small the theme took it to -1. No further warnings or errors in gdb. Probably same with the xrandr capplet but not visible from any terminal. Since the Bluetooth and Audacious icons appear (though no sharper as they may simply not have large enough files being chosen), clearly this code CAN work, but needs the apps setting the status icon to explicitly allocate this space. This should be fixed in the GTK PR if possible.

**Comment by raveit65** [comment] 2019-10-21 10:21
All applets which use GtkStatusIcon are gone with patched gtk3.
before (fusion-icon, blueberry, caja-dropbox, msd-xrandr, nm-applet,mate-power):
![na-tray-normal](https://user-images.githubusercontent.com/961604/67196973-1ddf6a80-f3fc-11e9-8767-c6ca06bf3fa9.png)
with patched gtk3 (only fusion-icon, caja-dropbox):
![na-tray-gtk3-patch](https://user-images.githubusercontent.com/961604/67197183-8595b580-f3fc-11e9-8911-693d7d0b2e15.png)
I got those warnings:
```
(mate-power-manager:2563): Gdk-CRITICAL **: 10:38:48.233: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(mate-settings-daemon:2504): Gtk-WARNING **: 10:38:48.234: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 26

(mate-power-manager:2563): Gtk-WARNING **: 10:38:48.238: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 26

(blueberry-tray.py:2557): Gtk-WARNING **: 10:38:48.238: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 26

(nm-applet:2574): Gtk-WARNING **: 10:38:48.238: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 26
```
I added the patch to current gtk3-3.24.11-1.fc30 RPM.
SRPM:
https://www.dropbox.com/s/u4kihf5b7ogt539/gtk3-3.24.11-2.fc30.src.rpm?dl=0

Rebui

**Comment by vkareh** [comment] 2019-10-21 11:30
@lukefromdc - I think I might need help compiling this... Here's what I use on Ubuntu MATE:
```
./autogen.sh \
  --prefix=/usr \
  --libdir=/usr/lib/x86_64-linux-gnu \
  --libexecdir/usr/libexec \
  --enable-broadway-backend \
  --enable-x11-backend \
  --enable-wayland-backend \
  --enable-shared \
  --enable-introspection \
  --disable-cloudprint \
  --disable-static \
  --disable-installed-tests \
  --disable-colord \
  --disable-gtk-doc \
  --disable-man
make
sudo make install
sudo cp ./gtk/org.gtk.* /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
sudo ldconfig
```
This is loosely based on what Debian does here: https://salsa.debian.org/gnome-team/gtk3/blob/debian/master/debian/rules
Not sure what I need to do to make it specific to Ubuntu.

But I saw your build instructions an it's not clear to me what you mean when you say that you move .la files manually and edit their version, then strip all executables...

**Comment by vkareh** [comment] 2019-10-21 13:21
Nevermind, I think I figured it out:
```
meson \
	build/ \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib/x86_64-linux-gnu \
	-Dsysconfdir=/etc \
	-Dx11_backend=true \
	-Dwayland_backend=true \
	-Dbroadway_backend=true \
	-Dintrospection=true
ninja -C build
sudo ninja -C build install
sudo cp ./gtk/libgtk-3.la /usr/lib/x86_64-linux-gnu/libgtk-3.la
sudo cp ./gdk/libgdk-3.la /usr/lib/x86_64-linux-gnu/libgdk-3.la
sudo cp ./gtk/org.gtk.* /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
sudo ldconfig
```
I can reproduce this on my branch, but `origin/gtk-3-24` works fine. I can now debug my code :)

**Comment by vkareh** [comment] 2019-10-21 14:49
Alright, final version of my build script:
```
meson \
	build/ \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib/x86_64-linux-gnu \
	-Dsysconfdir=/etc \
	-Dx11_backend=true \
	-Dwayland_backend=true \
	-Dbroadway_backend=true \
	-Dintrospection=true
ninja -C build
sudo ninja -C build install

sudo rm /usr/lib/x86_64-linux-gnu/libgtk-3.*
sudo cp ./gtk/libgtk-3.la /usr/lib/x86_64-linux-gnu/
sudo cp ./build/gtk/libgtk-3.so /usr/lib/x86_64-linux-gnu/
sudo cp ./build/gtk/libgtk-3.so.0 /usr/lib/x86_64-linux-gnu/

sudo rm /usr/lib/x86_64-linux-gnu/libgdk-3.*
sudo cp ./gdk/libgdk-3.la /usr/lib/x86_64-linux-gnu/
sudo cp ./build/gdk/libgdk-3.so /usr/lib/x86_64-linux-gnu/
sudo cp ./build/gdk/libgdk-3.so.0 /usr/lib/x86_64-linux-gnu/

sudo cp ./gtk/org.gtk.* /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
sudo ldconfig
```

It's quite destructive as it replaces your distro's GTK with whichever you just built, but I was finally able to compile/install successfully.

**Comment by vkareh** [comment] 2019-10-21 14:49
I've updated the [original merge request](https://gitlab.gnome.org/GNOME/gtk/merge_requests/1135). Please test if you have a chance.

**Comment by raveit65** [comment] 2019-10-21 17:08
Thanks this works much better.

**Comment by raveit65** [comment] 2019-10-21 18:08
Ok, gnome or awaita icon themes doesn't ship status/nm-device-wired and status/nm-no-connection icons. In result they use origin icons from nm-applet itself.
https://gitlab.gnome.org/GNOME/network-manager-applet/tree/master/icons
I think we should update mate-icon theme with their icons. And they ship SVGs, so we have a chance to regenerate PNGs for all sizes.

**Comment by vkareh** [comment] 2019-10-21 18:16
@raveit65 - I think any app that provides status icons might need to be rebuilt against the patched GTK. At least that has been the case for all the ones I've tested.

**Comment by vkareh** [comment] 2019-10-21 18:21
Regarding nm-applet, that repo only ships two SVG icons, all the others are tiny 22px PNGs :(
We might need to provide our own somehow...

**Comment by raveit65** [comment] 2019-10-21 18:37
Our own icons are symlinks from network-.....png to nm-.....png.
Maybe we replace only the 2 icons with the SVGs?
Any way, i will first test to rebuild nm-applet.
I am still wondering that blueberry-applet doesn't need a rebuild, btw. i thing it looks more sharpen without a rebuild.

**Comment by raveit65** [comment] 2019-10-21 20:41
Rebuilding network-manager-applet doesn't help, icon is blurred :/

**Comment by vkareh** [comment] 2019-10-21 21:06
Must be the really crappy icons. The highest size they have is 22px, which is way too small... Maybe try a theme that has symbolic icons? Those are often shipped as SVGs in several themes I've seen

**Comment by lukefromdc** [comment] 2019-10-21 21:58
network-manager-applet has a known small/low res icon issue. I had to create new SVG icons based on the originals by hand to get reasonable results in the indicator mode, though they are a little blurry in that. As soon as I get the new GTK PR commits built, I will try network manager in tray applet mode and see if it works better. It ought to, I made 128x128 icons in GIMP and used Inkscape to create SVG icons from them.

**Comment by raveit65** [comment] 2019-10-21 22:44
> Must be the really crappy icons. The highest size they have is 22px, which is way too small.

All icons are from mate-icon-theme, only if i select gnome/adwaita-icon-theme than icons from https://gitlab.gnome.org/GNOME/network-manager-applet/tree/master/icons are used, because those themes don't ship own icons for network-manager-applet nowadays.

Icons for network-manager-applet starts with nm-..... namespace for all sizes in mate-icon-theme.

So, i want to make it clear that using mate-icon-theme or icons from n-m gives me a blurry result when n-m is rebuild against patched gtk+.

**Comment by lukefromdc** [comment] 2019-10-21 23:20
(same comment as in the PR):

The revised version of this works. Also I found that in my case I didn't have to rebuild mate-panel, mate-settings-daemon or mate-volume-control (for mate-volume-control-status-applet) to get razor-sharp icons. I just had to restart them instead, first killall mate-panel, then open mate-system-monitor, find and kill mate-settings-daemon and mate-volume-control-status-applet and restart the latter (as I had started it manually) and I had crisp icons from both.
Blueman-Applet must ship only small icons as it did not benefit,network-manager icon I have special higher-resolution icons I made myself in my theme and they looks the same in tray and indicator mode but they don't seem to scale that well either way.

Conclusion is that this works, and at least on my setup nothing else has to be rebuilt, which is what I would expect because no .h (header) files are changed and the libraries are linked to, not compiled into mate-panel and the various applets that provide status icons. You DO have to restart them however to reload the GTK code they are linking against in RAM

**Comment by raveit65** [comment] 2019-10-21 23:21
I rebuilt blueberry-applet against patched gtk3 but i see no different.

**Comment by lukefromdc** [comment] 2019-10-21 23:31
No doubt the icons in that just don't have the resolution to scale up enough, cairo drawing can do nothing about that except not make it worse.

**Comment by raveit65** [comment] 2019-11-09 18:36
I think we need to find out why network-manger-applets icons do not scale, to increase our chances that someone from gtk+ starts to review your PR.
Because network-manager is part of gtk+/gnome/freedesktop application stack.
And it is used by several desktops, so it isn't a MATE-only problem.
I will take a look at old gnome-icon-theme repo, maybe i found some more svg icon sources, and we can generate them new for mate-icon-theme.
Not shore but for me it looks like the problem is more in their applet code. 
For this task i do not have enough  codding skills.

Well, i am happy to ask fedora/gtk+ developers to take a look in PR of GtkStatusIcon, but i am sure when we can say " See this fixes nm-applet icon with HIDPI" , this will increase our chance that someone update deprecated gtk+ code.

**Comment by lukefromdc** [comment] 2019-11-09 19:47
I just found that scaling down my own remade nm-applet icons from the 128x128 svg icons I made with the same colors as the originals but completely redraw also makes them blurry-and not only in the tray icon or the indicator, but even in Inkscale and Gimp!  They can be found in UbuntuStudio_Legacy/apps/scalable in  https://github.com/lukefromdc/ubuntustudio-legacy-icon-theme and when opened in EOM do NOT scale well. The 22px original icons scale well in EOM but not in Caja's thumbnailer. They will scale in GIMP if and only if interpolation is disabled in gimp's image rescaler.  I will now test the one I see the most in a complete set of PNG icons and see what that does.

I tested the origianls again by removing my SVG icons, and the result was nm-applet --indicator scales the original 22px icons to 44px cleanly-but cannot show them any other size. Running nm-applet for tray mode scales them to fit the panel, but they are of course blurry. I added the SVG icons long ago so the indicator icon would match the panel height. In all cases, with the original icons or with mine they are blurry in nm-applet's popup menu on a 4k monitor

There are no diagonal lines anywhere in these icons, only vertical and horizontal ones regardless of the color gradient.  I hope this doesn't mean that PNG icons for each size have to be totally remade from scratch.

**Comment by lukefromdc** [comment] 2019-11-09 20:35
There is a lot of internal detail in these icon for a 22px source file, so I tried remaking the nm-signal-75.svg icon to remove the detail-and it still didn't work. Remaking the icon cache after overwriting, then restarting nm-applet alternately in indicator and tray modes showed use of the new icon-but still blurry in BOTH modes, even though the simplified icon showed up clean in caja's thumbnailer and in EOM as well as Gimp and Inkscale. Not having this problem with the more complex(as they contain curves) volume control icons in either tray or panel applet mode

**Comment by vkareh** [comment] 2019-11-09 20:45
@lukefromdc, I think this doesn't have as much to do with the icons as it has to do with the code that places the icon itself. I will have to look into the nm-applet code, but I bet they're doing something like gtk_status_icon_new_from_pixbuf (or something like that, can't remember off the top of my head), but we don't even know how that pixbuf is loaded in the first place. So the real fix would be to change how nm-applet loads icons and sends them to the status icon function to make sure they're not losing pixel data in the process.

**Comment by vkareh** [comment] 2019-11-13 17:17
@lukefromdc, I've made some changes to nm-applet that fix this issue. However, it only fixes it for themes that use a different icon set than the one included with nm-applet (those are 22px PNGs, so they'll _never_ look good). Here: https://gitlab.gnome.org/vkareh/network-manager-applet/commit/912a985b26c8603b71ee22071f651dc64f1dc99d

As soon as the GTK patch to StatusIcons is merged, I'll send in a patch for nm-applet with this change.

**Comment by vkareh** [comment] 2019-11-13 17:43
awesome, it got merged!! https://gitlab.gnome.org/GNOME/gtk/merge_requests/1135

we're in business here, I'll submit the nm-applet changes

**Comment by vkareh** [comment] 2019-11-13 17:49
Now we can test nm-applet here: https://gitlab.gnome.org/GNOME/network-manager-applet/merge_requests/71

Remember to use a different icon theme that provides the correct network icons, like humanity, ubuntu-mono-dark, or ambiant-mate.

**Comment by lukefromdc** [comment] 2019-11-14 06:29
I just tested that, also applying https://github.com/lukefromdc/network-manager-applet/commit/09e1ca599f9fd45153827f5d3fac177d732757f5 
from my old "multifix" branch by hand so it would work with my gtk theme https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy and it's panel theme differing from the main GTK theme without having to rely on indicator mode.

Works great with my big .svg network icons from https://github.com/lukefromdc/ubuntustudio-legacy-icon-theme in tray mode, indicator mode is 
of course unchanged. Also icons in the popup menu are unchanged but neither of these have to do with the status-icon work that has finally been merged. This is an excellent followup to it in my opinion.

**Comment by vkareh** [comment] 2019-11-21 16:07
https://gitlab.gnome.org/GNOME/network-manager-applet/merge_requests/71 was merged. Mission accomplished! thanks for testing! :)

I have a branch in progress for the pop-up icons, and I think we should work on higher quality icons to submit upstream to nm-applet. So @lukefromdc if you can share those SVG I can try taking a stab at it too

**Comment by lukefromdc** [comment] 2019-11-21 17:04
You can find the svg icons I am using in 
https://github.com/lukefromdc/ubuntustudio-legacy-icon-theme
they are almost all of the icons in 
https://github.com/lukefromdc/ubuntustudio-legacy-icon-theme/tree/master/UbuntuStudio_Legacy/apps/scalable
and you are most welcome to use them for testing or more. I took the original icons, and scaled them up in GIMP with the scaling tool set to "no interpolation" that way all the sharp lines were preserved. I then made them into sgv files in Inkscale. There is probably a better way to do this but they worked for me and are good enough for testing at least.

**Comment by raveit65** [comment] 2019-11-21 18:06
I made icons from the origin icons for wired connections ate mate-icon-theme.
Sadly i didn't found good icon sources for wireless and vpn connections.
https://github.com/mate-desktop/mate-icon-theme/commit/0d317d42bc9ece742d1150dc9e668c2a9a5098bc

**Comment by raveit65** [comment] 2019-11-21 19:37
@lukefromdc 
Your wireless icons are looking really sharp inside na-tray.
Can i update mate-icon-theme with them, please?

Only in nm-applet menu the icons are blurred.
Looks like nm-applet needs another code update for menus ?

**Comment by raveit65** [comment] 2019-11-21 19:56
Looks like the SVGs are mostly embedded bitmaps.

**Comment by vkareh** [comment] 2019-11-21 20:25
Update for popup menus: https://gitlab.gnome.org/GNOME/network-manager-applet/merge_requests/72

**Comment by raveit65** [comment] 2019-11-21 22:12
Thanks, fix for menus works great.
But i would install icons to `status` dir and not `apps`.
Does the icons really looks better like before?
Because they are not real SVGs, embedded bitmaps SVGs are PNGs imported into a SVG.

**Comment by lukefromdc** [comment] 2019-11-22 00:35
Those SVG's are all I know how to make. They function reasonably well on my box. Feel free to remake them of course,
I simply don't know much about the format etc.I do not know if the authors of the original small icons created them at a
larger size or as SVG's, those would be ideal if they can be found. I would not want to see the style of these icons changed,
just the quality of them.

**Comment by lukefromdc** [comment] 2019-11-22 00:36
@raveit65, you are most welcome to use these icons in mate-icon-theme

**Comment by vkareh** [comment] 2019-11-26 16:08
@lukefromdc - question: how do you compile GTK so that you can still have indicators? I'm on Ubuntu, and applying [this patch](https://git.launchpad.net/ubuntu/+source/gtk+3.0/tree/debian/patches/ubuntu_gtk_custom_menu_items.patch) to GTK, but after recompiling mate-indicators-applet, I get this on run:
```
~/dev/mate/mate-indicator-applet/src/.libs/mate-indicator-applet: symbol lookup error: /usr/lib/x86_64-linux-gnu/libido3-0.1.so.0: undefined symbol: ubuntu_menu_item_factory_get_type
```
I'm compiling GTK using these options:
```
./autogen.sh \
	--prefix=/usr \
	--libdir=/usr/lib/x86_64-linux-gnu \
	--sysconfdir=/etc \
	--enable-x11-backend \
	--disable-win32-backend \
	--disable-quartz-backend \
	--enable-broadway-backend \
	--enable-wayland-backend \
	--enable-introspection
```
Then replacing the `libg[dt]k.*` files in `/usr/lib/x86_64-linux-gnu/`

Any idea on what I need to do differently?

**Comment by lukefromdc** [comment] 2019-11-26 20:26
I am no expert at all in gtk options, but note that network-manager-applet itself needs to be compiled with indicators explicitly enabled (at least in autotools, at least as of a few versions back). For compiling network-manager-applet I use

`./autogen.sh --prefix=/usr --sysconfdir=/etc --with-appindicator `

For GTK I will give you autotools build options that have always worked, as my Meson builds are nonstandard and involvem manually editing and adding back the .la files needed for many MATE packages and that I have never figured out how to get in meson. This is what I used for my last autotools build of gtk3, had no indicator problems with it:

`./autogen.sh --enable-wayland-backend --enable-x11-backend --enable-xrandr --enable-xfixes --enable-xkb --disable-maintainer-mode --prefix=/usr  --sysconfdir=/etc libdir=/usr/lib/x86_64-linux-gnu  --enable-broadway-backend`

Current meson build system (as used to make my last .deb package) is

```
meson \
	build/ \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib/x86_64-linux-gnu \
	-Dsysconfdir=/etc \
	-Dx11_backend=true \
	-Dwayland_backend=true \
	-Dbroadway_backend=true \
	-Dintrospection=true

ninja -C build

sudo DESTDIR=/home/luke/Desktop/Development/GTK_3.24/libgtk-3-0-all_3.24.12+git20191115-1luke1_amd64 ninja -C build install

Add back .la files manually

manually strip all executables
```
and as you can see involved nonstandard manual work, thus I gave you the autotools options that don't require this as well.

I don't know anything at all about any patches by Ubuntu

**Comment by vkareh** [comment] 2019-11-26 20:32
Wait, and your indicators work? Are you on Ubuntu? Which applet do you 
use for indicators?

As soon as I compile GTK, my mate-indicators-applet disappears, it errors 
with that same error message I posted, since Ubuntu patches GTK. Do you 
have your indicators manually compiled as well? Do you use Ubuntu or 
Ayatana indicators?

**Comment by lukefromdc** [comment] 2019-11-26 22:31
I am NOT on Ubuntu, I use indicators in mate-panel's native SNI support and not
the separate indicator applet.

**Comment by vkareh** [comment] 2019-11-26 22:44
Ah! Duh! That makes sense :P

Okay, I'll give SNI a try. Thanks

**Comment by raveit65** [comment] 2019-11-27 18:51
I have update network status icons (incl. wifi) for mate-icon-theme.
https://github.com/mate-desktop/mate-icon-theme/commit/4dbbf820cdaabc0981599c24f3f6c584ec5369a8
Some icons needs update but i didn't found goud svg sources for it, eg. nm-stage*-connecting*.png or vpn icons.

**Comment by lukefromdc** [comment] 2019-11-28 00:46
I think I found the indicator problem: 
We replace a pixbuf with a surface, but mate-panel's native SNI menus take only an icon name or a pixbuf.
https://gitlab.gnome.org/GNOME/network-manager-applet/merge_requests/72#note_657662
I think we can fix this by passing the icon name, and if it then comes up blurry in SNI mode can fix that in mate-panel

**Comment by vkareh** [comment] 2019-11-28 12:19
We can't pass icon name, since it's a composited pixbuf (e.g. on secured wi-fi networks, it overlaps the lock icon on top of the wi-fi icon). I've reworked https://gitlab.gnome.org/GNOME/network-manager-applet/merge_requests/72 to keep using GdkPixbuf for SNI, but then convert to cairo_surface_t for GtkStatusIcon. I also submitted a [new commit](https://github.com/mate-desktop/mate-panel/pull/1041) to fix the notifications-tray SNI menu items.

**Comment by lukefromdc** [comment] 2019-11-28 21:22
See 
https://github.com/mate-desktop/mate-panel/pull/1041#issuecomment-559599860
and
https://gitlab.gnome.org/vkareh/network-manager-applet/commit/d56c26da6d4ddddfcf3b8d54db2fc61b818b5af1#note_658383
These two PR commits to mate-panel and network-manager-applet  work very well together, though if you mix and match you can get wrong icon sizes

**Comment by raveit65** [comment] 2019-11-29 17:48
I just upload new vpn icons for nm-applet and regenerate volume status icons for mate-icon-theme.
Now all applets which i use (GtkStaus/SNI) are really looking sharp :)
Screenshot with 25px panel size.
![Bildschirmfoto zu 2019-11-29 18-32-07](https://user-images.githubusercontent.com/961604/69884227-a7c20380-12d7-11ea-8eed-10efdc0fff38.png)
Not sure about fusion-icon (SNI) from compiz-reloaded. Maybe the icon needs to regenerated.

It seems that GtkStatus applet icons have limited size, in opposite to SNI applets they don't scale to max panel size.

**Comment by vkareh** [comment] 2019-11-29 18:17
> It seems that GtkStatus applet icons have limited size, in opposite to SNI applets they don't scale to max panel size.

That seems to be a limitation in the notification-area applet's code. We should fix that, but do we want to limit _all_ icons or should we allow them all to scale up?

**Comment by raveit65** [comment] 2019-11-29 19:17
> That seems to be a limitation in the notification-area applet's code. We should fix that, but do we want to limit _all_ icons or should we allow them all to scale up?

Here the limitation starts with 48-49 px panel size. The important thing should be that all icons have the same size on every panel size.
If all icons means from na-tray-applet and other other applets, eg. panel-action or panel-launcher, than we should limit the size of tray-applet icons, to have an consistent look of the whole panel.

On the other side the typical mate user loves the freedom of choice and is responsible for his panel look&feel. And maybe there is a special use case for really large tray-applets (na-tray stand-alone on vertical panel). 
So, i would vote for scaling all na-tray icons up.

**Comment by raveit65** [comment] 2019-11-30 22:26
@vkareh 
Is it possible that mobil network connections are handled by another part in menu code for nm-applet?
It seems that the icon is blurry :/
![nm-applet-mobil-network](https://user-images.githubusercontent.com/961604/69906760-8ab92d80-13c8-11ea-8123-c67eac7a240f.jpg)

**Comment by vkareh** [comment] 2019-11-30 23:55
I think the new wireless icon has a drop shadow around it that makes it look blurry. If I use the Ubuntu MATE icons (symbolic) they look very sharp.

Any chance we can remove that shadow?

**Comment by raveit65** [comment] 2019-12-01 09:28
It's the same icon as shown for wireless connections of for the tray icon, and here the shadow is sharp on my screenshot.
And the shadow is needed to have a good contrast on light backgrounds.
For me the whole the icon is blurry and not only the edge.

**Comment by raveit65** [comment] 2019-12-01 09:42
Same effect with using original icon from network-manager-applet.
![nm-applet-mobil-network-origin](https://user-images.githubusercontent.com/961604/69912253-f6ca7e80-1426-11ea-8077-631386102bb7.jpg)
Any way not a big thing.

**Comment by vkareh** [comment] 2019-12-04 14:37
@raveit65 - I pushed new changes to https://gitlab.gnome.org/GNOME/network-manager-applet/merge_requests/72 that render the mobile broadband icons correctly. Please test

**Comment by raveit65** [comment] 2019-12-04 17:03
I did, mobile broadband icon looks sharp like the others now :)
Thank you so much for this work.

**Comment by lukefromdc** [comment] 2019-12-05 05:48
I'm getting good overall results now, though I can't test mobile broadband icons as I don't have the hardware to directly connect to it on the desktop

**Comment by raveit65** [comment] 2020-02-15 16:34
Remaining NM-applet PRs are merged.

**Closed by raveit65** 2020-02-15 16:34 UTC
