### ISSUE TITLE
Reproducable Mate Panel crash in v1.16.0

### ISSUE THREAD

**Issue by bkerlin** [mate-desktop/mate-panel#516] opened 2017-01-19 23:13 UTC
1. Add "Netspeed" applet to a panel.
2. Move "Netspeed" applet to a different panel (black box appears instead of data).
3. Right click on panel to where "Netspeed" applet was moved and try to add a new "Netspeed" applet.
4. Mate-panel crashes and restarts.

**Comment by raveit65** [comment] 2017-01-20 09:41
> 1. Add "Netspeed" applet to a panel.
> 2. Move "Netspeed" applet to a different panel (black box appears instead of data).

Do a panel restart here, ie. with 'killall mate-panel.
No need to add a new one here.

**Comment by monsta** [comment] 2017-01-27 13:38
> black box appears instead of data

@lukefromdc: looks related to https://github.com/mate-desktop/mate-panel/issues/504?

**Comment by monsta** [comment] 2017-01-27 13:40
@bkerlin: please also specify the distro, as there are various versions of GTK+ and various bugs related to them.

**Comment by bkerlin** [comment] 2017-01-27 16:00
I am currently running Ubuntu Mate 16.10.

I have GTK+ versions below:
3.20.9-1ubuntu2
2.24.30-4ubuntu3

My install was originally originally Ubuntu Mate 16.04.  I do not know if the issue occured prior to my upgrade, sadly.  After my upgrade, The only change I made was installing a PPA for the Brisk menu to try it out (https://launchpad.net/~flexiondotorg).

**Comment by monsta** [comment] 2017-01-28 10:41
It's an issue with GTK+3 build of MATE, so you couldn't experience it in 16.04 (where MATE is built with GTK+2). I thought it happens only with GTK+ 3.22, as reported in #504, but looks like 3.20 is affected as well.

**Comment by raveit65** [comment] 2017-01-28 19:08
I guess we can close this one and work on https://github.com/mate-desktop/mate-panel/issues/504 .

**Closed by raveit65** 2017-01-28 19:08 UTC

**Comment by monsta** [comment] 2017-05-30 09:46
So I was wrong about GTK+3 build, it actually was a regression in 1.16 which affected both builds. Anyway, this is now fixed by https://github.com/mate-desktop/mate-panel/pull/584. We'll make new 1.18.x and 1.16.x releases later.
