### ISSUE TITLE
"Window List", "Show Desktop", and "Workspace switcher" periodically crash since the 1.26 update

### ISSUE THREAD

**Issue by pgoetz** [mate-desktop/mate-panel#1256] opened 2021-09-23 20:03 UTC
#### Expected behaviour

Everything just works flawlessly, the way it did with 1.24

#### Actual behaviour

Some panel applets keep periodically crashing; I can't find any associated log files.
I just see successive pop-up dialogs reporting:

"Window List" has quit unexpectedly
"Show Desktop" has quite unexpectedly
"Workspace Switcher" has quit unexpectedly

Restarting them doesn't seem to harm anything.

#### Steps to reproduce the behaviour

Just use my workstation; I can't any correlates with what I'm doing.

#### MATE general version

1.26.0

#### Package version

1.26.0-1

#### Linux Distribution

Arch linux, fully updated.

#### Link to bugreport of your Distribution (requirement)

This might be a requirement, but the Arch philosophy is to leave upstream unmodified and then report all bugs there.  Also, I posted in as Mate General issue, but then thought it might only be related to the panel.

**Comment by raveit65** [comment] 2021-09-23 20:28
> This might be a requirement, but the Arch philosophy is to leave upstream unmodified and then report all bugs there. Also, I posted in as Mate General issue, but then thought it might only be related to the panel.

requirement not resolved, ........unsuscibed

**Comment by zhuyaliang** [comment] 2021-09-24 14:48
This may not be the problem of the ```mate-panel``` itself

**Comment by anvltu** [comment] 2021-10-20 19:21
I see the same behaviour in my Ubuntu Mate 21.10. Window list applet keeps crashing from time to time. Every applet restart reorders window buttons in a random manner.

**Comment by Dalzot** [comment] 2021-10-25 00:38
I also have this issue randomly on Manjaro and unsure if this is helpful but my journalctl has these errors for each panel that crashes. Sometimes when it crashes, I'm unable to adjust my volume.
`wnck-applet[1195]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
wnck-applet[1195]: gdk_window_get_scale_factor: assertion 'GDK_IS_WINDOW (window)' failed
wnck-applet[1195]: gdk_window_get_width: assertion 'GDK_IS_WINDOW (window)' failed
wnck-applet[1195]: gdk_window_get_height: assertion 'GDK_IS_WINDOW (window)' failed
wnck-applet[1195]: gdk_cairo_set_source_window: assertion 'GDK_IS_WINDOW (window)' failed
wnck-applet[1195]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
wnck-applet[1195]: gtk_window_set_default_size: assertion 'width >= -1' failed
`

**Comment by lgeek** [comment] 2021-10-25 23:56
I'm also affected by this and I managed to get a backtrace and some information. It seems to be a NULL pointer dereference of `impl` in gdk_x11_device_xi2_window_at_position():

```
Thread 1 "wnck-applet" received signal SIGSEGV, Segmentation fault.
0x00007f1cc12d56ce in gdk_x11_device_xi2_window_at_position (device=<optimized out>, win_x=0x7ffc7509b250, win_y=0x7ffc7509b248, mask=0x0, get_toplevel=0) at ../gtk/gdk/x11/gdkdevice-xi2.c:661
661	    *win_x = (window) ? (xwin_x / impl->window_scale) : -1;
(gdb) back
#0  0x00007f1cc12d56ce in gdk_x11_device_xi2_window_at_position (device=<optimized out>, win_x=0x7ffc7509b250, win_y=0x7ffc7509b248, mask=0x0, get_toplevel=0)
    at ../gtk/gdk/x11/gdkdevice-xi2.c:661
#1  0x00007f1cc128961c in _gdk_device_window_at_position (get_toplevel=0, mask=0x0, win_y=0x7ffc7509b248, win_x=0x7ffc7509b250, device=0x55b551bfa800) at ../gtk/gdk/gdkdevice.c:1894
#2  gdk_device_get_window_at_position_double (device=0x55b551bfa800, win_x=win_x@entry=0x7ffc7509b2a0, win_y=win_y@entry=0x7ffc7509b298) at ../gtk/gdk/gdkdevice.c:680
#3  0x00007f1cc128973e in gdk_device_get_window_at_position (device=<optimized out>, win_x=win_x@entry=0x7ffc7509b2dc, win_y=win_y@entry=0x7ffc7509b2d8) at ../gtk/gdk/gdkdevice.c:725
#4  0x00007f1cc16430e2 in gtk_tooltip_trigger_tooltip_query (display=<optimized out>) at ../gtk/gtk/gtktooltip.c:446
#5  0x00007f1cc0deab08 in g_slist_foreach (list=<optimized out>, func=0x7f1cc16430a0 <gtk_tooltip_trigger_tooltip_query>, user_data=user_data@entry=0x0) at ../glib/glib/gslist.c:885
#6  0x00007f1cc168bc7a in tooltip_query_idle (data=<optimized out>) at ../gtk/gtk/gtkwidget.c:15397
#7  0x00007f1cc128585c in gdk_threads_dispatch (data=0x55b551d1d2a0) at ../gtk/gdk/gdk.c:769
#8  0x00007f1cc0dcf015 in g_main_dispatch (context=0x55b551bf9ba0) at ../glib/glib/gmain.c:3337
#9  g_main_context_dispatch (context=0x55b551bf9ba0) at ../glib/glib/gmain.c:4055
#10 0x00007f1cc0e22b99 in g_main_context_iterate.constprop.0 (context=0x55b551bf9ba0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4131
#11 0x00007f1cc0dce693 in g_main_loop_run (loop=0x55b551d15240) at ../glib/glib/gmain.c:4329
#12 0x00007f1cc152b85f in gtk_main () at ../gtk/gtk/gtkmain.c:1329
#13 0x00007f1cc1ba3e2b in _mate_panel_applet_factory_main_internalPython Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
    (factory_id=0x55b5507fc171 "WnckletFactory", out_process=1, applet_type=, callback=0x55b5507f263c <wncklet_factory>, user_data=0x0) at mate-panel-applet.c:2458
#14 0x00007f1cc1ba3e85 in mate_panel_applet_factory_mainPython Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
 (factory_id=0x55b5507fc171 "WnckletFactory", out_process=1, applet_type=, callback=0x55b5507f263c <wncklet_factory>, user_data=0x0)
    at mate-panel-applet.c:2486
#15 0x000055b5507f2931 in main (argc=1, argv=0x7ffc7509b6a8) at wncklet.c:155

(gdb) print impl
$1 = 0x0
(gdb) print window
$2 = 0x55b5520373c0
(gdb) print *window
$5 = {parent_instance = {g_type_instance = {g_class = <error reading variable: Cannot access memory at address 0x0>}, ref_count = 0, qdata = 0x0}, impl = 0x0, parent = 0x0, 
  transient_for = 0x0, visual = 0x55b551bd8800, user_data = 0x0, x = 3840, y = 41, event_mask = 98304, window_type = 4 '\004', depth = 24 '\030', resize_count = 0 '\000', 
  toplevel_window_type = -1 '\377', filters = 0x0, children = 0x0, children_list_node = {data=0x55b5520373c0, next=0x0, prev=0x0}, native_children = 0x0, background = 0x0, current_paint = {
    surface = 0x0, region = 0x0, flushed_region = 0x0, need_blend_region = 0x0, surface_needs_composite = 0, use_gl = 0}, gl_paint_context = 0x0, update_area = 0x0, update_freeze_count = 0, 
  active_update_area = 0x0, old_updated_area = {0x0, 0x0}, old_state = 0, state = GDK_WINDOW_STATE_WITHDRAWN, synthesized_crossing_event_id = 0, alpha = 0 '\000', fullscreen_mode = 0 '\000', 
  input_only = 0, pass_through = 0, modal_hint = 0, composited = 0, has_alpha_background = 0, destroyed = 1, accept_focus = 0, focus_on_map = 0, shaped = 0, support_multidevice = 0, 
  effective_visibility = 0, visibility = 0, native_visibility = 0, viewable = 1, applied_shape = 0, in_update = 0, geometry_dirty = 1, event_compression = 0, frame_clock_events_paused = 0, 
  impl_window = 0x55b5520373c0, update_and_descendants_freeze_count = 0, abs_x = 0, abs_y = 0, width = 3840, height = 2119, shadow_top = 0, shadow_left = 0, shadow_right = 0, 
  shadow_bottom = 0, num_offscreen_children = 0, clip_region = 0x0, cursor = 0x0, device_cursor = 0x55b551ebc700 = {[0x218] = 0x218, [0x28] = 0x28, [0x0] = 0x0, [0x0] = 0x0, [0x61] = 0x61, 
    [0x9579bdf] = 0x9579bdf, [0x55b0] = 0x55b0, [0x51b79010] = 0x51b79010, [0x55b5] = 0x55b5, [0x110] = 0x110, [0x110] = 0x110, [0x110] = 0x110, [0x800840] = 0x800840, [0x110] = 0x110, 
    [0x0] = 0x0, [0x1] = 0x1, [0x2] = 0x2, [0x0] = 0x0, [0x0] = 0x0, [0x84a] = 0x84a, [0x1] = 0x1, [0x31] = 0x31, [0x0] = 0x0, [0x3] = 0x3, [0x1] = 0x1, [0x0] = 0x0, [0x31] = 0x31, 
    [0x0] = 0x0, [0x619] = 0x619, [0x0] = 0x0, [0x5201f300] = 0x5201f300, [0x55b5] = 0x55b5, [0x0] = 0x0, [0x0] = 0x0, [0x21] = 0x21, [0x51] = 0x51, [0x0] = 0x0, [0x10d] = 0x10d, 
    [0x28] = 0x28, [0x0] = 0x0, [0x0] = 0x0, [0x1] = 0x1, [0x0] = 0x0, [0x0] = 0x0, [0x51] = 0x51, [0x0] = 0x0, [0x10d] = 0x10d, [0x28] = 0x28, [0x0] = 0x0, [0x0] = 0x0, [0x1] = 0x1, 
    [0x0] = 0x0, [0x0] = 0x0, [0x0] = 0x0, [0x32400] = 0x32400, [0x0] = 0x0, [0x43100] = 0x43100, [0x2800] = 0x2800, [0x0] = 0x0, [0x51] = 0x51, [0x0] = 0x0, [0x325] = 0x325, [0x1] = 0x1, 
    [0x10b] = 0x10b, [0x26] = 0x26, [0x0] = 0x0, [0x51fff974] = 0x51fff974, [0x100] = 0x100, [0x43000] = 0x43000, [0x31] = 0x31, [0x0] = 0x0, [0x414bb76] = 0x414bb76, 
    [0xba775c33] = 0xba775c33, [0x0] = 0x0, [0xc6995af6] = 0xc6995af6, [0x21] = 0x21, [0x5200a4e0] = 0x5200a4e0, [0x55b5] = 0x55b5, [0x6] = 0x6, [0x0] = 0x0, [0x52011150] = 0x52011150, 
    [0x51f91ac0] = 0x51f91ac0, [0xc11a32a0] = 0xc11a32a0, [0x52012430] = 0x52012430, [0x55b5] = 0x55b5, [0x21d4f80] = 0x21d4f80, [0x40] = 0x40, [0x0] = 0x0, [0x51] = 0x51, [0x0] = 0x0, 
    [0x0] = 0x0, [0x0] = 0x0, [0x0] = 0x0, [0x0] = 0x0, [0x0] = 0x0, [0x0] = 0x0, [0xc0ec0c70] = 0xc0ec0c70, [0x7f1c] = 0x7f1c, [0x1] = 0x1, [0x0] = 0x0...}, shape = 0x0, input_shape = 0x0, 
  devices_inside = 0x0, device_events = 0x0, source_event_masks = 0x0, device_added_handler_id = 0, device_changed_handler_id = 0, frame_clock = 0x0, invalidate_handler = 0x0, 
  drawing_context = 0x0, opaque_region = 0x0}

```

**Comment by gunchleoc** [comment] 2021-10-30 08:19
I don't know with which version it started, but I am having the same problem with Linux Mint Mate - I seem to remember the first occurrence after the upgrade to the LTS release based on Ubuntu 20.04.

It also sometimes gets confused when I open the main menu, change my mind and try to return to a window without closing the main menu - maybe some bug in the window toggling code? It usually recovers after a while if I close the main menu and then keep clicking windows at random.

Also, sometimes the taskbar won't show at all after booting the system.

Sometimes, I can't switch between windows any more and the graphics get seriously foobared, but that might be another bug.

It's going to be tough reproducing the bug from this information - is there any way I can get more info out of the system for you? The info would have to be in some log that will survive a hard reboot.

**Comment by lukefromdc** [comment] 2021-11-03 03:34
I have never had this happen on Debian unstable, so somthing here might be distro-specific

**Comment by radiophysicist** [comment] 2021-11-03 18:45
The same problem for mate 1.26.0 on manjaro

**Comment by Torkamata** [comment] 2021-12-30 19:37
I have experienced the same "Window List", "Show Desktop", and "Workspace switcher" periodically crashing since 1.26 on Manjaro, Ubuntu 21.10, Ubuntu 21.04. on Mate 1.24 I did not have this issue.

If there is any other information I can gather to assist let me know.

**Comment by mbkma** [comment] 2021-12-30 22:21
This issue is already known and fixed. Please see https://github.com/mate-desktop/mate-panel/pull/1252. If you build mate-panel with this patch applied, everything should work fine. Alternatively you can wait until mate-panel 1.26.1 gets released.

**Comment by raveit65** [comment] 2022-01-23 12:43
Should be fixed with https://github.com/mate-desktop/mate-panel/commit/42e01cf4992c552bc7924bb8fd0087832e85e8c1

**Closed by raveit65** 2022-01-23 12:43 UTC
