### ISSUE TITLE
Guake not shown in Notification area. 

### ISSUE THREAD

**Issue by shirishag75** [mate-desktop/mate-panel#666] opened 2017-10-03 15:26 UTC
#### Expected behaviour

Guake should show up in Notification area, 

#### Actual behaviour

Guake should show up in Notification area, it doesn't. 

#### Steps to reproduce the behaviour

I have no idea what is the problem, I did remove the upper panel and started afresh, when I put the notification area, I expected Guake to show up, it didn't, dunno why. 

If I do use the mouse pointer to point exactly between notification area and qbittorrent I do get indication about guake . 

This has been happening for quite sometime now. 
![notification-area-no-guake](https://user-images.githubusercontent.com/727626/31133437-007958d4-a84f-11e7-9158-8669cdf61b16.png)

```
[$] apt-cache policy mate-panel                                                                                                    
mate-panel:
  Installed: 1.18.4-2
  Candidate: 1.18.4-2
  Version table:
 *** 1.18.4-2 600
        600 http://httpredir.debian.org/debian buster/main amd64 Packages
          1 http://httpredir.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```
#### Linux Distribution

Debian Testing

#### Link to downstream report of your Distribution

bugs.debian.org/877638

**Comment by monsta** [comment] 2017-11-18 09:08
@flexiondotorg @sunweaver @lukefromdc @raveit65 
Can you guys reproduce it? I wasn't able (in Debian Testing at least).

**Comment by raveit65** [comment] 2017-11-18 09:31
I don't know this app and i don't see any hints how to use it.
Why people think that that i should installed an unknown app on my system with incomplete steps to reproduce?  :P

**Comment by sc0w** [comment] 2017-11-18 09:55
I can see the guake icon in the notification area

The first time I run it, it goes to the notifiaction area

guake 0.8.10-1
mate-panel 1.18.4-2
gtk 3.22.24-3

debian testing

**Comment by lukefromdc** [comment] 2017-11-19 02:11
I also do not have guake installed. Looks like it's just a drop-down terminal app.  In synaptic I see guake and guake-indicator listed as available. Unfortunately it pulls in a bunch of dependencies so it is not very practical for me to test and then get rid of all the stuff it pulled in. If you are getting no icon but can hover between two icons, this looks like a zero icon width bug or an icon problem. In SNI mode, a missing icon will bring up the generic "missing icon" icon so that's probably not the problem.

Try changing through all your themes and seeing if the icon appears.

**Comment by monsta** [comment] 2017-11-23 15:13
Yeah it's a drop-down terminal app, one of several ones out there.

**Comment by monsta** [comment] 2017-11-23 15:16
It doesn't depend on any appindicator stuff, so SNI mode is out of question.

**Comment by shirishag75** [comment] 2018-10-11 06:11
FWIW, guake now shows up but lookd weird 
![keyboard-led-not-showing-in-notification-area](https://user-images.githubusercontent.com/727626/46784128-8b1ce200-cd4a-11e8-9437-f110777fb508.png)

**Comment by monsta** [comment] 2018-11-26 14:09
This apparently happened right after GTK+ 3.24 replaced 3.22 in Debian Testing. I can now reproduce this icon corruption in Ubuntu 18.10 with mate-panel 1.20.3 and GTK+ 3.24.1.

It's a different problem than the one reported here originally though. Do we have any other reports about it?

**Comment by monsta** [comment] 2018-11-26 14:15
@lukefromdc: I've picked the fix from https://github.com/mate-desktop/mate-panel/pull/834 and built 1.20 branch with it. Had to do some manual work, the commit didn't apply cleanly... So it didn't fix this corruption of Guake icon for me. Are there some other tray fixes which aren't picked to 1.20 yet?

Tested in a VM and without HiDPI.

**Comment by lukefromdc** [comment] 2018-11-26 18:57
I really don't know at this point: I don't have anything with the full set of 1.20 packages installed, and didn't see anything obvious but there are a lot of other differences now from the wide panel work in master. Have you tested this with master (1.21) to see if there is any difference?  Also, make sure you both build and run with either GTK 3.24 or GTK 3.22, don't mix these up.

**Comment by lukefromdc** [comment] 2018-11-26 19:09
I just verified by a test install over master that whatever this is, it is not a cherrypicking issue. I wonder however if the problem is in Guake itself and NOT in the panel, as the icon for a status icon is set up by the application setting a GtkStatusIcon and the contents of the small window containing it are what get passed to the GtkSocket using Xembed.

**Comment by lukefromdc** [comment] 2018-11-26 19:17
Also note that a guake-indicator package is now available(at least in Debian and presumably Ubuntu). Install this and have it start at login rather than guake itself, and it will start an instance of guake. Turn off guake's own tray icon in preferences(right click the guake terminal to get there without the icon)  and you are done. This is a workaround, not a fix, but I strongly suspect the issue is in guake and not in mate-panel with the tray icon.

**Comment by monsta** [comment] 2018-11-27 10:51
I don't mix GTK+ versions, every VM has its own version from the corresponding Debian/Ubuntu release. So I've tested in a few other configurations too.

- Ubuntu 18.04, GTK+ 3.22.30, Guake 3.0.5, mate-panel 1.20.1 and 1.20.3
- Ubuntu 18.10, GTK+ 3.24.1, Guake 3.3.0, mate-panel 1.20.3
- Debian Stretch, GTK+ 3.22.11, Guake 3.0.0 (not from repos - built locally), mate-panel 1.20.3
- Debian Testing, GTK+ 3.24.1, Guake 3.4.0, mate-panel 1.21.1 and git master

It's reproducible in all these cases. So could be indeed Guake's own problem...

**Comment by monsta** [comment] 2018-11-27 11:06
Ok, so this is already reported at https://github.com/Guake/guake/issues/1110, and it happens in Xfce too. This is only about Guake 3.x.x releases which are GTK+3.

The original problem reported here is about older versions of Guake (0.8.x) which are GTK+2. I was never able to reproduce the issue.

Given all this, should we close this report?

**Comment by lukefromdc** [comment] 2018-11-27 18:58
OK, we can probably close this, as the same issue with GTK3 versions of Guake is being reported across multiple DE's with different trays. Some of this may be maintainance issues with GtkStatusIcon or GtkPlug/Socket themselves, I would imagine Xembed itself is properly taken care of.   

This also tells me that tray issues with mate-power-management and with the mate volume control applet may need some work on our part in those packages.  Since there are at least some status icons that render troublefree , we may just have to limit what we ourselves now do with GtkStatusIcon to those things that still work correctly. That was why I dropped my effort to add an icon and slider for recording from output sound to mate-media's volume control applet: I just could not make the icon reliable with how GtkStatusIcon is behaving these days.

**Comment by lukefromdc** [comment] 2018-11-27 19:07
https://github.com/mate-desktop/mate-indicator-applet/issues/21 and the fix for it in 
https://github.com/mate-desktop/mate-control-center/pull/370
may be how to fix this sort of problem (corrupted icons sent to the tray) in our own applications setting status icons and improves HiDPI rendering to boot. This might also be what Guake developers need to do upstream.

**Comment by monsta** [comment] 2018-11-28 13:38
Yeah, GtkStatusIcon is deprecated, so they probably don't add any fixes to it.

**Closed by monsta** 2018-11-28 13:38 UTC
Labels: unconfirmed

**Comment by lukefromdc** [comment] 2018-12-13 05:19
The icon tiling issue in GTK 3 turned out to indeed be a gtkstatusicon issue, for which a PR has been submitted to GTK 3.24 and fixed it in my testing:
https://gitlab.gnome.org/GNOME/gtk/merge_requests/451

See https://github.com/mate-desktop/mate-panel/issues/793#issuecomment-446737176

**Comment by lukefromdc** [comment] 2018-12-13 05:34
No change needed in Guake, if the GTK devs merge the fix it should make it into GTK 3.24.3. Note that GTK 3.24.2 just came out today, only to be followed by a commit to revert a commit that broke the entire build. Thus the possible scenarios are:  
1: GTK devs merge the PR with the fix, and due to the build failure GTK 3.24.3 soon comes out and includes this.
2:  GTK devs merge the PR with the fix but release GTK 3.24.3 to fix the build that this misses the window and has to wait for GTK 3.24.4 which would then be a couple months away.
3: GTK devs merge the PR with the fix, then a couple months wait for GTK 3.24.3 (maybe after a 3.24.2 re-release with nothing but fixing the build)
4:GTK devs don't merge this at all.

Also, if your distro uses GTK 3.22, I have no idea if this would ever be backported. Note that mate-panel and some other programs have to be rebuilt for GTK 3.24 if you want to get good results on a HiDPI screen but will work fine on a normal resolution screen without rebuilding.

**Comment by shirishag75** [comment] 2018-12-13 05:42
that really depends upon Debian. I think it will miss the window though. Debian will enter soft freeze at Feb. end but might make an exception depending on when it's released. We are currently at -

**Comment by lukefromdc** [comment] 2018-12-13 21:08
Fix in GTK 3.24 branch is now merged, so its just a matter of waiting for GTK 3.24.3 which should include it.

**Comment by muktupavels** [comment] 2018-12-13 21:09
There might be new release before Christmas. :)

**Comment by shirishag75** [comment] 2018-12-14 05:54
> There might be new release before Christmas. :)

please intimate if it happens so. There is a delay in getting gtk 3.24.2 . If gtk 3.24.3 gets released, could ask the Debian Developers (DD) who are maintaining that package to get the release and see how guake icon looks afterwards in mate-panel, xfce-panel and lxqt, all in which guake fails at the present to give nice icon in the system tray.

**Comment by lukefromdc** [comment] 2018-12-14 06:43
GTK 3.24.2 as initially tagged had a commit with a typo that broke the build, thus no surprise it has not appeared as a released build.

**Comment by shirishag75** [comment] 2018-12-14 07:21
In Debian they did use the patch which fixed the typo and released it yesterday/today. See https://tracker.debian.org/news/1011105/accepted-gtk30-3242-3-source-into-unstable/

**Comment by lukefromdc** [comment] 2018-12-14 07:34
To get this into Debian Stable and other releases that predate GTK 3.24 would require a cherrypick into GTK 3.22, assuming the commits would apply clean.

**Comment by muktupavels** [comment] 2018-12-14 09:41
You can try to ask that they add one more patch.

**Comment by shirishag75** [comment] 2018-12-14 10:32
They could make a patch that works with 3.22 and release it as 3.22.1 . With git there is never an issue of doing something like that and happens all the time. If nobody else puts up a request, I will do the same in few hours. If somebody else does, please intimate the same.

**Comment by muktupavels** [comment] 2018-12-14 10:37
I think they have stated (I might be wrong) that there won't be new 3.22.x release. So none is going to spend time to merge fix in gtk-3-22 branch... Anyway patch should apply cleanly there and probably even to older releases.

Just ask your distro maintainer to add that patch.

**Comment by shirishag75** [comment] 2018-12-14 13:41
This hasn't been fixed. I got the updated version and tried running guake in mate-session on Debian testing and the results have been as before. In fact I saw even bugs.debian.org/916436 :( 

Will share the screenshot in a sec.

**Comment by shirishag75** [comment] 2018-12-14 13:41
![guake-issue-still-in-debian-mate](https://user-images.githubusercontent.com/727626/50006545-1b3e0880-ffd4-11e8-8cd2-944284229fe0.png)

**Comment by muktupavels** [comment] 2018-12-14 13:46
With updated version you mean `gtk+3.0 3.24.2-3` that you linked previously? It does **not** include fix...

**Comment by shirishag75** [comment] 2018-12-14 13:53
apparently the maintainer included the fix, at least that is what was told to me, although it doesn't appear in the debian changelog https://salsa.debian.org/gnome-team/gtk3/commit/0b26d0b56d5888d2c6a1244d41618e15dd6c3b2d

**Comment by muktupavels** [comment] 2018-12-14 13:53
It is different fix for different problem. You need this - https://gitlab.gnome.org/GNOME/gtk/merge_requests/451/.

**Comment by lukefromdc** [comment] 2018-12-14 21:04
Package version you will be waiting for will probably get a name like `gtk+3.0 3.24.3-1 `not the already mentioned ` gtk+3.0 3.24.2-3 `which is a (presumably the third) build of gtk 3.24.2

**Comment by shirishag75** [comment] 2018-12-14 21:36
yup, shared it with the maintainer and he would also be looking for the new release as and when it's released. It's just waiting time I guess now :(

**Comment by shirishag75** [comment] 2018-12-23 22:12
well seems the new point release will be after Christmas as it's just one day before Christmas and didn't see any info. at least on mailing list to indicate they are going to make a new release soon :(

**Comment by shirishag75** [comment] 2018-12-30 07:35
Still no update :(  https://gitlab.gnome.org/GNOME/gtk/tags

**Comment by shirishag75** [comment] 2019-01-09 10:49
apparently, the new version would be released sometime this week. https://mail.gnome.org/archives/gtk-devel-list/2019-January/msg00000.html
