### ISSUE TITLE
Transmission tray icon bug 

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-panel#50] opened 2012-10-19 09:20 UTC
In some themes, for example, adwaita spaces between transmission's tray icon and others look like this https://www.dropbox.com/s/5a2n7tz9tu30g00/Screenshot.png. In mint-x theme everything looks good. After change of theme from adwaita to mint-x and back, this bug disappear.
##

**Comment by monsta** [comment] 2015-08-31 10:02
Damn, even the latest tray area fixes in git master didn't fix skype's icon...

**Comment by dawidm** [comment] 2016-03-25 23:39
Same issue, Mate 1.12.
![screenshot at 2016-03-26 00 36 45](https://cloud.githubusercontent.com/assets/6854796/14056355/1b50f826-f2eb-11e5-91c0-d98da754b46b.png)

**Comment by Marko-M** [comment] 2016-06-18 18:07
Ubuntu Mate 16.04 with Mate up to 1.14.1 - still here.

**Comment by ewangi** [comment] 2016-12-21 20:43
In case it may be of interest, the creator of the CopyQ application (https://github.com/hluk/CopyQ/), one of the applications affected by this bug, has narrowed it down to the use of SVG icons in the notifications area. Accordingly PNG icons were added in the application's latest beta and this appears to resolve the problem. CopyQ is a qt application, which may be an additional causal factor.

**Comment by monsta** [comment] 2017-03-15 10:56
Now that MATE 1.18 is released with GTK+3 only code, this might be actually fixed. I can't reproduce it anymore with Skype 4.3 (and Skype didn't get any updates for months).

Can anyone test this again with MATE 1.18? Or 1.16 if your distro used GTK+3 build of it (examples: Debian Testing/Unstable, Ubuntu 16.10).

**Comment by cwendling** [comment] 2017-03-15 11:00
New [SNI](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) support might also help Qt apps (together *sni-qt* for Qt4)

**Comment by monsta** [comment] 2017-03-15 11:04
Indeed, but I just found my old comment above, now I remember I already tested it with GTK+3 in 2014... and couldn't reproduce the issue.

**Comment by monsta** [comment] 2017-04-11 13:27
Ok, looks like with GTK+3 the bug isn't coming back, so closing as fixed.

**Closed by monsta** 2017-04-11 13:27 UTC
Labels: confirmed
