### ISSUE TITLE
Menus on MATE Panel do not have up and down scroll buttons on low screen resolutions or with long lists

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-panel#920] opened 2019-02-03 10:26 UTC
#### Expected behaviour
applications menu has scroll buttons as shown on screenshot from Ubuntu MATE 16.04 LTS:

![1604-top](https://user-images.githubusercontent.com/309456/52175582-f46fa780-27b6-11e9-8cf5-a7580c743f9a.png)

#### Actual behaviour
applications menu does not have scroll buttons and looks non-intuitive as shown on screenshot from Ubuntu MATE 18.04 LTS:

![1804-top](https://user-images.githubusercontent.com/309456/52175588-094c3b00-27b7-11e9-90f5-f054925f6350.png)

#### Steps to reproduce the behaviour
1. Have Ubuntu 18.04 LTS (or newer) installed
2. Switch MATE Panel layout to Traditional
3. Install many applications to get scrolling in Applications, Places, System menu (or change screen resolution to minimal - it is easy on VM)
4. Open Applications (or Places, or System) menu

#### MATE general version
1.20 as in Ubuntu MATE 18.04 LTS 

#### Package version
mate-panel 1.20.1-3ubuntu1

#### Linux Distribution
Ubuntu 18.04 LTS

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/mate-panel/+bug/1814421

---

Notes: this bug is actual for Ubuntu 18.04 LTS, 18.10 and upcoming Ubuntu 19.04 with Debian 10.

**Comment by lukefromdc** [comment] 2019-02-03 21:06
CONFIRMED on Debian Unstable: even worse, those areas of the menu that render off-screen are not displayed. I need to see if this is fallout from GTK changes or from replacing deprecated gtk_menu_popup with gtk_menu_popup_at_widget (testing the panel button here)

To duplicate this bug, first turn off icons on the desktop in dconf-editor so you don't rearrance your desktop icons. Then open up the display capplet and lower screen resolution until menus no longer fit the screen. Other menus sometimes show scrollbars when they get an item added but don't get resized so its not lik GTK just made this impossible.

**Comment by lukefromdc** [comment] 2019-02-03 22:12
I tested gnome-panel, and found that gnome-panel's menu button will show scrollbars but NOT the menubar. 

I also found the scrollbars in mate-panel's menubutton work fine with gtk3 rolled back to gtk-3.22.30 so we have either a gtk change that we need to adapt to or a gtk bug, not sure which. The gnome-panel code is a bit more complex, my guess is the menu is not getting this display size constraints passed to it with GTK 3.24 in our code but is getting it OK in gnome-panel's menu button (but not their menu bar)

**Comment by lukefromdc** [comment] 2019-02-03 22:45
I just found that adding 
gtk_menu_reposition(button->priv->menu);
will fix this, PR coming shortly

**Comment by lukefromdc** [comment] 2019-02-03 23:43
So far I have been able to fix the menu button and the alt-F1 menu popup but NOT the menubar, that code might be internal to GTK and beyond our reach without reimplementing menubar. That might explain why the menubar has this issue in gnome-panel too.

I tested rolling back mate-panel and mate-menus all the way to a 1.18 version (before any of the popup deprecation work) and the menubar still would not show scrollbars. This again shows that the change is inside GTK.

**Comment by lukefromdc** [comment] 2019-02-03 23:54
https://github.com/mate-desktop/mate-panel/pull/922
fixes the button and alt-F1 menus, but NOT the menubar menus.
Maybe @muktupavels can find out if a change to GtkMenu needs work on this end or if there is a bug in GTK itself that needs to be fixed on that end?

**Comment by N0rbert** [comment] 2019-02-04 09:15
Thank you for analysis, @lukefromdc! 
I forgot to mention that I first seen this issue in full-screen 1366x768 resolution after installation of all Debian Edu packages on Buster/sid (10) with MATE 1.20.4 and by opening Applications→Education (it was very long list without scroll arrows):
![debian-edu10](https://user-images.githubusercontent.com/309456/52198996-d3ba5700-2875-11e9-8dab-4153441d37d4.png)
I have opened `mozo` (_Main Menu_ window) in the right to show that KGeography is not really last position of the list.

**Comment by muktupavels** [comment] 2019-02-04 11:42
I would suggest to first retest with current GTK 3-24 branch (if that has not been done already):
https://gitlab.gnome.org/GNOME/gtk/commits/gtk-3-24/gtk/gtkmenu.c

And in case it is still reproducible open issue in GTK...

**Comment by lukefromdc** [comment] 2019-02-04 21:05
I see GTK 3.24.5 just came out, I will build and test that now

**Comment by muktupavels** [comment] 2019-02-04 22:46
Perhaps it is time to create one? After all GTK is important part of your desktop environment...

**Comment by lukefromdc** [comment] 2019-02-05 04:30
The issue seems to be a new case of 
https://gitlab.gnome.org/GNOME/gtk/issues/17
which may have been the reason for those three menu commits.

**Comment by lukefromdc** [comment] 2019-02-05 04:38
Just posted
https://gitlab.gnome.org/GNOME/gtk/issues/17#note_429104
"menus don't scroll anymore"
as that issue is a months-old example of similar behavior that apparently has gotten more extensive

**Comment by lukefromdc** [comment] 2019-02-07 01:02
https://gitlab.gnome.org/GNOME/gtk/merge_requests/565
fixes this, so if get gets merged we will be able to close this

**Comment by raveit65** [comment] 2019-02-07 22:37
I did run for myself in this issue with fedora rawhide.
No chance to select a keyboard layout from `mate-keyboard-properties` UI for my language :-/
So this issue isn't limited to the panel.

**Comment by lukefromdc** [comment] 2019-02-08 00:01
https://gitlab.gnome.org/GNOME/gtk/merge_requests/565 has been merged with
https://gitlab.gnome.org/GNOME/gtk/commit/1d4eac211c09624d29b9309e2b92173f7477a9b7
which will be included in GTK 3.24.6 whenever it is released, so we can now close this. Fix is in GTK's git master

**Closed** 2019-02-08 00:01 UTC
Labels: confirmed
