### ISSUE TITLE
Clock display overlaps numbers

### ISSUE THREAD

**Issue by gramo44** [mate-desktop/mate-panel#635] opened 2017-08-02 20:03 UTC
#### Expected behaviour
I need to see date and time into panel by adding the clock applet

#### Actual behaviour
Clock applet appears fine the first time but it did not refresh the display.
It just writes date-time information overlapping the previous information.
That causes, after some time, that display turns unreadable.

#### Steps to reproduce the behaviour
I had Mate Panel on Mageia 5 (full updated on july 25), the clock worked fine then
I reinstall Mageia, with Mageia 6, (I did'nt format /home partition so the settings are the same)

#### MATE general version
Previous mate 1.8.1-4 (the one which stablished configuration parameters)
MATE Desktop Environment 1.18.0

#### Package version
Previous mate panel 1.8.1
Current Mate panel 1.18.2 (spanish)

#### Linux Distribution
Mageia

#### Link to downstream report of your Distribution
don't know

**Comment by lukefromdc** [comment] 2017-08-02 20:22
Is the clock applet built in-process? If so, your mate-panel package will include a file named libclock-applet.so and if not there will be a file named libclock-applet . 

If you have the clock applet built in-process, this is the same as https://github.com/mate-desktop/mate-panel/issues/468 and is a redraw failure. Some upstream library change fixed this in Debian Unstable, possily prior to you last update but that is a different distro. Thus 
https://github.com/mate-desktop/mate-panel/issues/468 is still an issue. 
https://github.com/mate-desktop/mate-panel/pull/622
will fix this if merged but is a complex set of changes

**Comment by raveit65** [comment] 2017-08-02 20:24
I can't reproduce that fedora.
Maybe a Mageia problem.
Sadly , you didn't filed out a downstream report to camm your distro maintainer.
Sorry, i have to wait for his opinion before i can work on it ;-)

> Link to downstream report of your Distribution

don't know

**Comment by lukefromdc** [comment] 2017-08-02 20:27
What GTK 3 version was used in Mageia, and was mate-panel built with GTK3 or with GTK2? MATE 1.18 and later always use GTK3 while all distros shipped 1.14 and earlier built with GTK 2. MATE 1.16 was built with GTK 3 by some distros(such as Debian and Ubuntu) and built with GTK2 by others(such as Mint)

**Comment by gramo44** [comment] 2017-08-02 20:39
Mageia 5 and Mageia 6 are both using the same gtk

# rpm -qa | grep ^gtk | sort
gtk+2.0-2.24.31-3.mga6
gtk2-theme-engines-2.20.2-6.mga6
gtk+3.0-3.22.16-1.mga6
gtk-murrine-engine-0.98.2-7.mga6
gtksourceview-3.24.2-1.mga6
gtkspell-2.0.16-11.mga6
gtkspell3-3.0.9-3.mga6
gtk-vnc-i18n-0.6.0-3.mga6

**Comment by lukefromdc** [comment] 2017-08-02 22:25
Yeah-that's the version of GTK3 that created redraw issues: any GTK 3.22. I have literally never interacted with Mageia but if the older version used MATE 1.16 or earlier and built it with GTK2 you would not have seen the redraw issue, as it is GTK 3.22 only

**Comment by gramo44** [comment] 2017-08-03 01:59
Yes!, this is the same as #468 
If I set solid background, clock works fine!

**Comment by lukefromdc** [comment] 2017-08-04 04:34
This is still going on in Debian Unstavble as well, turns out what made it disappear was nothing  more than having a system background that matches the custom background tested-and being on the system background, which always works

**Comment by gramo44** [comment] 2017-08-04 15:06
The odd thing is that I was working with the same configuration on Mageia 5, and it was working fine. Same background, same transparency.
When I switch to Mageia 6 I did't format /home partition

**Comment by lukefromdc** [comment] 2017-08-04 17:25
Formatting /home would have no effect at all, the only thing I can imagine would be if you previously had a version of MATE built with GTK2 instead of GTK3, since you say the GTK versions installed did not change.

**Comment by lukefromdc** [comment] 2017-08-15 06:35
This should now be fixed as of the mate-panel 1.19.3 release by a range of commits
025a11f
through
9f43dd5
which remove the GtkPlugs from in-process applets, turning them transparent over the panel.
EDIT: This stops the redraw problems with the in-process applets. The later commits in this range stop warnings and segfaults on removing in-process applets, so they can be added and removed freely.

If you find this problem is not all the way gone with a build of 1.19.3 as released or later, feel free to reopen it. For distros to be free of this they will need to either pick up 1.19.3 or (more likely) wait until mate-panel 1.20.

**Closed by lukefromdc** 2017-08-15 06:35 UTC
