### ISSUE TITLE
Window List should display window titles when Panel is not expanded

### ISSUE THREAD

**Issue by darkoni** [mate-desktop/mate-panel#797] opened 2018-04-28 11:44 UTC
#### Expected behaviour

Window List should display window titles when Panel is not expanded.
When Panel is expanded, window titles are shown ok.

#### Steps to reproduce the behaviour

1) Make Panel [x] Expand
2) Add Window List to Panel - window titles are displayed
3) Make Panel [ ] Expand - in Window list, window titles are not displayed, only space is reserved where window tiles should be displayed.

#### MATE general version

1.20.1.

#### Package version

Window List 1.20.1

#### Linux Distribution

Fedora 27
Linux 4.15.17-300.fc27.x86_64 #1 SMP Thu Apr 12 18:19:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by raveit65** [comment] 2018-04-28 12:56
wtf, confirmed with master.

**Comment by raveit65** [comment] 2018-04-28 13:49
@darkoni 
I need to know the exact mate-panel package version, please post the result of
'rpm -qa mate-panel'
There is more than one 1.20.1 package version built for f27 repos.

**Comment by raveit65** [comment] 2018-04-28 14:28
I could track down the problem, it occurs if panel is build with
` --with-in-process-applets=all` configure flag.
If panel is build with  --with-in-process-applets=none than the windows-list applet is still visible like before.
I switch building panel for 1.20 in f27 to buiild in process because it is better for HIDIPI support.
Steps to reproduce:
1. build panel in process
2. create an empty panel
3. add the windows-list applet
4. un-expand the panel

@lukefromdc 
Can you please take a look into it?

@darkoni 
You can rebuild the rpm with `--with-in-process-applets=none` as quick workaround.

**Comment by darkoni** [comment] 2018-04-28 15:02
rpm -qa mate-panel
mate-panel-1.20.1-4.fc27.x86_64

**Comment by raveit65** [comment] 2018-04-28 15:51
well, i switched with 1.20.1-2.fc27.x86_64 to build in-process applets.
You can try downgrade to 1.20.1-1.fc27.x86_64 or just rebuild current version for the moment.

**Comment by darkoni** [comment] 2018-04-28 17:39
@raveit65 

i can not find  1.20.1-1.fc27.x86_64  so i downgraded to  1.19.3-2.fc27.x86_64

# dnf install mate-panel-1.19.3-2.fc27.x86_64

many thx

ps: i hope mate-panel-1.20.1-5.fc27.x86_64 or some other version will be ready in future,
if not, i see that i can easily downgrade to 1.19.3-2.fc27.x86_64

**Comment by raveit65** [comment] 2018-04-28 18:40
@darkoni 
You can download 1.20.1-1.fc27.x86_64 at fedora koji build-server and install by hand.
https://koji.fedoraproject.org/koji/buildinfo?buildID=1066848

@lukefromdc 
I feel with you :)
There is a little area (grip/handle of the panel) at left and right edge of horz. panels where right-click- menu is working.
I suggest to use always a new panel for testing because that thus can be deleted in dconf-editor if nothing else is working.

Np, At least i can fedora switch back to out-of-process build, if we find no solution.

**Comment by lukefromdc** [comment] 2018-04-28 20:11
I just used a new panel for testing , had to first set it not to expand (we now get a minimum width so it can be right-clicked on when empty. Have to close the preferences dialog to get not expanding to apply. I then found that the window list was not rendered AT ALL, though the panel was expanded by the amount of space needed to accomodate both the icons and the text. Clicks on the space used by it go the the panel toplevel, so it is as if the window list was not even on the panel. Minimize window animations also do not even attempt to go to where the button should be on the panel unless expand is set.

Worst of all, all of this is silent with no text showing up in terminal. The window list is thus completely broken when expand is not set and it is built in-process, and I have no idea why and no starting point for it. I will now test GNOME panel, see what happens there.

**Comment by lukefromdc** [comment] 2018-04-28 23:01
This turned out to have a rather simple fix, found by looking for the word "EXPAND" in window-list.c 
https://github.com/mate-desktop/mate-panel/pull/798
In the process I found another issue present also in master blocking removal of the clock, window-list, and workspace switcher (in-process) from an unexpanded panel, will open a new issue for that.

**Comment by lukefromdc** [comment] 2018-04-28 23:13
In my test, I got both the icons and the text, a fully normal looking window list on both the expanded and now the non-expanded panel. Also tested an out-of-process build, that too worked fine

**Comment by lukefromdc** [comment] 2018-04-28 23:14
Space taken by applet still expands and contracts with the number of open windows with the PR

**Comment by lukefromdc** [comment] 2018-04-28 23:52
Just found a nasty side-effect of my initial fix:
It causes the window list when overfilled to expand to the left past it's origjnal position over other applets, and that locking it to the panel does not stop it. Seems that MATE_PANEL_APPLET_EXPAND_MAJOR both causes the problem and also keeps the window-list from being pushed left

**Comment by lukefromdc** [comment] 2018-04-30 00:40
I just confirmed that the window list is the only applet using MATE_PANEL_APPLET_EXPAND_MAJOR in the panel itself, meaning it's the only applet that can both set that flag and be built in process. Without it it is not stopped from expanding left and pushing away anything to its left.

**Comment by lukefromdc** [comment] 2018-04-30 02:02
On continued testing, it looks like what is actually happening is that zero size is being allocated for the window list when the panel is set not to expand. I followed the code to the applet_size_allocate function and within it to wnck_tasklist_get_size_hint_list, still in window-list.c . Disabling either one causes the window list to appear on an unexpanded panel-but also to push itself over other applets, as this is the function that limits its length to available space. Apparently this gets redefined as zero on an unexpanded panel when (and for some reason only when) the applet is in process.  Since the offending function may be  is in wnck itself, but gnome-panel uses the same version of wnck and works. There is extra code to set a length for the applet in gnome-panel but it did not work here in an initial test, I think it has to be used elswhere after being set

**Comment by lukefromdc** [comment] 2018-04-30 03:07
I cannot find any GNOME commits that fix this, though it works in gnome-panel. The odd thing is this apparent zero size allocation for rendering the window-list combined with the panel still expanding as though it was being correctly computed somewhere but not passed back to the applet for rendering. At the moment I am out of ideas on this one

**Comment by lukefromdc** [comment] 2018-04-30 03:12
It's worth keeping in mind that a window list on an unexpanded panel requires the panel to expand and contract with the number or open windows on that workspace. That part works, question is how many users set up a panel like this? I've got many hours in this already and may not be able to fix it. If a wayland transition forces in-process builds, we might lose this feature.

**Comment by lukefromdc** [comment] 2018-05-01 00:39
I just did some testing, reinstalling my old saved Debian packages. Turns out the refusal to render the window list on a nonexpanded panel when built in-process is a very old bug, going all the way back to mate-panel 1.10 when built with GTK3.  Thus what we have here is a bug in the GTK3 porting itself-unless the problem also appears on GTK2 builds of 1.10, that is.

That means neither the GtkPlug work to support custom backgrounds that GTK 3.20 required, nor the later removal of GtkSockets and related commits for in-process applets have anything to do with this. The bug was already there, we just hadn't gotten any reports of it yet. Distros began using GTK 3 with mate-panel 1.16, a year and a half ago and nobody found or reported this until April this year.

**Comment by lukefromdc** [comment] 2018-05-01 01:07
Even on Linux Mint 17.1 with mate-panel 1.8 built with GTK2 and all applets out of process this is buggy: in that case, switching a nonexpanded panel containing the window list back to expanded causes the window list to disappear even after restarting the panel, only to sometimes appear twice if added back. In short, the window list on a nonexpanded panel has long been buggy

**Comment by darkoni** [comment] 2018-05-01 08:40
@lukefromdc 

First of all, thx for your investigation.

I am using the same settings of desktop and Panel since long time ago. And now, as upgraded to Fedora 27, i was suprissed that i can not see Window list on not expanded Panel.

![panel](https://user-images.githubusercontent.com/153441/39466970-d8f4230c-4d2b-11e8-8475-51b0ac2387a5.png)

On bottom left side i have a default panel with clock and menu and few shortcuts to start FF, terminal and Caja.

On botom right side i have not expanded Panel with Window list and Workspace Switcher.

The same configuration i have at my office, on Linux Mint 18, also with Mate.

Fix for Fedora 27 - downgrade mate-panel to version that works as expected, at least for me.
```
# dnf install mate-panel-1.19.3-2.fc27.x86_64
```

**Comment by lukefromdc** [comment] 2018-05-06 20:00
Presumably that older mate-panel package is one built with the window list out of process, as the bug goes at least back to mate-panel 1.10 with GTK3

**Comment by raveit65** [comment] 2018-05-07 06:01
Yes, older mate-panel rpm is build with out- of-process applets.
https://src.fedoraproject.org/cgit/rpms/mate-panel.git/commit/?h=f28&id=7978a516a6a7f5cfdd6472006b8921b0cb487744

I just tested a actual panel build with with out- of-process applets and sadly i have weird redraw issues with the windows-list applet  with using HIDPI scaling, sometimes.
I posted a screenshot already here https://github.com/mate-desktop/mate-panel/pull/755#issuecomment-374868245
Well, those glitches goes away if i change workspaces.
But both kind of builds aren't optimal.

@vkareh 
Any thoughts?

**Comment by lukefromdc** [comment] 2018-05-07 06:30
How many users use a non-expanded panel with the window list in it, and how many use HiDPI panels? That tells distros which way to build until one or the other bugs is squashed, and this but is an old one at least in GTK3. I cannot figure out how to fix it at this point, though as usual it does not occur in gnome-panel. No idea in the world where the difference is, maybe in their orignal GTK3 port?

**Comment by raveit65** [comment] 2018-05-07 06:50
> How many users use a non-expanded panel with the window list in it, and how many use HiDPI panels? 

With fedora we have found 2 user with which needs different builds of mate-panel. Reporter and me :)
If we found no solution i will switch back to out-of-process, as personal i can live with the redraw issue, btw, it's easy for me to rebuild the panel local with in-process build option.

I think we should not break old features in favor of new ones, because most MATE user like to use the old gnome2 features.

**Comment by lukefromdc** [comment] 2018-05-07 06:55
https://github.com/mate-desktop/mate-panel/pull/755
was supposed to fix that and is included in mate-panel 1.20.1. Is that what you are building or an older version? If you are, than more work is needed to force consistant redrawing.

**Comment by raveit65** [comment] 2018-05-07 07:01
> #755
was supposed to fix that (EDIT-the redraw problems) and is included in mate-panel 1.20.1. Is that what you are building or an older version? If you are, than more work is needed to force consistant redrawing.

I used always latest master + open PRs. And https://github.com/mate-desktop/mate-panel/pull/755
doesn't fix the double buttons from my screenshot.
Well, as i said it happens not very often and i can trigger  a redraw with switching workspaces.

**Comment by lukefromdc** [comment] 2018-05-07 07:09
OK, I will have to have another look at that tomorrow, but will have to be able to duplicate it to test. Will see what I can do.

**Comment by lukefromdc** [comment] 2018-05-08 01:54
Try new PR
https://github.com/mate-desktop/mate-panel/pull/806
which lets the window list render properly on a nonexpanded panel with wncklet in-process. Unlike last time, it does not lead to over-expansion of the taskbar to the left or over other widgets. Note that one problem remains: on switching the panel from unexpanded to expanded, the window list moves as far right as it can, compressing the buttons to zero width. Workaround is to drag it back to the desired position, where it will stay.

**Comment by raveit65** [comment] 2018-05-08 08:49
Related PR fixes the issue, tested with vertical and horizontal panel.

**Comment by raveit65** [comment] 2018-05-08 08:57
> Note that one problem remains: on switching the panel from unexpanded to expanded, the window list moves as far right as it can, compressing the buttons to zero width. Workaround is to drag it back to the desired position, where it will stay.

Well this was still there before, and happens not if an other applet is at the right side of the panel.
So, i think we can ignore it for the moment.
Let's wait until someone report it :)

**Comment by raveit65** [comment] 2018-05-08 09:14
@darkoni 
Can you please test this build for f27 from fedora build server?
https://koji.fedoraproject.org/koji/taskinfo?taskID=26847338
Follow links for your arch for downloading rpms.
If it works for you i will push that soon to fedora.

**Comment by darkoni** [comment] 2018-05-08 16:46
I wish to test it - but i already switched to Fedora 28, on all my comps.

Please, could you build it for F28 ?

**Comment by raveit65** [comment] 2018-05-08 17:19
@darkoni 
here we go (ignore the failed arch, build is fine)
https://koji.fedoraproject.org/koji/taskinfo?taskID=26850672

**Comment by darkoni** [comment] 2018-05-08 19:10
Here is what i did for test
```
wget https://kojipkgs.fedoraproject.org//work/tasks/673/26850673/mate-panel-1.20.1-7.fc28.x86_64.rpm
wget https://kojipkgs.fedoraproject.org//work/tasks/673/26850673/mate-panel-libs-1.20.1-7.fc28.x86_64.rpm
```
```
ls -al
 1.795.960 May  8 19:11 mate-panel-1.20.1-7.fc28.x86_64.rpm
    52.532 May  8 19:11 mate-panel-libs-1.20.1-7.fc28.x86_64.rpm
```
```
sudo rpm -Uvh \
 mate-panel-1.20.1-7.fc28.x86_64.rpm \
 mate-panel-libs-1.20.1-7.fc28.x86_64.rpm
```
```
Preparing...                          ################################# [100%]
Updating / installing...
   1:mate-panel-libs-1.20.1-7.fc28    ################################# [ 25%]
   2:mate-panel-1.20.1-7.fc28         ################################# [ 50%]
Cleaning up / removing...
   3:mate-panel-1.19.3-2.fc28         ################################# [ 75%]
   4:mate-panel-libs-1.19.3-2.fc28    ################################# [100%]
```
```
rpm -qa mate-panel
mate-panel-1.20.1-7.fc28.x86_64
```

And - sorry i have to said - **it is not good** :(

In NOT expanded state - Window List is displayed, but on right side of Workspace Switcher - maybe i can live with that.

In expanded state - Window List is NOT displayed. I even put Clock Applet and Command Applet, but it does not help - Window List is NOT displayed, or i can not see Window Buttons...

Sorry...

Can i help more ?

**Comment by lukefromdc** [comment] 2018-05-08 19:46
When switching from non-expanded BACK to expanded, the window list gets
moved all the way to the right, such that only the handle is visible and the buttons
are compressed to zero width. Try dragging that handle back to the left, if you
do not then get the buttons we have another problem. Replying by email as I
am on the road and do not have my Github stuff on the laptop

**Comment by raveit65** [comment] 2018-05-08 19:50
@darkoni 
Did you reload the panel after installing new version?
'killall mate-panel'

**Comment by darkoni** [comment] 2018-05-08 19:58
```
reboot
```

**Comment by raveit65** [comment] 2018-05-08 20:02
Luke is right, if you don't see the window-list applet in expand state of the panel, the applet is at the right edge of the panel. Here you can do a right-click on the last pixels to see the context-menu of the applet.
Than move the applet to the right place.

**Comment by darkoni** [comment] 2018-05-08 20:29
YES !!!

Now the window list is displayed in expandend Panel :)

I have to say that is very weird behaviour ;)

End now - in the NOT expanded Panel, the Window List is on the left side - as i am used.

Hey - many thnx @raveit65 and @lukefromdc 

I can say it works.

But, some help text will be very useful - explaining that trick with selecting right most pixel with right-click and moving Window List applet to the left side of Workspace Switcher.

Or, more usefull - maybe you could make that Window List applet has some default width, which is not zero pixels ;)

**Comment by lukefromdc** [comment] 2018-05-08 20:47
I might be able to set a minimum width somewhere, which also would help panel
behavior in the non-expanded/nothing but the window list case.

**Comment by raveit65** [comment] 2018-05-09 05:17
Looks like there is another problem with building the panel with -with-in-process-applets=all
https://bugzilla.redhat.com/show_bug.cgi?id=1575091

**Comment by lukefromdc** [comment] 2018-05-09 06:47
Setting a minimum width did nothing, but then I decided to test the panel on the left, right, and bottom as well as the top (my usual position for a test panel) and did not get the problem with the window list moving to the end when returning to expanded mode. Oddly, once I put it back on top, I no longer had that problem there either, even when removing that panel and making a new one, restarting, whatever. 

My theme, BTW, already sets a miniumum width and height on all buttons in the panel.

**Closed** 2018-05-10 21:28 UTC
Labels: confirmed

**Comment by raveit65** [comment] 2018-05-17 08:39
> My theme, BTW, already sets a miniumum width and height on all buttons in the panel.

Reporter use BlueMenta in screenshot.
All themes from us sets a miniumum width and height as general settings for button widget in gtk-widget.css.
