### ISSUE TITLE
GTK3: Panel is transparent with the Adwaita theme

### ISSUE THREAD

**Issue by City-busz** [mate-desktop/mate-panel#329] opened 2015-07-25 23:12 UTC
If the panel background is set to none (which is the default setting), and the Adwaita theme used, the panel has transparent background. The expected result is to use Adwaita's default background color.

Adwaita is the default GTK+ theme since version 3.14.

**Comment by infirit** [comment] 2015-07-26 00:42
Duplicate of https://github.com/mate-desktop/mate-panel/issues/217

**Closed by infirit** 2015-07-26 00:42 UTC
