### ISSUE TITLE
Underscores from window titles are removed in window list (but not tooltip)

### ISSUE THREAD

**Issue by insaner** [mate-desktop/mate-panel#1005] opened 2019-07-25 06:51 UTC
Using:
mate-panel-1.20.3-1.fc27.i686

From the attached (cropped) screengrab, you can see that mate-panel is removing the underscores (_) from window titles. In fact, it seems to be just the first, when in a series of underscores, that is removed (if two underscores in a row, the title in the list only has one; if there are three underscores in a row, the title only has two).

Interestingly, when I hover over the title in the list, a popup/tooltip/hint appears (in yellow) which _does_ contain them!

I could not find a setting in dconf-editor to modify this behavior, and I rely on underscores to properly organize my window list in mate-panel (I have many browser windows open, for example, and use prefixed underscores to move certain windows to the top of the list). Also, some titles don't make sense without the underscores as these are sometimes used as word separators instead of spaces.

![underscores](https://user-images.githubusercontent.com/6283329/61852003-61bae600-ae86-11e9-98dd-ffbf255055f0.png)

**Comment by cwendling** [comment] 2019-07-25 07:46
Sounds like the applet is reading the string as containing mnemonics, which it most probably shouldn't.

**Comment by insaner** [comment] 2019-08-10 08:41
Is there a workaround I could use for the time being?

**Comment by insaner** [comment] 2020-02-08 10:42
Still present in mate-panel-1.22.2-1.fc30.i686

if someone just points me into the right direction I might be able to take a quick look into this and try to provide a fix.

**Comment by insaner** [comment] 2020-02-09 10:43
Still present in mate-panel-1.22.2-1.fc30.i686

**Comment by raveit65** [comment] 2020-02-09 11:03
Which website uses underscores in their title for reproducing this with chromium browser?
Are you using system decoration (metacity theme) for your chromium browser.

**Comment by rbuj** [comment] 2020-02-09 11:11
test:
```shell
$ pluma "_this_is_a_test.txt"
```
![pluma](https://user-images.githubusercontent.com/10171411/74101000-52a33900-4b35-11ea-9b14-22f818238cb5.png)

**Comment by raveit65** [comment] 2020-02-09 14:49
Ahh, so it happens with pluma too and it's not related to use a internet browser.
Confirmed.

**Comment by cwendling** [comment] 2020-02-11 09:37
Following up on https://github.com/mate-desktop/mate-panel/pull/806#issuecomment-583830133: I would think it's a mere matter of adding [`gtk_menu_item_set_use_underline(, item, FALSE)`](https://developer.gnome.org/gtk3/stable/GtkMenuItem.html#gtk-menu-item-set-use-underline) or some other way of not having it consider underscores as mnemonics (e.g. not using [`gtk_menu_item_new_with_mnemonic()`](https://developer.gnome.org/gtk3/stable/GtkMenuItem.html#gtk-menu-item-new-with-mnemonic)).  I don't have time to look at this and fix it, but I'd think it'd be revolving around this.

**Comment by insaner** [comment] 2020-02-11 09:41
I think that's the clue I needed. Will test some things and report back soon. Thanks!

**Comment by insaner** [comment] 2020-02-11 10:57
Btw, mate-panel's autogen.sh is missing checks for the presence of:

startup-notification-devel
dconf-devel

**Comment by raveit65** [comment] 2020-02-11 13:10
> Should I create separate issues for each of these?

No, please not.

**Comment by insaner** [comment] 2020-02-11 13:27
Ok no problem. I've been at this all night, but I can't find where the problem lies. I'm thinking of calling it quits at this point. If someone else can fix it, that would be great.

**Comment by cwendling** [comment] 2020-02-11 13:42
@insaner It's actually inside [libwnck](https://gitlab.gnome.org/GNOME/libwnck), see [1](https://gitlab.gnome.org/GNOME/libwnck/blob/master/libwnck/selector.c#L523), [2](https://gitlab.gnome.org/GNOME/libwnck/blob/master/libwnck/wnck-image-menu-item.c#L153) and [3](https://gitlab.gnome.org/GNOME/libwnck/blob/master/libwnck/wnck-image-menu-item.c#L199).  Not sure if `WnckImageMenuItem` is used in places where the mnemonics make sense, but anyway there's what need be fixed.  You can report it there as well I guess.

**Comment by insaner** [comment] 2020-02-11 13:45
@cwendling Does that mean it has to be fixed in libwnck, and cannot be fixed in the mate-panel code?

**Comment by cwendling** [comment] 2020-02-11 13:46
@infirit yes

**Comment by vkareh** [comment] 2020-02-11 13:48
libwnck queries X11 for the `_NET_WM_VISIBLE_NAME` window prop, if that's empty, then it uses `_NET_WM_NAME`, which contains underscores correctly. The name seems to be sent as-is, I can't find anywhere in libwnck where this would be styled to remove underscores...

**Comment by vkareh** [comment] 2020-02-11 13:49
Okay, seems like I was wrong. @cwendling seems to have found it

**Comment by vkareh** [comment] 2020-02-11 13:51
This seems to fix it:
```diff
diff --git a/libwnck/wnck-image-menu-item.c b/libwnck/wnck-image-menu-item.c
index 94c7ed7..b278bb4 100644
--- a/libwnck/wnck-image-menu-item.c
+++ b/libwnck/wnck-image-menu-item.c
@@ -150,7 +150,7 @@ wnck_image_menu_item_set_label (GtkMenuItem *menu_item,
       g_free (item->label);
       item->label = g_strdup (label);
 
-      gtk_label_set_text_with_mnemonic (GTK_LABEL (item->accel_label), label);
+      gtk_label_set_text (GTK_LABEL (item->accel_label), label);
       g_object_notify (G_OBJECT (menu_item), "label");
     }
 }
```

**Comment by cwendling** [comment] 2020-02-11 13:53
@vkareh something like this would most probably do indeed, but maybe also look at [3](https://gitlab.gnome.org/GNOME/libwnck/blob/master/libwnck/wnck-image-menu-item.c#L199).  Also, you should make sure nothing else is using WnckImageMenuItem in a way that requires mnemonics -- I did not, maybe there are none, or maybe there are some.

**Comment by insaner** [comment] 2020-02-11 13:55
@vkareh Awesome!
Thanks everyone! If you have created an issue on gnome's gitlab, please do link to it here. I look forward to this being finally resolved.

**Comment by insaner** [comment] 2020-02-11 13:57
Where in the mate-panel code is the relevant call to libwnck being made?

**Comment by cwendling** [comment] 2020-02-11 14:00
[applets/wncklet/window-menu.c:243](https://github.com/mate-desktop/mate-panel/tree/master/applets/wncklet/window-menu.c#L243)

**Comment by vkareh** [comment] 2020-02-11 14:00
@cwendling - changing `"use-underline"` to `FALSE` doesn't fix it...

**Comment by cwendling** [comment] 2020-02-11 14:02
@vkareh alone it won't, no, because the call you mentioned explicitly asks for `_with_mnemonic()`.  My point is that you probably want to remove that as well, and as the author seemed to have went to fairly great length to use mnemonics, there might be a reason for it.

**Comment by insaner** [comment] 2020-02-11 14:05
I tried adding a debug print line just above that in window-menu.c as follows:

printf ("window-menu.c: window_menu_applet_fill\n");

but it doesn't seem to be printing to the terminal, while the ones added to menu.c do print. What am I missing here? I'd love to know how to debug mate-panel to be able to help a little better in the future.

**Comment by vkareh** [comment] 2020-02-11 14:55
Filed an issue: https://gitlab.gnome.org/GNOME/libwnck/issues/142

**Comment by insaner** [comment] 2020-04-01 06:40
As mentioned in https://gitlab.gnome.org/GNOME/libwnck/issues/142 , I don't know if it breaks anything else, but I tested patching my libwnck3 (libwnck3-3.32.0-1.fc30.src.rpm on 32bit) with @vkareh's patch above and it solves it for me. If another patch is provided I would be happy to test. For now, this is what I will be using. Thanks, Victor!

**Comment by raveit65** [comment] 2023-07-23 18:11
Ok, this one is fixed by https://gitlab.gnome.org/GNOME/libwnck/-/merge_requests/50
Closing.

**Closed by raveit65** 2023-07-23 18:11 UTC
Labels: confirmed

**Comment by lukefromdc** [comment] 2023-07-23 19:17
Note that the cairo surface icon loading code probably is NOT going to be merged in libwnck (I have used a patched version for years)
https://gitlab.gnome.org/GNOME/libwnck/-/merge_requests/10
We are being advised to move the icon loading code OUT of libwnck and into mate-panel itself, though that may also require adding it to marco or compiz.

also libwnck is looking at moving to GTK4, which we have no intention of using in the forseeable future:
https://gitlab.gnome.org/GNOME/libwnck/-/merge_requests/18

Distros may have to either depend on an older version of libwnck, or we may have to fork it for our own use as it is now diverging from what we need

**Comment by muktupavels** [comment] 2023-07-23 19:39
> Note that the cairo surface icon loading code probably is NOT going to be merged in libwnck (I have used a patched version for years) 

Yes, in its current form it is not going to be merged! Getting icons as cairo_surface_t sooner or later is going to happen.

> https://gitlab.gnome.org/GNOME/libwnck/-/merge_requests/10 We are being advised to move the icon loading code OUT of libwnck and into mate-panel itself, though that may also require adding it to marco or compiz.

This sounds wrong...

> also libwnck is looking at moving to GTK4, which we have no intention of using in the forseeable future: https://gitlab.gnome.org/GNOME/libwnck/-/merge_requests/18

You make conclusion from ~3 years old draft? Look at https://gitlab.gnome.org/GNOME/libwnck/-/issues/150. The plan is to separate UI from main library so main library can be used without depending on any GTK version. There are no plans to remove GTK3 widgets...

> Distros may have to either depend on an older version of libwnck, or we may have to fork it for our own use as it is now diverging from what we need

**Comment by raveit65** [comment] 2023-07-23 19:45
> Distros may have to either depend on an older version of libwnck, or we may have to fork it for our own use as it is now diverging from what we need

+ 1 for reforking libwnck again, for several reason.
- Workspace switcher is already broken with libwnck
- libwnck dev do not work on PR from mate devs since nearly 3 or 4 years.
- and their roadmap looks like more breaks. https://gitlab.gnome.org/GNOME/libwnck/-/issues/150
- last but not least working with libwnck , gnome-flachback maintainer is very problematic. I' am really tired of him

So, reforking libwnck will solve a lot of problems, ihmo.

**Comment by lukefromdc** [comment] 2023-07-23 21:13
We could call the fork mate-wnck, first order of business would be to revert the breaking change in the workspace switcher, second would be to finish and merge the hidpi/cairo surface icon handling work.

compiz-reloaded would need a very simple port to build against it, matching what would would do in marco. This is why we would need to fork the library instead of adding the code to mate-panel. We don't want marco or compiz to have to depend on mate-panel as a whole
