### ISSUE TITLE
Mouse wheel behaves inconsistently wrt volume change in notification area and popup

### ISSUE THREAD

**Issue by karltk** [mate-desktop/mate-panel#914] opened 2019-01-24 12:48 UTC
#### Expected behaviour

I can scroll the mouse over the volume icon in the notification area, and the volume changes: When I scroll downwards, the volume increases; when I scroll upwards, the volume decreases. I would expect this scrolling behaviour to be same if I click on the notification area and use the mouse wheel to adjust the volume slider in the resulting popup.

#### Actual behaviour

The slider and the volume icon behave exactly opposite of each other! 

The direction of scrolling resulting in a volume increase when hovering over the icon in the notification area will *decease* the volume when hovering + scrolling over the volume slider in the popup.

#### Steps to reproduce the behaviour

1. Move mouse cursor over the sound icon in the notification area.
2. Scroll up, and notice change in volume.
3. Click the sound icon in the notification area.
4. Move the mouse cursor over the volume slider in the resulting popup.
5. Scroll up, and notice the change in volume.

On my machine, the volume changes in (2) and (5) are opposite, despite scrolling in the same direction.

#### Package version

mate-panel     1.20.3-1     amd64 

#### Linux Distribution
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"

#### Link to downstream report of your Distribution

N/A

**Comment by lukefromdc** [comment] 2019-01-24 20:07
The package involved here is actually mate-media, which contains the volume control applet. Please resubmit this issue against mate-media, as we cannot move an issue report between packages. Closing as this is the wrong package, waiting for a new issue against mate-media.

I tested this, and on my machine with Debian Unstable and locally compiled GTL 3.24.3 the scroll direction was the same for the icon and the slider. I know there were some changes in GTK3 concerning slider directions not too long ago, wondering if that is the difference? What exactly is the GTK3 version you have?

**Closed** 2019-01-24 20:08 UTC

**Comment by vkareh** [comment] 2019-01-26 16:11
Actually, just testing this and it seems like the issue is with the [mate-indicator-applet](https://github.com/mate-desktop/mate-indicator-applet). I've re-posted the issue there: https://github.com/mate-desktop/mate-indicator-applet/issues/36

**Comment by karltk** [comment] 2019-01-26 20:21
FWIW, my gtk3 version is `3.24.1-1ubuntu2` (amd64).

**Comment by lukefromdc** [comment] 2019-01-27 02:17
Ahh that explains why I did not get the same result. I assume you are using the sound indicator applet whose volume control is a HORIZONTAL slider? A vertical slider would create a huge box in an indicator as the only thing it can pop up is a menu, and a vertical slider in a menuitem would turn it into a box as high as the slider and as wide as the rest of the menu. Though I suppose it might be possible to make the menu as narrow as the slider, Ubuntu's indicator-sound applet packed the slider horizontally into the menuitem when I last saw it
