### ISSUE TITLE
Black vertical line in notification area

### ISSUE THREAD

**Issue by w3lifer** [mate-desktop/mate-panel#514] opened 2017-01-15 00:18 UTC
It is always displayed:
![screenshot at 2017-01-15 03-14-48](https://cloud.githubusercontent.com/assets/14075412/21959205/0157f860-dad1-11e6-90eb-6b788176282d.png)

---
Linux Mint 18 Sarah 64-bit
MATE Panel 1.14.2

**Comment by kn00tcn** [comment] 2017-02-08 01:16
most likely the theme has added a right border to separate the notification section from other panel items

is this mint-y theme or another one?

**Comment by w3lifer** [comment] 2017-02-09 19:36
@kn00tcn, this is mint. Perhaps this is due to the microphone icon. At the moment, it disappeared and there appear only sometimes.

**Comment by kn00tcn** [comment] 2017-02-10 01:52
microphone NOT speaker icon? what do you mean appears sometimes... when running an application that uses sound? what happens if you change the icon theme?

**Comment by monsta** [comment] 2017-11-24 12:14
I can't reproduce it. It might be solved in the next releases, especially 18.2 which has MATE migrated to GTK+3.

**Comment by kn00tcn** [comment] 2017-11-28 04:29
well i just noticed it appear during startup of xfce with bluementa theme for some miliseconds until the volume icon loaded (xfce4-pulseaudio-plugin in this case)

really leaning towards it being specific to icons or processes failing to load, i'd probably close this issue

**Comment by w3lifer** [comment] 2018-01-09 16:38
I do not know how to reproduce it, but it is, both on my working computer and on my home laptop.
![1](https://user-images.githubusercontent.com/14075412/34731872-a61ae3ee-f574-11e7-8b06-816a2f8dd31e.png)

**Comment by lukefromdc** [comment] 2018-01-09 18:34
I can't reproduce this either

**Comment by lukefromdc** [comment] 2018-01-09 18:35
If this is GTK2 it may well be gone with GTK3 versions

**Comment by monsta** [comment] 2018-01-18 18:37
@w3lifer: is it still the same version of Mint?

**Comment by w3lifer** [comment] 2018-01-29 17:54
@monsta, now version is 18.1 Serena.

**Comment by monsta** [comment] 2018-01-29 18:11
Ah, that one still uses GTK+2 build. In 18.2 and 18.3 MATE uses GTK+3.

**Comment by lukefromdc** [comment] 2018-01-29 19:59
Closing, this seems to be GTK2-only. Please reopen if you ever see this with a GTK3 build

**Closed** 2018-02-04 16:08 UTC
Labels: unconfirmed

**Comment by lukefromdc** [comment] 2018-04-11 02:46
Does the line appear and then the icon? If so, it might be that the icon is momentarily being loaded at zero width or at 1px. Remember that the tray hasd to expand to accomodate each icon, if the code is trying to render it before making the space, it will be limited to the available space, which could be just one px or so. Then the icon would display fully as the tray expands to take it.

**Comment by kn00tcn** [comment] 2018-04-11 04:45
i'm really leaning towards the icon, especially since i saw it happen in xfce (as the volume was loading) rather than mate

**Comment by w3lifer** [comment] 2018-04-11 17:51
@lukefromdc

![1](https://user-images.githubusercontent.com/14075412/38633997-fa42522a-3dc9-11e8-9d3d-55a220329355.gif)

**Comment by lukefromdc** [comment] 2018-04-11 19:57
Looks like the icon trying to add once, not finding the space (or just plain the tray icon crashing), then successfully adding a second time. If you watch closely, the tray starts expanding for the icon, then that process aborts and starts over. You might have a crashing and restarting tray icon here

**Comment by kn00tcn** [comment] 2018-04-12 02:57
when i look closely, to me it looks like a new icon was attempted on the right side, causing the entire tray area to enlarge towards the left by 1px, then when this new spot got removed, the tray area shrinks by 1px, revealing 'nothing' on the left side, like a gap between the window list panel item & the tray icons panel item
