### ISSUE TITLE
notification area applets cut in half vertically 

### ISSUE THREAD

**Issue by dimdam** [mate-desktop/mate-panel#746] opened 2018-02-25 20:15 UTC
#### Expected behaviour
full size indicators

#### Actual behaviour
chopped up icons

#### Steps to reproduce the behaviour
Its a very random issue ,happens on booting/rebooting but not all the time .
for example as shown in the picture the sound applet is cut in half :
![2018-02-25 14-44-00](https://user-images.githubusercontent.com/7516919/36645955-3a9f6cfa-1a79-11e8-886e-74b9b0b20027.png)

#### MATE general version
1.20.0

#### Linux Distribution
Manjaro MATE

#### Link to downstream report of your Distribution

https://bugs.manjaro.org/#ticket/zoom/17962

Additional info:

Kernel: 4.14.21-1-MANJARO
Shell: bash 4.4.19
Theme: Adapta-Eta-Maia [GTK2/3]
 Icons: Papirus-Maia [GTK2/3]
CPU: Intel i7-5500U (4) @ 3.000GHz
GPU: AMD Radeon R7 M260/M265
 GPU: Intel HD Graphics 5500

**Comment by info-cppsp** [comment] 2018-02-25 20:31
dup? #518 

is that the notification area applet or the indicator applet?
(right click - about)

what if you move it more to the left?

**Comment by lukefromdc** [comment] 2018-02-25 20:32
I see the icon is cut vertically. That is an old bug affecting all tray icons, looks like indicator icons get treated the same as all others. That's a clue as to where in the code the trouble (possibly a failure to (re)allocate enough size for the icon when first drawn must be: in code common to everything in the tray, or else in something that was cut and pasted when GNOME first wrote the code for sni support in gnome-panel. 

Confirm you are using an indicator for the volume control applet and not the default mate-media "mate-volume-control-applet" applet? mate-volume-control-applet is a traditional tray applet without an indicator mode

**Comment by dimdam** [comment] 2018-02-25 21:02
@info-cppsp @lukefromdc it is a notification area applet .

**Comment by lukefromdc** [comment] 2018-02-25 21:09
OK, it's not an indicator and has nothing to do with sni support then. I did notice that when I built network-manager-applet with SNI support it never got cut in half again, something which used to be a problem from time to time.  That suggests the code is in the tray icon code separate from sni support code

**Comment by dimdam** [comment] 2018-02-25 21:13
@lukefromdc  Can you please guide me on where i should get help about this?

**Comment by dimdam** [comment] 2018-02-26 21:51
Another image showing this random issue:
![2018-02-26 23-45-13](https://user-images.githubusercontent.com/7516919/36697390-8d071624-1b4f-11e8-8bea-80f739bda6c0.png)

Now the language selector is cut vertically too and date/time applet are not present.

**Comment by raveit65** [comment] 2018-02-27 10:07
Maybe your distro maintainer can reproduce the issue and help?
Sadly, you forgot to file out a report against your disro.
> Link to downstream report of your Distribution

**Comment by dimdam** [comment] 2018-02-27 14:00
@raveit65  Can you please show me how to do that?

**Comment by raveit65** [comment] 2018-02-27 14:10
I am using fedora and i've no clue about Manjaro infrastructure sites.
Maybe google helps?

**Comment by info-cppsp** [comment] 2018-02-27 15:39
https://bugs.manjaro.org/#login
or
https://manjaro.org/feedback/

no?

**Comment by dimdam** [comment] 2018-02-27 16:20
I  just opened a ticket in bugs.manjaro.org,thank you @info-cppsp . Updated first post as well

**Comment by lukefromdc** [comment] 2018-07-02 18:54
https://github.com/mate-desktop/mate-panel/pull/833 has been merged, should reduce the frequency of this but since it can still occur I am now looking at trying to refactor the code for drawing the icons, which dates back to GTK2 and an entirely different drawing model

**Comment by lukefromdc** [comment] 2018-07-03 17:10
Yesterday's refactoring attempts worked most of the time but made matter worse when an icon was cut. I did some digging, and this problem may actually come from issues with GtkStatusIcon itself, which is called not by the tray but the application placing a tray icon-and being deprecated probably is not maintained by GNOME.

In researching the Freedesktop.org tray specification I found that the icon is actually loaded by the application calling GtkStatusIcon, and the icon window containing that icon is all that is passed to the tray.  If that application does not finish drawing the icon window (they always are cut on the right), this would cause a partial icon to be passed to the tray and there is nothing the tray can do about that as it does not even get the icon name. If the icon name were passed, then the iconwindow passed to the tray could be thrown away and the icon loaded directly. That would require every app to change and probably would need a specification change to require it.

I used my laptop (a much slower machine) for testing as my desktop almost always gives perfect tray icons with any version of MATE.  I got cut icons about one session start in three, but never on a clean restart of just mate-panel. That tells me that when the session is starting, there is a lot of activity and more opportunities for GtkStatusIcon to get somehow interrrupted in drawing that iconwindow to pass to the tray,

Today I will see what happens if I try a forced wider allocation, but what I expect to get is just more space to the right of any icon that gets cut. If I get that, it would be an indicator that GTK itself may be to blame. I have noticed that I can more easily duplicate this with GTK 3.23, speaking of that.

**Comment by lukefromdc** [comment] 2018-07-03 17:54
Laptop tests found this:
1: it was mate-power-manager's icon (not battstat) causing the most issues
2: if m-p-m's battery icon was cut, turning m-p-m's icon off and back on caused it to render clean, resizing the panel did not

3: if the volume control icon was cut, resiziing the panel made it render clean, changing the volume setting did not.

Thus, refreshing the icon(message sent and new icon window?) does not change the rendering, but removing it and adding it back (docking it again) renders a cut icon cleanly. Some but not all also respond to changing panel height.

I will now try using the hide/show option in force-redraw unconditionally

**Comment by lukefromdc** [comment] 2018-07-03 18:24
On the laptop, I got these results in playing with the force-redraw code:

1: force-redraw as it stands, with the expose causes the corrupted icons one session start in three with GTK 3.23 and that laptop

2: converting force-redraw to use either gtk_widget_hide followed by gtk_widget_show or gtk_widget_queue_draw(lighter) stops the corrupted or wrong icons entirely, but m-p-m's icon now entirely missing one session start in three on the same machine

3: entirely disabling force-redraw was interesting: No corrupted icons and m-p-m's icon always showed up, but the 7th start cut the m-p-m and mate-volume-control icons.

Since restarting the whole panel always brings all the tray icons up clean, this means at some point the correct icon windows are being sent. Thus, it may just be a matter of finding out what works for force-redraw to get the icons to always show up and always render correct and complete.

**Comment by raveit65** [comment] 2023-07-21 15:46
It seems fixed with mentioned PR.

**Closed by raveit65** 2023-07-21 15:46 UTC
