### ISSUE TITLE
Unable to add Custom Application Launcher to panel for Locations

### ISSUE THREAD

**Issue by rhdi** [mate-desktop/mate-panel#605] opened 2017-07-05 23:04 UTC
#### Expected behaviour
Attempting to add launcher locations to MATE panel

#### Actual behaviour
Nothing happens. No launcher is added. 

#### MATE general version
MATE 1.18.0

#### Linux Distribution
Linux Mint 18.2 Sonya 64-bit

**Comment by epgfm** [comment] 2017-07-05 23:08
Can't reproduce on Ubuntu MATE 17.04 with mate-panel v 1.18.1: adding launchers by drag & drop from menu works as expected.

**Comment by epgfm** [comment] 2017-07-05 23:12
Unable to reproduce with Ubuntu MATE 17.04 using mate-panel 1.18.1.
Drag & Drop from place menu does nothing, but adding a launcher to the "caja" item from the application menu works, only the command and icon has to be subsequently modifier which is easy.

**Comment by rhdi** [comment] 2017-07-06 16:54
When attempting to change the properties after adding the Application Launcher Caja to the panel, the panel application restarts and the newly added launcher (Caja) is automatically removed. Thanks for the idea of this workaround, however it does not work for Linux Mint 18.2 Sonya 64-bit, MATE 1.18.0.

**Comment by monsta** [comment] 2017-07-09 19:07
Do you try to add a shortcut to some file/folder to the panel?

**Comment by monsta** [comment] 2017-10-01 18:08
Ok, I'll consider it a duplicate of https://github.com/mate-desktop/mate-panel/issues/590

**Closed by monsta** 2017-10-01 18:08 UTC
