### ISSUE TITLE
DConf issue when i remove the places menu from the panel

### ISSUE THREAD

**Issue by mratmartinez** [mate-desktop/mate-panel#294] opened 2015-03-30 23:18 UTC
I have disabled the Places Menu in the Panel, i disabled it from dconf-editor
The problem is: Everytime that i disable it, it appears again when i reboot.
The only solution that i have actually is this:
sleep 10
gsettings set org.mate.panel.menubar show-places false

It's a script that is runned at the startup. The problem is, that i have to use the "sleep" option 'cause it starts before Mate and i have to wait until it booted completely, that's why i use the "sleep 10".
So i want:
a) A way to set the Places disabled permanently.
b) If it isn't possible (or no one knows), a way to run the "gsettings set org.mate.panel.menubar show-places false" command AFTER Mate started. It doesn't work from the Startup Applications in the Settings
Sorry for the bad english, spanish speaker here

I'm using Arch.
I mean that i have to configure it everytime it boots 'cause the Places menu reappear in the Panel.

**Comment by monsta** [comment] 2015-04-10 12:06
Looks like duplicate of https://github.com/mate-desktop/mate-panel/issues/245 - fixed in 1.9

**Comment by mratmartinez** [comment] 2015-04-10 14:12
K, i have the 1.8.2

**Comment by NiceandGently** [comment] 2015-05-20 15:53
@flexiondotorg 
solved in master, can be closed

**Comment by monsta** [comment] 2015-05-21 08:55
Fixed in 1.8 as well by https://github.com/mate-desktop/mate-panel/commit/9319d4d527e970acc347f1a02d66a6d6ea576372.

**Closed by monsta** 2015-05-21 08:55 UTC

**Comment by asdf23** [comment] 2016-10-14 16:19
Is there anyway to hide items within Places & especially System?
