### ISSUE TITLE
notification-area-applet - near 100% cpu usage

### ISSUE THREAD

**Issue by KamalW** [mate-desktop/mate-panel#907] opened 2019-01-11 19:37 UTC
#### Steps to reproduce the behaviour
Try below script (May want to try with different numbers of yad notifications):
```
#!/bin/bash

for i in `seq 1 30`; do
  yad --notification --text "xx" &
done
```
#### MATE general version
1.20.1-2ubuntu1

#### Package version
1.20.1-3ubuntu1

#### Linux Distribution
Ubuntu 18.04 (64 bit)

**Comment by lukefromdc** [comment] 2019-01-12 01:39
What is yad? That is not a valid command on my system, and I've never seen the tray chew up CPU percentage on Debian Unstable with locally built MATE, any GTK3 version and the display applet, volume control, nm-applet, and audacious in the tray

**Comment by KamalW** [comment] 2019-01-12 04:08
```
$ dpkg-query --show --showformat '${Description}\n' yad
tool for creating graphical dialogs from shell scripts
 Yad allows you to display GTK+ dialog boxes from command line or shell
 scripts. It is similar to Zenity but with more dialog types and options.

$ dpkg-query --show --showformat '${Depends}\n' yad
libc6 (>= 2.7), libcairo2 (>= 1.2.4), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.30.0), libgtk-3-0 (>= 3.0.0), libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0)
```
Both yad and notification-area-applet work well if only a limited number of tray icons are shown. But the notification-area-applet issue gets triggered when the number of yad tray icons increases beyond a certain limit - may be when there is no space left to display the tray icons. While not sure, it might happen not only when yad is used, but with other tray icon placing applications.

Placing too many tray icons itself is not convenient. But that shouldn't cause notification-area-applet to misbehave.

Such a problem wasn't encounted while using Ubuntu Mate 16.04 from which I have moved to 18.04.

**Comment by raveit65** [comment] 2019-01-12 08:58
Are you sure it is the notfication-applet process?
And not the indicator applet from ubuntu?
Sadly, you 're ignore the template and didn't filed out a ubuntu bugreport, otherwise you would know that 18.04 switched to using indicator-applet.
I am using fedora and i don't see a high load with using you script.
```
[rave@mother Schreibtisch]$ ps aux | grep notification*
rave      2192  0.0  0.2 711408 34976 ?        Sl   09:36   0:00 /usr/libexec/mate-panel/notification-area-applet
rave     12002  0.0  0.1 535848 29432 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12003  0.0  0.1 535752 29004 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12004  0.0  0.1 535832 29424 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12005  0.0  0.1 535848 28964 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12006  0.0  0.1 535712 29484 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12007  0.0  0.1 535752 29396 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12008  0.0  0.1 535832 29288 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12009  0.0  0.1 535760 29464 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12010  0.0  0.1 535756 29084 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12011  0.0  0.1 535848 29524 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12012  0.0  0.1 535720 29512 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12013  0.0  0.1 535756 28976 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12014  0.0  0.1 535832 29468 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12015  0.0  0.1 535828 29508 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12016  0.0  0.1 535752 29484 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12017  0.0  0.1 535844 29516 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12018  0.0  0.1 535840 29564 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12019  0.0  0.1 535748 29296 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12020  0.0  0.1 535840 29460 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12021  0.0  0.1 535828 29484 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12022  0.0  0.1 535860 29040 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12023  0.0  0.1 535844 29548 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12024  0.0  0.1 535856 29564 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12025  0.0  0.1 535824 29376 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12026  0.0  0.1 535752 29328 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12027  0.0  0.1 535852 28920 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12028  0.0  0.1 535748 29424 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12029  0.0  0.1 535824 28920 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12030  0.0  0.1 535852 29296 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12031  0.0  0.1 535848 29556 pts/0    Sl   09:45   0:00 yad --notification --text xx
rave     12214  0.0  0.0 213788  1020 pts/0    S+   09:53   0:00 grep --color=auto notification*
```

**Comment by KamalW** [comment] 2019-01-12 10:00
```
kamal@chrome:~$ uname -a
Linux chrome 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

kamal@chrome:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

kamal@chrome:~$ ps aux | grep session
root      1691  0.0  0.1 250548  7256 ?        Sl   15:24   0:00 lightdm --session-child 13 20
kamal     1716  0.6  0.5 505012 23172 ?        Ssl  15:24   0:00 mate-session
kamal     1745  0.7  0.1  51020  5256 ?        Ss   15:24   0:00 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
kamal     1831  0.1  0.1 220772  6980 ?        Sl   15:24   0:00 /usr/lib/at-spi2-core/at-spi2-registryd --use-gnome-session
kamal     1837  0.0  0.0  11304   320 ?        Ss   15:24   0:00 /usr/bin/ssh-agent /usr/bin/im-launch mate-session
kamal     1927  0.0  0.1 974848  7292 ?        Sl   15:24   0:00 /usr/lib/x86_64-linux-gnu/indicator-session/indicator-session-service
kamal     2324  0.0  0.0  21540  1108 pts/0    S+   15:25   0:00 grep --color=auto session

kamal@chrome:~$ ps aux | grep panel
kamal     1872  2.1  0.9 732416 37292 ?        Sl   15:24   0:01 mate-panel
kamal     1888  0.6  0.7 569500 31392 ?        Sl   15:24   0:00 /usr/lib/mate-panel/wnck-applet
kamal     2012  0.6  0.8 655276 33208 ?        Sl   15:24   0:00 /usr/lib/mate-panel/clock-applet
kamal     2018 42.7  0.5 498316 23020 ?        Rl   15:24   0:27 /usr/lib/mate-panel/notification-area-applet
kamal     2326  0.0  0.0  21540  1020 pts/0    S+   15:25   0:00 grep --color=auto panel

kamal@chrome:~$ ps aux | grep notification*
kamal     2018 54.9  0.5 498316 23020 ?        Rl   15:24   0:46 /usr/lib/mate-panel/notification-area-applet
kamal     2173  0.3  0.6 500696 26352 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2174  0.3  0.6 500692 26356 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2175  0.3  0.6 500664 25964 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2176  0.3  0.6 500708 26132 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2177  0.3  0.6 500704 26436 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2178  0.3  0.6 500712 26444 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2179  0.3  0.6 500712 26180 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2180  0.3  0.6 500708 26156 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2181  0.3  0.6 500672 26112 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2182  0.3  0.6 500704 25964 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2183  0.3  0.6 500704 26400 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2184  0.3  0.6 500708 26068 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2185  0.3  0.6 500708 26060 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2186  0.3  0.6 500700 26096 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2187  0.3  0.6 500708 25976 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2188  0.3  0.6 500696 26076 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2189  0.3  0.6 500700 26336 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2190  0.3  0.6 500700 26120 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2191  0.3  0.6 500684 26536 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2192  0.3  0.6 500676 26060 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2193  0.3  0.6 500696 26516 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2194  0.3  0.6 500704 26140 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2195  0.3  0.6 500680 26152 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2196  0.3  0.6 500700 26036 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2197  0.3  0.6 500696 26312 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2198  0.3  0.6 500712 26348 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2199  0.3  0.6 500704 26336 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2200  0.3  0.6 500688 26324 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2201  0.3  0.6 500704 26416 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2202  0.3  0.6 500704 26520 pts/1    Sl   15:25   0:00 yad --notification --text xx
kamal     2328  0.0  0.0  21540  1108 pts/0    S+   15:25   0:00 grep --color=auto notification*

kamal@chrome:~$ top -p 2018

top - 15:26:25 up 2 min,  1 user,  load average: 1.82, 1.03, 0.41
Tasks:   1 total,   1 running,   0 sleeping,   0 stopped,   0 zombie
%Cpu(s): 51.6 us,  0.5 sy,  0.0 ni, 47.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3974964 total,  2700764 free,   723612 used,   550588 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  2974628 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                          
 2018 kamal     20   0  498316  23020  18300 R 100.0  0.6   1:17.19 notification-ar                                                                  
```

**Comment by raveit65** [comment] 2019-01-12 12:57
Ok, i tested it again with f28 and mate-1.20.x
```
[rave@f28-orig Downloads]$ ./yad-script 
[rave@f28-orig Downloads]$ ps aux | grep notification-area*
rave      1562 15.7  0.6 694536 25620 ?        Rl   13:46   0:36 /usr/libexec/mate-panel/notification-area-applet
rave      2527  0.0  0.0 213920  1016 pts/0    S+   13:50   0:00 grep --color=auto notification-area*
[rave@f28-orig Downloads]$ top -p 1562

top - 13:50:51 up 4 min,  1 user,  load average: 0,83, 0,35, 0,13
Tasks:   1 total,   1 running,   0 sleeping,   0 stopped,   0 zombie
%Cpu(s): 12,6 us,  0,0 sy,  0,0 ni, 87,4 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem :  4035944 total,  2228636 free,   986368 used,   820940 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  2773224 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
 1562 rave      20   0  694536  25620  18400 R 100,0  0,6   1:20.95 notificati+
```
So, this means that the issue is fixed somewhere in master branch.

**Comment by raveit65** [comment] 2019-01-12 13:33
@KamalW 
It won't hurt to file out an downstream report to inform ubuntu about this problem and that we're looking for the fix in master branch.
Without that ubuntu maintainer won't know that the problem exists and 18.04 will never get the fix.

**Comment by KamalW** [comment] 2019-01-12 15:19
Reported to Ubuntu.
https://bugs.launchpad.net/ubuntu/+source/mate-panel/+bug/1811523

**Comment by raveit65** [comment] 2019-01-12 19:19
What surprise, i just downgrade my local fedora mate-panel-1.21.x rpm builds and i found the PR which fixes the issue.
https://github.com/mate-desktop/mate-panel/pull/856
mate-panel-1.21.2 release does have the issue but this PR fix it.
Well, this is a new feature so this doesn't belongs in old stable branch, ihmo.
But maybe we can find out which commit (1/5) from this PR helps.

**Comment by raveit65** [comment] 2019-01-12 20:45
The first 3 commits of https://github.com/mate-desktop/mate-panel/pull/856 fixes the issue.
In other words the port from GtkTable to GtkGrid.

> Such a problem wasn't encounted while using Ubuntu Mate 16.04 from which I have moved to 18.04.

Looks like the issue is one of last remnants of porting MATE from gtk+-2 to gtk+-3,
IHMO, MATE in 16.04 was build with gtk+-2......, correct me if i am wrong.
If other team members agree we can assume a deprecation fix as a bug fix? :wink: 
I will try to back port those 3 commits to 1.20 branch.

**Comment by lukefromdc** [comment] 2019-01-13 01:31
After applying those commits it will also be necessary to apply
https://github.com/mate-desktop/mate-panel/pull/902
"Tray: Fix too-wide icon spacing after mate-polkit has been used and icon dismissed (privileges dropped) with sni "
as otherwise dismissing the mate-polkit icon will leave the rest of the tray icons double-spaced until either mate-polkit or the entire session is restarted.

**Comment by raveit65** [comment] 2019-01-14 12:05
You may like to test the PR?
https://github.com/mate-desktop/mate-panel/pull/909

**Comment by raveit65** [comment] 2023-07-21 16:47
Fix is merged.

**Closed by raveit65** 2023-07-21 16:47 UTC
Labels: confirmed
