### ISSUE TITLE
mate panel has accessibility issues with some of it's applets, as well as freezing periodically

### ISSUE THREAD

**Issue by coffeeking** [mate-desktop/mate-panel#441] opened 2016-05-31 05:32 UTC
steps to reproduce: start orca in mate. If needed, install it first. Make sure the following applets are on your panel. clock, power manager, universal access. Switch to the panel using control+alt+tab. Tab around the panel. You'll notice that the clock applet simply says "click to select month calendar". The universal access applet simply says "1 of 1" and so does the power manager applet if there is no battery present. The panel is also very verbose when tabbing along it, usually saying "bottom expanded edge panel. Bottom expanded edge panel panel" with every tab. The last issue is a habbit of freezing. The panel itself doesn't seem to have frozen, since the applets visually update themselves, but it's the best termI can come up with for it. Once this happens, orca can no longer see any of the applets on it until you restart it with "mate-panel --replace." This is an old issue. It existed in gnome 2.x before mate was forked, and has persisted in mate. It exists in the latest release, mate 1.14. I'll be happy to help you guys solve it any way I can.

**Comment by coffeeking** [comment] 2016-06-03 07:44
hi
I'd like to add the following applets to this bug. The sound volume applet is accessible to orca, but only if you press control+f1, which is a very well hidden trick that isn't documented anywhere. Would it be possible to change the applet to show the current volume and output device when the applet is hovered over? Also allow the ability to change output, and input devices from the applet? I'd be happy to file a feature request if you like. The system load indicator applet is also inaccessible. This one simply says "1 of 1" when orca hovers over it, and orca can't read any of the items in it's menus, which presumably details things like cpu load, memory usage, etc.
Thanks
Kendell Clark

**Comment by Joanmarie** [comment] 2016-06-03 13:03
Some (extremely quick) observations made without a MATE environment (sorry!):

> You'll notice that the clock applet simply says "click to select month calendar".

Orca gets what it says by first checking the AtkObject name (because interactive widgets should have accessible names). Then it falls back on the AtkObject description (because we cannot count on developers actually providing accessible names, but they often provide tooltips, the content of which Gtk+ exposes via the AtkObject description).

Whatever is displayed visually on the clock applet should be exposed via the AtkObject name. If you do that, Orca should speak what users see.

The clock applet should also be keyboard accessible (I'm not saying it's not; merely mentioning it).

> The universal access applet simply says "1 of 1" and so does the power manager applet if there is no battery present.

Missing AtkObject name again.

> The panel is also very verbose when tabbing along it, usually saying "bottom expanded edge panel. Bottom expanded edge panel panel" with every tab.

I'll come back to this in a subsequent comment.

> The last issue is a habbit of freezing. The panel itself doesn't seem to have frozen, since the applets visually update themselves, but it's the best termI can come up with for it. Once this happens, orca can no longer see any of the applets on it until you restart it with "mate-panel --replace." This is an old issue. It existed in gnome 2.x before mate was forked, and has persisted in mate. It exists in the latest release, mate 1.14. I'll be happy to help you guys solve it any way I can.

As I believe I've mentioned to you before, there are two possibilities:

1. Keyboard focus is getting stuck. In other words, it's not that Orca can not see the applets. It's that you are not moving amongst the applets. If this is the case, it would impact all users. Verifying that this is the case should be easy enough for the MATE developers to do: Use Tab and/or the arrow keys as appropriate to navigate within the panel. If you reach a point where keyboard navigation gets stuck, there's your bug.

2. Keyboard focus is not getting stuck, but all accessibility events have suddenly stopped being emitted, whereas they were being emitted before.

My bet is on item 1.

**Comment by Joanmarie** [comment] 2016-06-03 13:42
Regarding this the verbosity when tabbing. Another user had asked me about this and provided me a debug.out. What I responded to him:

> It seems multiple applications are claiming to be the active one.
> 
> 1. You start out in an app named "mate-panel."
> 
> 2. You press Tab and a nameless panel claim focus. This nameless panel is from an app named "mate-menu.py."
> 
> 3. You press Tab again and a bunch of stuff happens:
> 
>    a. A menu bar in an application named "mate-indicator-applet-complete" claims focus.
> 
>    b. A nameless panel from "mate-menu.py" claims focus.
> 
>    c. The menu bar in "mate-indicator-applet-complete" claims focus again.
> 
> 4. You press Tab again and a button named "Thunderbird Mail Send and receive mail with Thunderbird" claims focus. This button is from "mate-panel"
> 
> And now we're at your first question: Why did Orca repeat the frame name? Because you switched applications. It's like when you switch windows, Orca presents the context/ancestry so you know where you are.
> 
> Now, to you, it probably doesn't seem like you switched applications. You're tabbing around in MATE panel's bottom panel. However, what Orca is being told is that you left MATE panel, went into mate-menu.py, went into mate-indicator-applet-complete, returned to mate-menu.py, left that for mate-indicator-applet-complete, and finally switched back to MATE panel.

I have taking a closer look at this on my to-do list. But my to-do list is admittedly huge. And if I'm being completely honest, I won't be getting to this any time soon. Sorry. But what I think needs to be done is to make the applets be children of the MATE panel accessible application. You can verify if they already are or not by examining your environment using Accerciser (the pane of accessible objects on the left).

On a related note, it seems that MATE panel has an object with ATK_ROLE_FRAME whose accessible name is "Bottom Expanded Edge Panel". There is a descendant ATK_ROLE_PANEL object, whose name is also "Bottom Expanded Edge Panel". As a general rule:

1. Don't duplicate role names in the accessible name.<br><br> Orca often presents the role name to make it clear what type of object something is. So the panel named "Bottom Expanded Edge Panel" would be spoken as "Bottom Expanded Edge Panel panel."

2. Don't duplicate accessible names within the accessibility tree of objects unless you have a good reason to.<br><br>An example of a good reason would be the frame displaying the text, and also a descendant container displaying the text (e.g. via a GtkLabel). Because we want Orca to present what the user is seeing, in that hypothetical instance repeating the displayed names would be appropriate. (Possible poor UI for everyone, but appropriate.)<br><br>My guess is that in this case, nothing is displaying the text "Bottom Expanded Edge Panel". We still want Orca to tell the user when he/she has given focus to the panel at the bottom, and Orca will announce new frames, so keeping the name as-is on the top-level (ATK_ROLE_FRAME) object makes sense, even if it is not displayed. Removing it from the descendant (ATK_ROLE_PANEL) object would probably be a good idea. That way, Orca won't say things like "Bottom Expanded Edge Panel frame Bottom Expanded Edge Panel panel" when that panel initially gains focus.

**Comment by Joanmarie** [comment] 2016-06-03 14:51
I'm attaching a very simple pyatspi accessible-event listener. Launch it in a terminal (after deleting the "txt" extension I had to add to convince github it was a "supported" file).

What it will dump out is the key you pressed, the key you released, and any `object:state-changed:focused` and `object:state-changed:selected` events where `event.detail1` is `true` (i.e. the object just became selected or focused, rather than having given up focus).

For each output event, it will print the accessible name, the accessible role, and the accessible application name. Here's an example from my getting into the Firefox menu and arrowing:

```
PRESSED:     'Alt_L'

PRESSED:     'f'
FOCUSED:     'New Tab' menu item in 'Firefox'
RELEASED:    'f'
RELEASED:    'Alt_L'

PRESSED:     'Down'
FOCUSED:     'New Window' menu item in 'Firefox'
RELEASED:    'Down'

PRESSED:     'Down'
FOCUSED:     'New Private Window' menu item in 'Firefox'
RELEASED:    'Down'

PRESSED:     'Down'
FOCUSED:     'Open File…' menu item in 'Firefox'
RELEASED:    'Down'

PRESSED:     'Down'
FOCUSED:     'Close Tab' menu item in 'Firefox'
RELEASED:    'Down'

PRESSED:     'Tab'
FOCUSED:     'Nightly Start Page' document frame in 'Firefox'
RELEASED:    'Tab'
```

Now I'll grant you this listener is an extreme oversimplification. However, it should make it easier for you to identify where things are not working as expected in a way that Kendell will report. :)

- If there is nothing in between the PRESSED and RELEASED, and focus is really changing, then the bug is (likely*) an absence of accessible events.
- If the FOCUSED/SELECTED event starts with an empty string (''), then the bug is (likely*) an absence of accessible name.
- If there are a surprising number of events from multiple MATE applications resulting from a single key press (see my previous comment and quoted response to the other user), then please stop that. ;)

*I say "likely" because there are other appropriate events, and names can come from labels associated via AtkRelation. But for menus, panels, and the like, you should be able to identify many accessibility issues just from this listener.

Hope this helps, and thanks for making MATE more accessible!

[focus.py.txt](https://github.com/mate-desktop/mate-panel/files/297750/focus.py.txt)

**Comment by coffeeking** [comment] 2016-06-04 00:49
hi
This is very helpful. Since I've got nothing to do today, I'll try to
verify if the keyboard focus is getting stuck. I'm pretty sure this
won't be hard to do.
Thanks
Kendell Clark


Joanmarie wrote:

**Comment by coffeeking** [comment] 2016-06-04 00:52
hi
Joanmeri is right I believe. It does seem to be a keyboard focus issue.
I have no visual proof, since I cannot see well enough, but after
tabbing to the "universal access" applet, you often cannot tab past it.
You can sometimes arrow past it using the left and right arrow, but even
this doesn't always work. The bug also exists in the mate weather
applet. Once you tab to it, you usually can't tab past it. Sometimes you
can arrow past it but not always. I'm not sure if this bug is a mate
panel bug, something in the panel or a bug in certain applets.
Thanks
Kendell Clark


kendell clark wrote:

**Comment by coffeeking** [comment] 2016-06-04 00:59
hi
Youch. That's quite a list of things going on there lol. I'm glad you've
shed some light on this. Like I said in my email, this is important but
not critical, and now that you've told us what's going on someone else
can probably fix it. Now that I know what's going on I can stop
wondering if there's a way to "hack" around it in orca, because to do
that would mess up orca's behavior when switching apps, which isn't what
we want. I've mentioned this numerous times, sorry about that. I'm only
being this persistent because it's gotten to a point where the panel is
nearly unusable in it's current state, and I'm trying to make it better
than it was before this bug happened, because the keyboard focus issue
causes a lot of issues  if you depend on a screen reader to navigate the
panel.
Thanks
Kendell Clark


Joanmarie wrote:

**Comment by raveit65** [comment] 2016-06-06 19:12
Ok, i tried to reproduce the issue.
With a bit help i've orca runing on fedora 24 with Mate-1.14 and it speaks on most apps if i use the mouse or keyboard.
But i failed to select any applet or panel launcher with the keyboard.
And it doesn't mater if i build mate-panel-1.14.0 or
mate-panel-1.14.0 + the fix for https://github.com/mate-desktop/mate-panel/issues/440
or
mate-panel-1.14.0 + the fix for https://github.com/mate-desktop/mate-panel/issues/440 + the rest of the commits on top of 1.14 branch.
What i do:
1. selecting the top panel with crtl+alt+tab or tab+ shift. ---> orca told me i#m on top panel.
2. try to tab trough the panel --> failed, i hear only a   a   a   a   a   a...........
I have no idea what i do wrong, as other people say it is possible to select some applets.
Sorry, i never used orca.
And i have no idea if this is the issue or if i do some thing wrong.
But i can't confirm that the panel is freezed at this point.

.....very hard to debug something if you don't know how it should work normal.

**Comment by Joanmarie** [comment] 2016-06-06 19:23
> Sorry, i never used orca.

No need to apologize. I'm not a MATE user. I do use Fedora 24, however. And it sounds like getting stuck on the top panel is a long-standing issue (i.e. and not requiring I build MATE components). So let me install MATE and repro the problem.

**Comment by raveit65** [comment] 2016-06-06 19:51
@Joanmarie 
here is the mate-panel rpm with the fix for https://github.com/mate-desktop/mate-panel/issues/440
Don't enable the other patch because this one should cause a regression again (not confirmed by me) as i need first to learn use orca.
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/mate-panel.tar.xz

**Comment by Joanmarie** [comment] 2016-06-06 20:09
@raveit65 Hopefully that's the answer to the question I was about to ask (my panel is completely non-navigable via the keyboard). Lemme give this a shot. Thanks!

**Comment by Joanmarie** [comment] 2016-06-06 20:24
Installed. My top panel still doesn't seem to be keyboard navigable. At least back in the GNOME 2 days, you used to be able to use Ctrl+Alt+Tab to move focus between the panels and desktop (this still seems to be the case). HOWEVER, once you've moved focus to the top panel, you could then press Tab (and if memory serves me, Left and Right) to move within the top panel. That is totally failing for me in Fedora 24. (And still is, using your packages).

As for Orca: What Orca should be doing is presenting the focus changes as the user navigates. So IF the top panel is keyboard navigable THEN if Orca fails to present focus changes, I can help you. IF the top panel is not keyboard navigable THEN Orca is irrelevant to the problem.

Should my top panel be keyboard navigable given the packages I have now?

**Comment by raveit65** [comment] 2016-06-06 21:08
PS: I'm fedora mate maintainer ;)

**Comment by raveit65** [comment] 2016-06-06 21:19
I forgot to say , with latets mate-panel build for f23 i use the the commits from master branch which should cause a regression again as @coffeeking said here.
https://github.com/mate-desktop/mate-panel/issues/440#issuecomment-223559237
http://pkgs.fedoraproject.org/cgit/rpms/mate-panel.git/tree/mate-panel.spec?h=f23#n38
So this can't be the real problem for the second regression.

**Comment by coffeeking** [comment] 2016-06-06 21:31
hi
It's really iffy after mate panel is upgraded from 1.12 to 1.14.
Sometimes it works, usually it doesn't, or only does for a couple of
applets and then stops working. This is why I filed both issues, to
figure out what the problem is and get it fixed. This can't continue,
because one of our editions for sonar is a mate edition, and a mate
desktop with an inaccessible panel ... I'm not complaining, at least not
intentionally. I'll start on that git revert you guys asked me to do to
see if I can find out which of the two commits fix the problem, if
either of them do.
Thanks
Kendell Clark


Joanmarie wrote:

**Comment by coffeeking** [comment] 2016-06-06 21:42
hi
I've reverted all the commits up to the commit labeled na-try-child: add
missing include for GTK_Version_Check"
 I'm sorry, but none of the commits fix the problem. I'm not sure what
to do next.
Thanks
Kendell Clark



kendell clark wrote:

**Comment by raveit65** [comment] 2016-06-06 21:54
> I've reverted all the commits up to the commit labeled na-try-child: add missing include for GTK_Version_Check" I'm sorry, but none of the commits fix the problem. I'm not sure what to do next.

No prob, this confirms only my results with f23, here i use this commits and orca works on mate-panel.
I'm thinking more and more that we have a general problem on bleeding edge distros like fedora or clones which use a rolling release distro ArchLinux as base, or debian testing.

**Comment by Joanmarie** [comment] 2016-06-06 22:19
Since I'm already sufficiently distracted from what I should be working on.... I built mate-panel from git in Fedora 24. I have gnome-shell running. When I launch mate-panel via terminal, gnome-shell continues running, but I get an additional top panel. :) I can navigate to it via gnome-shell using Ctrl+Alt+Tab. The contents of my top-panel include: The menu bar, notification area (which is non-functional in gnome-shell), the buttons to shutdown and show the desktop, and the drawer.

With this setup: mate-panel master suffers from the problem at hand. BUT MATE 1.12.2 (at commit 2e0a38734b6) works as expected. More specifically, when you give keyboard focus to the top panel and use Tab to navigate, you'll notice that the visual appearance of the newly-focused items changes. If you press Space on a focused item on the top panel, it gets activated. No Orca needed and works in Fedora 24.

**Comment by Joanmarie** [comment] 2016-06-06 22:46
This seems to be where focus broke: 9bf088cdca9

At least for the Gkt+2 version.

**Comment by raveit65** [comment] 2016-06-07 07:11
@lukefromdc 
Was this a typo?
https://github.com/mate-desktop/mate-panel/commit/9bf088cdca91e1feed8276fc55d2d47a460b983b#diff-61790045ddf6fdb86bd773bd32a4bb67L443
Here you removed
widget_class->focus = panel_widget_real_focus;
for both toolkit versions.

@Joanmarie 
thanks a lot.....nice that you have a second panel in gnome :)

**Comment by raveit65** [comment] 2016-06-07 08:19
I just tested the fix and it works well for both toolkit versions and applets don't crash in gtk3 version if you change gtk theme if a custom background is selected, which was the intention for https://github.com/mate-desktop/mate-panel/commit/9bf088cdca91e1feed8276fc55d2d47a460b983b

**Comment by monsta** [comment] 2016-06-07 10:45
@lukefromdc: indeed - gnome-panel still has that line...

**Comment by raveit65** [comment] 2016-06-08 08:40
merged
https://github.com/mate-desktop/mate-panel/commit/e14d3305b6ea36bb68db6c410494824e3c64ab5d

**Closed by raveit65** 2016-06-08 08:40 UTC

**Comment by raveit65** [comment] 2016-06-08 10:42
@coffeeking 
I've released mate-panel-1.14.1
http://pub.mate-desktop.org/releases/1.14/?C=M;O=A
In my tests orca speaks now on nearly all applets with mate-panel gtk2 and gtk3 version on fedora 24.
As this report is very huge and confused, i suggest to open a new one with a simple list of applets which don't work with orca.
@Joanmarie 
For your info.
I noticed that speech-dispatcher-espeak-0.8.4-1.fc24.x86_64 crashes very often with session start and trigered a abrt alarm.

**Comment by coffeeking** [comment] 2016-06-08 13:10
hi
Completely agreed. I'll file a new bug if there are still any issues.
I'll also tell the manjaro people so they can release a package with the
update. I really really appreciate your and everyone else's effort,
especially that you've tested to make sure orca works on both gtk2 and
3. No one else has done that to date and that makes a huge difference.
Thanks
Kendell Clark


raveit65 wrote:

**Comment by coffeeking** [comment] 2016-06-09 05:04
hi
I'm immensely pleased to report that the mate panel 1.14.1 update fixes
all of the issues I reported. The only ones left are the inaccessibility
of the  universal access, system load and clock applet, and the
occasional freezing. To test this with orca, simply focus on the panel
and tab around very quickly. You'll eventually be unable to tab among
the applets until you restart the panel with mate-panel --replace from a
terminal or the run dialog. I don't have enough vision to tell whether
you can still visually move among the applets and orca just isn't seeing
it or if the panel really has frozen. To test the inaccessible aplets,
simply add them to one of your panels by pressing control+f10 to click
on a blank area of the panel, select add to panel, and select either
clock, or system load indicator. Universal access seems to show up if
accessibility is enabled in mate, which you do by going to
system>preferences>personalization>assistive technology and checking the
"enable assistive technologies" checkbox.  Until you do that, parts of
mate will not read. I'm trying to be as clear as possible since you guys
have requested these bugs. I'm really glad you guys care about
accessibility. Few desktop developers really do. Gnome is the other
desktop that does, but then again they have people paid to work on
accessibility, you guys don't If you guys accept donations, I'll drop
some money your way. It won't be much as I never have much, but you guys
deserve financial compensation and not just praise from one distro
developer for all your fantastic work. I use your desktop every day.
Thanks
Kendell Clark


kendell clark wrote:

**Comment by raveit65** [comment] 2016-06-09 19:20
@Joanmarie 
Can you please test and leave karma?
https://bodhi.fedoraproject.org/updates/mate-panel-1.14.1-1.fc24
I want to as for freeze exception by releng.

**Comment by Joanmarie** [comment] 2016-06-09 21:57
@raveit65 Done. I don't use Bodhi and thought it would turn my email address into a displayable username. Oops. Happily I included who I was in the comment. ;) Please let me know if I need to do anything else. Thanks again for pushing this forward!

**Comment by raveit65** [comment] 2016-06-09 22:12
@Joanmarie 
thanks for the comment, but without a fas account your karma isn't counted.
I thought you had one.
