### ISSUE TITLE
Unable to Maximize previously minimized window after clicking an applet

### ISSUE THREAD

**Issue by pyaazkaparatha** [mate-desktop/mate-panel#367] opened 2015-11-10 18:08 UTC
Steps:
1-I use applet netspeed. Add it to panel. 

2-Open any program(say deluge) and minimize it. 

3-Just do one click on netspeed applet. 

4-Try to maximize deluge by clicking on panel. It doesn't work.

Solution: Either try to open the program from menu which maximizes it or use emerald. Also bug is not encountered when two windows on different desktops are there and window on other desktop is being maximized.

EDIT: mate-panel-1.12.0-11.fc23.x86_64 GTK3 on Fedora23
##

**Comment by raveit65** [comment] 2015-11-10 18:37
Confirmed, but it happens also with gtk2 version.
I know reporter use fedora with mate-1.12 gtk3.

**Comment by raveit65** [comment] 2015-11-10 18:41
Looks like it is an old regression, i can trigger the issue with fedora 22 and Mate-1.10 too.
Another workaround is to switch to another workspace and back

**Comment by raveit65** [comment] 2015-11-10 20:53
Urg, this happens with an old m-n 1.8.0 version installed.
So, this seems to be an very old bug or it's is an issue with mate-panel itself.

**Comment by raveit65** [comment] 2015-11-10 21:15
same with 1.6.2 :)

**Comment by raveit65** [comment] 2017-05-28 07:12
I can't really reproduce this any more with mate-1.18 or 1.16 (gtk3), so closing this.

**Closed by raveit65** 2017-05-28 07:12 UTC
Labels: confirmed
