### ISSUE TITLE
Notification area icons disproportionally big in certain panel sizes

### ISSUE THREAD

**Issue by o-alquimista** [mate-desktop/mate-panel#736] opened 2018-02-12 10:56 UTC
#### Expected behaviour
The icons should have a size relative to the panel height, like 70% or something. If possible, make them always smaller than the main menus and window switchers when the panel exceeds a certain size.

#### Actual behaviour
The icons are HUGE when you increase the panel height. It looks totally awkward.

![captura de tela em 2018-02-12 08-47-50](https://user-images.githubusercontent.com/25424263/36093714-a1dd4362-0fd2-11e8-88e9-718ac01540ae.png)

#### Steps to reproduce the behaviour

- Start with the panel set to 24px (default)

- Increase size to 32px

#### MATE general version
1.20.0

#### Package version
1.20.0-1

#### Linux Distribution
Arch Linux (x86_64)

**Comment by info-cppsp** [comment] 2018-02-12 11:08
@monsta 
duplicate of #519 
Please close.

**Closed** 2018-02-12 12:40 UTC
