### ISSUE TITLE
Artifacts after toggling full screen in Chrome or Electron apps

### ISSUE THREAD

**Issue by tommyvct** [mate-desktop/mate-panel#1006] opened 2019-08-06 13:16 UTC
#### Expected behaviour
![image](https://user-images.githubusercontent.com/7903172/62542418-51473a00-b88e-11e9-97e7-fbda55e4b26b.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/7903172/62542444-5c9a6580-b88e-11e9-91ac-9e11fe9fd5c1.png)

#### Steps to reproduce the behaviour
1. Open Skype or Chrome
2. Press F11
3. Press F11 again
4. Scrambled panel get!

#### MATE general version
1.20.4b

#### Package version
1.20.5-1

#### Linux Distribution
Ubuntu MATE 1904

I don't know exactly whether it's a `radeon` driver problem, or it is a chromium problem.
Using `pkill mate-panel` to restart the panel can solve the problem.

**Comment by raveit65** [comment] 2019-08-06 13:28
I don't think that this is a mate-panel problem.
Does whole the desktop have glitches or only mate-panel?
This sounds for me like a graphic driver problem and radeon driver is pretty old.
Can you use newer amdgpu driver?
Sorry, i can't reproduce it because i am using nvidia cards and chrome doesn't have the issue with proprietary nvidia driver here.

**Comment by sc0w** [comment] 2019-08-06 20:06
I can't reproduce the issue with:

```
mate-panel 1.20.5
chromium 73.0.3683.75
(nouveau driver)
```

**Comment by lukefromdc** [comment] 2019-08-06 20:15
I've seen similar glitches from time to time with almost any application capable of an F11 fullscreen window excluding video players. I normally run compiz and have seen it with both Radeon and AMDGPU drivers. Thought it was a compiz bug but maybe not, assuming this is occurring with marco as well. As for Skype and Chrome, I don't have them installed and cannot test them.

**Comment by sc0w** [comment] 2019-08-06 20:26
I have `Marco (Compton GPU compositor) 1.20.3`

maybe it is related to the size of panel? the size here in mate-panel properties is 24 pixels

**Comment by lukefromdc** [comment] 2019-08-06 20:29
Compton uses the GPU as does compiz, so GPU drivers are a possible issue here. I don't think the panel is involved at all, rather it's just part of what a fullscreen app covers and is leavintg glitches behind over. I've seen them all over the desktop from other applications.

**Comment by tommyvct** [comment] 2019-08-07 03:38
My second thought is it is a 'radeon' problem.
'radeon' is my only choice because I'm using a ThinkPad X120e with Radeon 6310 HD and a super crappy dual core low power CPU.

But the strange thing is I didn't see this kind of artifacts when using gnome 3 or KDE, though these are totally different things by design.

Only the panel have glitches, others parts are not affected.

**Comment by lukefromdc** [comment] 2019-08-07 05:26
The artifacts I got were on unmaximizing a fullscreen window, appeared to be a partial redraw failure, and could appear anywhere on the screen. Similar but not exactly the same, hardware also different here.

Years ago I had an issue with an Intel video driver causing panel issues on old Intel Atom netbooks, eventually fixed by a video driver update. This was with no GPU compositing at all, just GTK and mate-panel both talking to the GDK backend and that in turn rendering with cairo. That no doubt interacts differently with the video driver that gnome-shell or kde.

**Comment by tommyvct** [comment] 2019-11-11 07:40
Believe it or not, I tried Ubuntu MATE 1910, the problem is totally gone.

**Comment by raveit65** [comment] 2019-11-11 08:22
Thanks, for information.

**Closed by raveit65** 2019-11-11 08:22 UTC
