### ISSUE TITLE
menubutton on bottom autohiding panel: menu unfolds over button/panel

### ISSUE THREAD

**Issue by n8w8** [mate-desktop/mate-panel#592] opened 2017-06-17 14:58 UTC
#### Expected behaviour
When I click on the menubutton, the bottom edge of the menu is at the top of the panel, keeping the panel/button visible (and the mouse cursor on the button)
![afbeelding](https://user-images.githubusercontent.com/29505028/27253983-14e9d110-537f-11e7-956c-df016a2d3a21.png)

#### Actual behaviour
When I click on the menubutton, the bottom edge of the menu is at the bottom of the screen, covering the panel/button.
![afbeelding](https://user-images.githubusercontent.com/29505028/27253985-1d97353c-537f-11e7-9000-f14f3028a568.png)
This might sound minor but is very annoying:
1. When I click to open the menu, the mouse cursor is on the Shutdown item. So, if I hold the mouse button slightly too long, or accidentally click 2 times, Shutdown gets chosen.
2. When I want to close the menu, I have to move the cursor away from the menu, instead of clicking again in the same spot I opened the menu. Which I need to do if I misfire when wanting to click the button next to the menu button (or perhaps other reasons).

(It works fine on top of screen, or non-autohide, and the other foldout buttons/applets I tested also work fine).

#### Steps to reproduce the behaviour
Put panel on bottom of screen, enable autohide of this panel, add menu button, click menu button.

#### MATE general version
1.16 (all packages from official Debian Stretch main)
gtk3
marco --no-composite

#### Package version
mate-panel 1.16.2-1

#### Linux Distribution
Debian Stretch

**Comment by lukefromdc** [comment] 2017-06-17 17:38
I was able to duplicate this with compiz as the window manager and MATE 1.19 from git master. Looks like what is going on is that the panel normally reserves space for itself, and this controls the menu position. Reserving that space when the panel is hidden would make that space useless by prohibiting all other windows (not just the menu) from occupying it.

What is most likely to create issues for users is the shutdown menu item coming up as a default, something which does NOT happen when the panel is not set to autohide. It looks like cursor position is the cause here: The cursor has to be at the position of the menu button (bottom left on my setup) to click it. When the menu comes up, the shutdown menu item is under the cursor and thus is selected. Thus an accidental slow double click on the button can invoke the shutdown dialog. When the panel is not autohidden, the menu comes up above the panel, and the cursor is still on the button, thus not on the menu at all

**Comment by raveit65** [comment] 2023-07-21 14:38
Seem to fixed with actual Mate version.

**Closed by raveit65** 2023-07-21 14:38 UTC
