### ISSUE TITLE
[1.16] Notification area icons disappears when apply a background image to the panel

### ISSUE THREAD

**Issue by caringi** [mate-desktop/mate-panel#585] opened 2017-05-31 09:15 UTC
When I try to set a background image for a panel, if this panel has a notification area, all their icons disappears.
![mate_panel_problem_before_background](https://cloud.githubusercontent.com/assets/2509235/26624810/5c2c0984-45f2-11e7-8363-e082de2f7fff.png)
![mate_panel_problem_after_background](https://cloud.githubusercontent.com/assets/2509235/26624817/61853acc-45f2-11e7-858f-b167a3fc0812.png)

**Comment by lukefromdc** [comment] 2017-05-31 17:30
What version of mate-panel, and is it built with GTK2 or GTK3? If GTK3, what GTK3 version?  MATE 1.18 always uses GTK3, and some distros such as Ubuntu and Debian build MATE 1.16 with GTK3. MATE 1.14 and earlier is almost always supplied built with GTK2 by distros.

Also, what kind of image? I can set a png or jpg image and never get this, the notification area icons show up fine on my panel. I have compiled mate locally with GTK3 all the way back to 1.10 and never seen this, but if this is with GTK2 that is why.

**Comment by caringi** [comment] 2017-06-01 08:22
I'm using MATE shipped with Fedora 25 (1.16.2).
It's using GTK3 (3.22.15):

```
$ ldd /usr/bin/mate-panel|grep libgtk
	libgtk-3.so.0 => /lib64/libgtk-3.so.0 (0x00007fce1f570000)

$ pkg-config --modversion gtk+-3.0
3.22.15
```
The image is in png format, I'm sending it attached, but it happens with all the images that I've tried (doesn't matter the image format)...

I have been using different versions of MATE in different systems in the last years and never seen this behavior before.

![panel_background1](https://cloud.githubusercontent.com/assets/2509235/26670046/62881ff2-46b0-11e7-9cef-f7498097f8fa.png)

**Comment by lukefromdc** [comment] 2017-06-01 17:27
I just tested your image, tray icons worked fine for me, using GTK 3.22.15 on Debian Unstable. I've never seen this, can't duplicate it. Can one of the other Fedora users here test this?

**Comment by monsta** [comment] 2017-06-06 09:31
@raveit65 please check if it happens in your Fedora versions :slightly_smiling_face:

**Comment by raveit65** [comment] 2017-06-06 13:54
I can confirm that with
```
[rave@f25 ~]$ rpm -qa mate-panel
mate-panel-1.16.2-2.fc25.x86_64
```
But not with
```
[rave@f26 ~]$ rpm -qa mate-panel
mate-panel-1.18.2-3.fc26.x86_64
```
mate-panel-1.16.2-2.fc25.x86_64 use only one commit from @monsta 
http://pkgs.fedoraproject.org/cgit/rpms/mate-panel.git/tree/mate-panel.spec?h=f25#n40
(fix-crash-when-some-.desktop-file-has-empty-Icon).
So this shouldn't be related.
I think we need to backport more na-tray fixes from master, on the other side i will upgrade f25 to 1.18.x in a few weeks when f26 is released ;-)
After that upgrade debian is the only distro which have to use 1.16.x with mate gtk3 builds, ....sadly.
@monsta 
Can you please test this with debian?

**Comment by raveit65** [comment] 2017-06-06 13:56
Btw. The icons in na-tray are there (physical), i see tooltips and context menus of them.

**Comment by monsta** [comment] 2017-06-08 13:45
Confirmed in Debian Testing with mate-panel 1.16.2 and GTK+ 3.22.11. The icons are invisible but clickable, and tooltips still work too.

**Comment by monsta** [comment] 2017-06-08 14:00
Looks like GTK+ 3.22 issue. I can't reproduce it with the same mate-panel version and GTK+ 3.20.9 in Ubuntu 16.10.

**Comment by raveit65** [comment] 2017-06-08 16:32
Not sure if this is gtk+- related, as f26 with gtk3-3.22.15-2.fc26.x86_64 and mate-panel from master don't have this issue.
But with f25 + gtk3-3.22.15-2.fc25.x86_64 + mate-panel-1.16.2-2.fc25.x86_64 the issue is reproducible.

**Comment by lukefromdc** [comment] 2017-06-08 17:37
Could this require a specfic version of glib with gtk 3.22 to reproduce, or of some other library?

**Comment by monsta** [comment] 2017-06-08 19:06
Not sure, but you'll need mate-panel 1.16 to reproduce it.

**Comment by lukefromdc** [comment] 2017-06-08 22:01
I never once saw this in mate-panel 1.16, and all my builds of it used GTK 3.22. I have never, ever seen this

**Comment by lukefromdc** [comment] 2017-06-08 22:24
Just tested with mate-panel 1.16.2 plus the last commit in the branch(GTK+3: fix crash when some .desktop file has empty Icon field), and the icons in the tray remained visible. Still can't duplicate on Debian Unstable but my gtk and giib builds are local builds.

Wonder if maybe some particular item in the tray triggers this?  What icons are normally "showing" when this occurs? I have the xrandr applet icon, the volume control, and my customized nm-applet including the panel menu support. Also the audacious tray icon if audacious is running.

**Comment by caringi** [comment] 2017-06-09 07:51
@lukefromdc I usually have:

- power manager (battery level)
- nm-applet
- volume control
- goldendict
- fusion-icon
- firewall applet
- display settings
- tomboy
- bluetooth

But I'm skeptical about this problem being triggered by some particular item.

**Comment by monsta** [comment] 2017-06-09 09:01
It doesn't matter, I can reproduce it with just volume control and nm-applet.

Maybe it's only reproducible in a VM?

**Comment by raveit65** [comment] 2017-06-09 09:43
> Maybe it's only reproducible in a VM?

Indeed, on bare metal + f25 + nvidia +
[rave@mother ~]$ rpm -qa gtk3
gtk3-3.22.15-2.fc25.x86_64
[rave@mother ~]$ rpm -qa mate-panel
mate-panel-1.16.2-2.fc25.x86_64
The issue isn't reproducible here, icons of applets are there in na-tray.
@caringi 
Do you use a VM?

**Comment by caringi** [comment] 2017-06-09 09:51
@raveit65 nop...

I'm reproducing the problem on bare metal: f25 + intel

```
$ lshw -C display
WARNING: you should run this program as super-user.
  *-display                 
       description: VGA compatible controller
       product: HD Graphics 520
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:126 memory:f0000000-f0ffffff memory:e0000000-efffffff ioport:e000(size=64) memory:c0000-dffff
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.

$ rpm -qa gtk3
gtk3-3.22.15-2.fc25.x86_64

$ rpm -qa mate-panel
mate-panel-1.16.2-2.fc25.x86_64
```

**Comment by lukefromdc** [comment] 2017-06-09 17:26
Would be very odd for this to be video driver dependant, though I did get video driver caused corruption of some panel items a year or two ago on Intel Atom pine trail, which is now poorly supported by drivers. Still, they showed up, they just rendered wrong.  Don't see any other likely hardware issues.

**Comment by monsta** [comment] 2017-06-10 11:44
Unfortunately, I only have 1.16 in a couple of VMs, so I can't compare... but even if I had it on baremetal, I only have nvidia cards.

**Comment by mokkurkalve** [comment] 2017-06-13 08:16
This have been the issue on x86_64 Arch Linux all the time since Arch switched to Mate 1.18 and started compile Mate against GTK3. 
All icons in systray becomes invisible when I try to apply the PNG image that worked nice with Mate 1.16/GTK2. As noted they are still there but completely invisible. 
Currently I have mate-panel 1.18.3 compiled against GTK3 version 3.22.15 and glib2 version 2.52.2+9+g3245eba16. 
mate-desktop version are 1.18.0. 
This is a physical laptop with intel graphics.

**Comment by lukefromdc** [comment] 2017-06-13 16:21
Someone who can reproduce this might be able to find the culprit by starting with 1.16 and applying 1.18 commits one at a time, sort of the inverse of a normal bisect.

**Comment by Michael-AU** [comment] 2017-06-14 04:49
I reported a similar issue against mate-panel 1.16.2-1 to Debian a little while back but Stretch is in complete freeze now so they haven't done anything. Anyway, if you apply any transparency to the panel the notification area icons disappear. It doesn't matter what theme is being used, it doesn't matter what icons are being used what matters is if you change the panel background or apply transparency.

**Comment by monsta** [comment] 2017-06-14 19:03
This is getting complicated. I looked at another VM with Debian Testing which has MATE built from git master (instead of stock 1.16). Guess what, it's reproducible there.

**Comment by monsta** [comment] 2017-06-14 19:09
Resizing or restarting the panel makes the icons visible. Apparently there's some refresh missing somewhere.

**Comment by raveit65** [comment] 2017-06-15 05:46
> Resizing or restarting the panel makes the icons visible.

Indeed this works, but starting the panel with session start makes the icons invisible.
Btw. with Centos7 VM and MATE compiledwith gtk3 i can't reproduce the issue.
[rave@localhost ~]$ rpm -qa gtk3
gtk3-3.14.13-20.el7_3.1.x86_64
[rave@localhost ~]$ rpm -qa mate-panel
mate-panel-1.18.3-1.el7.centos.x86_64

**Comment by monsta** [comment] 2017-06-17 11:57
I was only able to reproduce it with GTK+ 3.22...

**Comment by caringi** [comment] 2017-06-22 12:57
Today my F25 received an update with MATE 1.18...

```
$ rpm -qa mate-panel
mate-panel-1.18.3-1.fc25.x86_64
```

Seems that the problem persists... 

Actually the behaviour has changed a bit, now only part (as far as I can tell: always the same ones) of the icons disappears...

![mate_panel_1_18_problem_before_background](https://user-images.githubusercontent.com/2509235/27434952-bc7087ec-575a-11e7-9483-a168e2c41626.png)

![mate_panel_1_18_problem_after_background](https://user-images.githubusercontent.com/2509235/27434958-c0de7c6c-575a-11e7-864b-4e53e7d6fb91.png)

Fusion-Icon, Bluetooth, Firewall-applet and GoldenDict are never affected.

**Comment by monsta** [comment] 2017-06-22 13:09
Ah right. We have StatusNotifier support in 1.18, and these icons aren't affected. I'm not surprised - SNI is handled in a different part of code.

**Comment by lukefromdc** [comment] 2017-07-05 05:52
I can now confirm this too, after recent changes in Debian Unstable. Restarting the panel will bring them back. This is limited to a bg image selected from the panel-prefs dialog,newly-supported bg images in the GTK theme (https://github.com/mate-desktop/mate-panel/commit/a1445bc208e22260c27ce67ad4ebce6040ff5a3c made those work) are not affected

Rollback tests showed that my locally build GTK 3.22.16 and glib 2.53.3 were not to blame. There is a suggestion that the entire bg image code be rewritten around the far simpler code I've got working for images in the GTK theme, which never cover the tray icons in my current tests. One disadvantage of so doing is there is a bug in Cairo that causes an extreme stretch of small image to not render all pixels and this gradually get more and more transparent with great amounts of stretch (more than about 5-1). 

Also, usr set images will tile (not stretch) if they are very short, maybe that is a better way of handling theme backgrounds as well? In GTK itself "repeat" is the default, and a repeat of a 1px sample gives a perfect smooth background image bar.

**Comment by lukefromdc** [comment] 2017-07-05 06:04
Worse yet, I just found the entire code block that is supposed to scale user selected background images no longer seems to work, if you set an image that matches your panel height, it does not scale but either is cropped or a section is left uncovered. Lots of rework needed here

**Comment by lukefromdc** [comment] 2017-07-05 06:28
Here's the code for reading how a user set image is supposeds to be handled as to fix/stretch/rotate, in panel-profile.c:
```

	if (!strcmp (key, "type")) {
		PanelBackgroundType  background_type;
		background_type = g_settings_get_enum (settings, key);
		panel_background_set_type (background, background_type);
		panel_toplevel_update_edges (toplevel);
	} else if (!strcmp (key, "color")) {
		GdkRGBA color;
		gchar *str;
		str = g_settings_get_string (settings, key);
		if (gdk_rgba_parse (&color, str))
			panel_background_set_color (background, &color);
		g_free (str);
	} else if (!strcmp (key, "image")) {
		gchar *value = g_settings_get_string (settings, key);
		panel_background_set_image (background, value);
		g_free (value);
	} else if (!strcmp (key, "fit")) {
		panel_background_set_fit (background,
					  g_settings_get_boolean (settings, key));
	} else if (!strcmp (key, "stretch")) {
		panel_background_set_stretch (background,
					      g_settings_get_boolean (settings, key));
	} else if (!strcmp (key, "rotate")) {
		panel_background_set_rotate (background,
					     g_settings_get_boolean (settings, key));
	}

```

I see nothing in dconf-editor nor in the panel-prefs dialog for rotate, fit, or stretch, so these go to defaults. That seems to be fit and rotate, meaning the image does rotate to fit vertical panels but never stretches or shrinks to fit the panel. This breaks layouts like Ubuntu MATE Mutiny.

Meanwhile I'm also looking at the tray with icons "covered" and found that if the image is transparent they still are not there. They are either covered by the copied image of the desktop (which is an exact size match) or never rendered at all, not sure which. They can be clicked on, even though they are not actually displayed.

**Comment by raveit65** [comment] 2017-07-05 07:18
> They can be clicked on, even though they are not actually displayed.

This sounds like an issue with SNI-Support, maybe......
Did you try to disable SNI-Support via gsettings from the other PR?

**Comment by lukefromdc** [comment] 2017-07-05 18:19
I just tested this with SNI support turned off, no difference at all.  I also found another interesting thing: if compositing is turned off, a custom panel color with transparency will also make the tray icons disappear, while a solid color wiil not. If compositing is used the icons are always shown with a color background.

**Comment by monsta** [comment] 2017-07-05 19:27
It's reproducible in 1.16 too, so SNI support shouldn't affect it as it appeared only in 1.18.

**Comment by monsta** [comment] 2017-07-05 19:42
The mentioned fit/stretch/rotate keys are per-toplevel keys, dconf-editor doesn't show them unless they have some non-default value. There's the same problem with per-applet keys (except for stickynotes applet which has its own schema outside of `org.mate.panel` namespace).
I can only see the default values in  `data/org.mate.panel.toplevel.gschema.xml.in` file.

**Comment by lukefromdc** [comment] 2017-07-05 19:47
That means most GUI dependent user have no way to reset those values, as they are not in the panel preferences dialog. I think they were at one time but I am not sure. They don't got a non-default value if a user can't change them, so don't show up in dconf-editor. Since a user can't change them in panel-prefs they don't get changed at all.  This allows a distro to ship a changed value for something like Ubuntu-Mate Mutiny but that's about it. An image background will fit if it is done the way it was sometimes done in GTK2: a 1px wide, full height file that when tiles gives the background all the way across

**Comment by lukefromdc** [comment] 2017-07-06 05:10
Just found that the "stretch" option works fine with a manually edited schema.

I think what is happening with the disappearing icons is this: the compositing path copies the desktop background, as does the image path.

for an image, the code below in panel-background.c picks up the desktop background and seems to be the only difference in the rendering code for the noncomposited case:

```
if(!gdk_window_check_composited_wm(background->window)){
		cairo_set_source_rgb (cr, 1, 1, 1);
		cairo_paint (cr);

		gdk_cairo_set_source_pixbuf (cr, background->desktop, 0, 0);
		cairo_rectangle (cr, 0, 0, width, height);
		cairo_fill (cr);
	}

```
For a color with an alpha a similar trick is used.

Wonder if this is just enough slower to cause it to paint after the tray icons have already been painted? I've already found the desktop shows OVER tray icons that are still clickable if a transparent color or image background is used without compositing.

Tray icons are unique in that they come from programs external to mate-panel and are not panel applet icons either.

**Comment by lukefromdc** [comment] 2017-07-06 21:27
Working on backgrounds again, found the entire
image_details_dialog 
section of panel-properties-dialog.ui is present and unused, already found the gsettings values work if the schema is edited. Was this dialog lost or never properly implemented?

**Comment by lukefromdc** [comment] 2017-07-07 03:53
I just found that the icons only disappear if the panel size is 28px high or smaller. They keep showing at 29px or larger.

**Comment by lukefromdc** [comment] 2017-07-07 04:01
Also in na-tray-child.c na_tray_child_realize
replacing
gdk_window_set_composited (window, child->composited);
with
gdk_window_set_composited (window, FALSE);
will kill the tray background entirely (showing the desktop with compositing) and show the icon regardless of panel size.

Removing all of

```
 if (child->has_alpha)
    {
      /* We have real transparency with an ARGB visual and the Composite
       * extension. */

      /* Set a transparent background */
      cairo_pattern_t *transparent = cairo_pattern_create_rgba (0, 0, 0, 0);
      gdk_window_set_background_pattern (window, transparent);
      gdk_window_set_composited (window, TRUE);
      cairo_pattern_destroy (transparent);

      child->parent_relative_bg = FALSE;
    }
  else 

in the same function will also force the icons to appear except for sometimes being slow to redraw on changing panel size.  For some odd reason, just replacing gdk_window_set_background_pattern (window, transparent); with gdk_window_set_background_pattern (window, NULL); from the function beneath does not force the icons to appear
```

**Comment by lukefromdc** [comment] 2017-07-07 04:19
Found a fix: forcing a relative bg by replacing 
child->parent_relative_bg = FALSE;
with
child->parent_relative_bg = TRUE;
will force the icons to appear, included it in
https://github.com/mate-desktop/mate-panel/issues/607
along with my fix for vertical panels with an image bg in the GTK theme. Feel free to cherrypick if you want to merge the fix for this first, they affect completely different files.

**Comment by lukefromdc** [comment] 2017-07-07 07:10
I finally traced the offending function using child->parent_relative_bg to a force-redraw function that only worked if it was set to TRUE and changed that to work unconditionally. That works too. In a small number of panel restarts it is still possible for the icons to not come up until something forces a redraw (like moving the panel or changing its height) but most of the time this works

**Comment by raveit65** [comment] 2017-07-07 13:29
@caringi 
Can you please test those scratch build ? https://koji.fedoraproject.org/koji/taskinfo?taskID=20381480
With fixes from pull reguest.

**Comment by lukefromdc** [comment] 2017-07-08 20:44
Should be mostly fixed with https://github.com/mate-desktop/mate-panel/commit/ab786fa5282be8169b9c94d258cc57d07944ed13 
Leaving this open in case any problems remain, as I had occasional instances of the panel starting with the tray icons hidden but almost all the time (in fact ALL the time the last couple days) they have worked

**Comment by mokkurkalve** [comment] 2017-07-09 15:41
@lukefromdc 
Seems to fix the issue for me. Thanx!
( mate-panel 1.18.3 and gtk3 3.22.16 on Arch Linux current )

**Comment by caringi** [comment] 2017-07-10 13:48
@raveit65 tested... It's working as expected. Thanks!

**Comment by monsta** [comment] 2017-07-10 13:55
Need to test with older GTK+3 versions just in case, to make sure nothing wrong happens there with this change.

**Comment by lukefromdc** [comment] 2017-07-10 18:42
Just tested with all of the supported GTK versions back to 3.14, behavior seems to be the same in all of them.

To do this test, first ensure caja, mate-terminal, and anything else you may need are already open as many won't launch when GTK is rolled back. Mate-search tool seems to work with any version so it will be available, BTW Next, roll back libwnck to version 3.14, then install the test GTK version. Mine are all built as single packages for easy interchange. Having done this, recompile and reinstall mate-desktop, then do the same with mate-panel and restart the panel.  Repeat with each GTK version to be tested, libwnck 3.14 can stay as it works with all of them.

When done, reinstall your normal GTK version, your normal  libwnck, mate-desktop, and mate-panel versions. Be sure to do this before killing your session-or you won't be able to start any GTK3 based session. Unless you have a QT or GTK2 based session, recovery from that is from the console. Consider having a VT open and already on the directory with the packages in it.

**Comment by monsta** [comment] 2017-07-10 19:15
It's ok, I have several installations of various Debian/Ubuntu/Mint releases with various GTK+3 versions :slightly_smiling_face: 

So far, it looks alright with GTK+ 3.18 (Mint 18.2, based on Ubuntu 16.04).

**Comment by raveit65** [comment] 2017-07-11 06:03
Ok, closing.

**Closed by raveit65** 2017-07-11 06:03 UTC
Labels: confirmed

**Comment by caringi** [comment] 2017-07-14 08:17
Just to let you know... Seems that the problem is not 100% fixed.

After 5 days running the panel without problems, today it happened again.

I set the background image again and it and started working again.

**Comment by lukefromdc** [comment] 2017-07-14 17:27
I found in testing that this indeed worked most of the time but it was still possible for the icons to disappear. Restarting the panel, resizing the panel, moving the tray, or doing anything else to force a redraw brings them back. Right now I am experimenting with a slew of gnome-panel commits that redo the applet handling code to fix redraw issues with in-process applets, maybe that will help this too

**Comment by monsta** [comment] 2017-08-22 10:10
Ok, should we reopen this if it's not completely fixed?

**Comment by lukefromdc** [comment] 2017-08-22 17:40
I have not seen this problem come back since the in-process work, including in out-of-process tests. A test today with the tray out of process gave normal icon behavior with a custom image background, same as with the tray in-process(my usual build).

Has anyone else had this problem with current master? If not this can stay closed.

**Comment by raveit65** [comment] 2017-08-22 20:47
I will test it again, or maybe other Mate devs can test this too, to fix my heavy workload for mate.
Only asking for re-opennig the issue isn't sufficient, simply test it for yourself.

**Comment by martinkunev** [comment] 2017-12-03 15:58
I had the same problem except that I was using transparent background instead of background image. I believe the problem to be caused by the same core issue as everything else matches the descriptions of the problem by other people.
The bug is no longer observed after upgrading mate-panel, libmate-panel-applet-4-1 and mate-panel-common from 1.16.2 to 1.18.6 (on debian).

**Comment by monsta** [comment] 2017-12-24 19:57
Hmm, it could be the same problem, because https://github.com/mate-desktop/mate-panel/commit/188c705473849e9432c48a0a1a58adb7423ec630 (which fixes this) is in 1.18, but not in 1.16.

**Comment by Michael-AU** [comment] 2018-02-08 20:41
Sorry for the late reply, I have just moved and only just got phone and 
internet services connected.

With regards to this bug the problem for me is that I'm using Debian 
Stretch (Stable) and don't want to change to Debian Testing (Buster?). 
This issue has been reported on multiple bug reporting systems and as 
far as I have seen no one wants to fix it against the version it was 
reported on so users of Debian Stable (and other distros and versions 
that are on Mate 1.16) are stuck with a panel that does not work as it 
is intended to work.

If people don't want to fix it that's fine but please stop telling users 
of a Stable release that they need to upgrade to an development (and in 
Debian it is development) release because it will add more bugs to 
systems of users who don't want more bugs.

Cheers.

**Comment by alexarnaud** [comment] 2018-02-09 20:29
Debian has it own schedule and has no links with the Mate project. You can't blame the Mate guys about the Debian stuff.

@monsta what do you think of a back-port to 1.16?

Maybe @sunweaver  could give us his opinion.

Best regards.

**Comment by sunweaver** [comment] 2018-02-09 21:01
Last time I tried background image on the panel with 1.16, the whole panel crashed.

Our current focus is a stretch-backport of MATE 1.18. And I recommend to use that. Next effort is getting MATE 1.20 into Debian testing. Then the next effort is - after some testing - to bump MATE 1.20 into Debian stretch-backports.

**Comment by sunweaver** [comment] 2018-02-09 21:03
Don't get me wrong, but considering the rather small size of all involved teams and the strict Debian release policy, getting this and that arbitrary fix into Debian stable is only feasible for really grave issues. Background images on the panel are no grave issues IMHO.

(And you can always donate to the people on the team to get your issues prioritized...)

**Comment by sunweaver** [comment] 2018-02-09 21:08
And... if anyone can confirm that this fix (https://github.com/mate-desktop/mate-panel/pull/607/files) cherry-picked to mate-panel in Debian stretch fixes this issue, and is also willing to test the same against an X2Go session (there is another issue bothering us there: https://github.com/ArcticaProject/nx-libs/issues/337), then I'd be happy to propose a stretch-update of mate-panel to the Debian release team.

**Comment by alexarnaud** [comment] 2018-02-09 22:26
Le 09/02/2018 à 22:01, Mike Gabriel a écrit :
> Our current focus is a stretch-backport of MATE 1.18. And I recommend to 
> use that. Next effort is getting MATE 1.20 into Debian testing. Then the 
> next effort is - after some testing - to bump MATE 1.20 into Debian 
> stretch-backports.

Great to know, can I help you? I'm also interested to have Mate 1.18 on 
Stretch.

Best regards.

**Comment by sunweaver** [comment] 2018-02-11 19:12
Hi,

On  Fr 09 Feb 2018 23:26:22 CET, Alex ARNAUD wrote:

> Le 09/02/2018 à 22:01, Mike Gabriel a écrit :
>> Our current focus is a stretch-backport of MATE 1.18. And I recommend to
>> use that. Next effort is getting MATE 1.20 into Debian testing. Then the
>> next effort is - after some testing - to bump MATE 1.20 into Debian
>> stretch-backports.
>
> Great to know, can I help you? I'm also interested to have Mate 1.18 on
> Stretch.

MATE 1.18 is available via stretch-backports.

You can help in general with MATE in Debian by going through open bugs  
for all MATE packages in Debian and see if they still apply.

With the upcoming MATE 1.20 uploads, you can wait and then still check  
if bugs still exist.

With MATE 1.16 in stable, you can help with backporting patches for  
the more important issues and we can see to get them to stretch-updates.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Michael-AU** [comment] 2018-02-11 21:29
@ alexarnaud, I have not blamed anyone. I have, however reported a bug, on Debian BTS and taken part here, on MATE 1.16 and the consensus is don't worry about it. Again if its not going to be fixed by anyone anywhere in MATE 1.16 so be it but, again, encouraging people to "upgrade" from a stable release to a possibly buggier release when people rely on stability may cause more issues than its worth.

I humbly suggest this report is closed to further comments and all Debian related discussion for it is taken to the Debian bug report.

**Comment by flexiondotorg** [comment] 2018-02-11 21:42
Closed as requested.

**Comment by alexarnaud** [comment] 2018-02-13 12:17
Le 11/02/2018 à 20:12, Mike Gabriel a écrit :
> MATE 1.18 is available via stretch-backports.
> 
> You can help in general with MATE in Debian by going through open bugs
> for all MATE packages in Debian and see if they still apply.

I can take time to do that.

> With the upcoming MATE 1.20 uploads, you can wait and then still check
> if bugs still exist.

OK, I can do that also.

> With MATE 1.16 in stable, you can help with backporting patches for
> the more important issues and we can see to get them to stretch-updates.

I haven't the time to backport patch because I'm mostly busy by 
accessibility of Debian, Mate, LibreOffice, Firefox, Orca, Compiz 0.9 
and Debian to the beginners, visual-impaired and blind people.

Thanks for your great job Mike :) !
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by sunweaver** [comment] 2018-02-13 12:23
Hi Alex,

On  Di 13 Feb 2018 13:17:25 CET, Alex ARNAUD wrote:

>> With MATE 1.16 in stable, you can help with backporting patches for
>> the more important issues and we can see to get them to stretch-updates.
>
> I haven't the time to backport patch because I'm mostly busy by
> accessibility of Debian, Mate, LibreOffice, Firefox, Orca, Compiz 0.9
> and Debian to the beginners, visual-impaired and blind people.
>
> Thanks for your great job Mike :) !

This is an awesome expertise. Please help in Debian to assure MATE is  
approximating 100% accessibility. That would be a great help, having  
someone on the packaging team who QAs a11y of MATE in Debian.

Please make sure, you hang out on irc.debian.org #debian-mate and ping  
me there (my nick is sunweaver).

Thanks,
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
