### ISSUE TITLE
Icons for opened programs are unstable on vertical panel

### ISSUE THREAD

**Issue by anacon** [mate-desktop/mate-panel#277] opened 2015-02-09 16:33 UTC
This bug has been around since gnome2 and occurs when the main panel is configured vertically. After opening more than approximately six program instances, the icons flicker and erratically switch between one and two column placement when trying to select an icon with the mouse pointer. Since the icons are moving around, it becomes nearly impossible to select the desired one. This is mentioned under the comments to issue #157, Usable Vertical Panel, but I feel that it is a longstanding and serious UI problem and so have opened a separate issue for it.
##

**Comment by damarev** [comment] 2015-05-06 06:35
Since 2002:  https://bugzilla.gnome.org/show_bug.cgi?id=86382

I think, sadly, we should prepare a big party for his 13th birthday....   :(

**Comment by slacka** [comment] 2015-05-06 23:47
This is a dupe of #58. stefano-k says:

> Because 1.8 uses libwnck, so you need an updated libwnck. The issue is not is mate-panel

**Comment by mckaygerhard** [comment] 2017-03-23 19:38
i cited here:

> An old issue in the old and unmaintained GTK+2 version of libwnck, already mentioned in #157 and #277. Will probably be solved only when mate-panel is switched to GTK+3, as libwnck3 (GTK+3 version) will be used there.

switched to gtk3 ?

**Comment by monsta** [comment] 2017-07-27 12:18
This should be fixed now in 1.18 because of migration to GTK+3.

**Closed by monsta** 2017-07-27 12:18 UTC
