### ISSUE TITLE
GTK+3: icons in menu don't auto-refresh on icon theme change - need to hover over them

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-panel#274] opened 2015-01-23 10:08 UTC
Virtualbox, Debian Jessie, GTK+3 build of MATE 1.9 (all from git master).

When I change the icon theme in mate-appearance-properties, the icons in the panel menu don't auto-refresh. I have to hover mouse over them to make them change to the new theme.

You can see this at the screenshot below. I've changed the icon theme from Mint-X to Menta but the icons in the menu are still from Mint-X.

![menu-icons-bug-gtk3](https://cloud.githubusercontent.com/assets/5138986/5872751/0fac601e-a300-11e4-9fc5-781536541151.png)

**Comment by rilian-la-te** [comment] 2015-01-23 14:09
It is also in other GTK3 projects. I think there is GTK3 bug. Confirrm it.

I also created upstream bugreport: https://bugzilla.gnome.org/show_bug.cgi?id=743341.

I think there is exactly the same bug.

**Comment by monsta** [comment] 2015-01-23 14:11
Interesting... there's no Debian bug report on that (or I missed it).

**Comment by NiceandGently** [comment] 2015-02-20 00:06
looks like it is fixed in gtk3-3.15.5.
https://git.gnome.org/browse/gtk+/commit/?id=11d70f1ac30dd491d9d8dac9b9e2c31cee073cc9
I can't test it, i've only setup a mate gtk3 enviroment in  gtk3-3.14.

**Comment by monsta** [comment] 2015-02-20 11:36
I can try cherry-picking in to 3.14 in Debian and test... but the question is, do we need to change anything in the themes too for this to work?

**Comment by NiceandGently** [comment] 2015-02-20 15:20
i don't know......seems i need to to setup a f22 GTK3 enviroment.
I will do that in next weeks

**Comment by NiceandGently** [comment] 2015-02-21 13:29
Confirmed, the issue is gone with gtk3-3.15.7.

**Comment by monsta** [comment] 2015-02-21 14:05
No theme modifications required? Or do MATE themes already have the needed property?

**Comment by NiceandGently** [comment] 2015-02-21 21:14
I don't think, the icon theme switch works with all themes. But there are definitly adjustment for themes in gtk3-3.15 needed, ie. list-rows and others.
Sadly, i don't think that a gtk3-3.14 theme will work in gtk3-3.16., thanks again gtk+ m....f .
So, i can't be 100% shure.
Also, caja seems to be broken, i can't open any folder, maybe i need to set up a fresh f22 VM, not a clone from f21-gtk3 VM to get things working.
But i decided for myself not to work on themes for gtk3-3.16 until it is stable and not to waste my time for unstable dev releases ;)

**Comment by monsta** [comment] 2015-02-22 15:28
Yes, I'll try it in a few days.

**Comment by NiceandGently** [comment] 2015-02-23 15:00
After setting up a new mate gtk3-3.15.x VM, i'm pretty shure that no adjustments are needed for themes. Here i don't see the issue anymore with every mate theme and every application menu.
On the other side i don't see the issue with Menta themes in GTK3-3.14 in the panel menu anymore, but i see it in caja-sidebar.
So, maybe i can do something for the other themes.
But is there really a action needed when it is fixed with GTK+-3.15.x?
I'm in doubt that we start with GTK3 in a distro before GTK+-3.18 ;)

**Comment by monsta** [comment] 2015-02-24 09:01
Damn.
GTK+ 3.14.5 won't build with this patch because GtkCssStyle type (used by the new code) isn't known there. Gotta find out where it was introduced and cherry-pick that as well. But I'm afraid this will make the patch so big that Debian and Ubuntu maintainers won't accept it...

**Comment by NiceandGently** [comment] 2015-05-20 16:07
@monsta 
can we close that, i mean it is unfixable from our side for gtk3-14 and i see no distro with building Mate with GTK3.14.

**Closed** 2015-05-20 18:18 UTC
