### ISSUE TITLE
mate-session: WARNING: Application 'mate-panel.desktop' failed to register before timeout - since 1cfcb58 commit (June 11)

### ISSUE THREAD

**Issue by L-U-T-i** [mate-desktop/mate-panel#1111] opened 2020-07-16 09:54 UTC
#### Expected behaviour
Starting VNC session with mate desktop, there shall be no such error in VNC log file. And, has not been until [1cfcb58 commit (June 11)](https://github.com/mate-desktop/mate-panel/commit/1cfcb58dd5bc3e6effac1d2cdbc482dce930dd9b).

#### Actual behaviour
For all builds since (including) this commit (as well as for 1.25.0 release), the following line appears in VNC log (session for root user):
`mate-session[26960]: WARNING: Application 'mate-panel.desktop' failed to register before timeout`
or (session for normal user):
`mate-session[27824]: WARNING: Application '10c711634b52c3e240157368417132901900000090890050.desktop' failed to register before timeout`
(~/.config/mate-session/saved-session/10c711634b52c3e240157368417132901900000090890050.desktop is a launcher for mate-panel)

Both panels (top & bottom) are there and function as before, but I suspect it still shouldn't be like that (I have an issue with vncserver restart crashes since CentoS 8.1 o 8.2 upgrade, but most probably not related to that - as it happens also on the other system with older mate desktop releases before this started to happen).

#### Steps to reproduce the behaviour
Start a vncserver session with mate desktop, set session to be saved upon logout and check vncserver log after next vnc session (when desktop is to be restored).

Downgrading mate-panel to a build before [1cfcb58 commit (June 11)](https://github.com/mate-desktop/mate-panel/commit/1cfcb58dd5bc3e6effac1d2cdbc482dce930dd9b) makes the warning disappear (hence an issue is reported here and not for mate-session-manager, which actually issues the warning, I guess).

#### MATE general version
1.24 (1cfcb58 commit) / 1.25.0

#### Package version
x86_64 RPM

#### Linux Distribution
CentOS 8.2

**Comment by raveit65** [comment] 2020-07-16 10:29
1.25 is a developer version. It is not intend to use it on a server for stable usage.
You are doing this for your own risk!
Please use stable Mate 1.24. or better pre-compiled MATE from Fedora.

By the way, you don't need to start the panel with save-session state files.
The panel starts automatic via mate-session-manager.
```
[rave@mother ~]$ gsettings get org.mate.session.required-components panel
'mate-panel'
```

PS: I don't have this problem with my official fedora RPMs updated with 1.25 on my f32 box.
And i stopped maintaining MATE for RHEL8 and it's derivatives after RHEL7,
because i don't have any spare time left to give you support for free ;)
Maintainer is wanted!

**Comment by L-U-T-i** [comment] 2020-07-16 11:52
It is not a stable use, it is a development server...

I have CentOS 8, I'm not sure which Fedora releases would work for me, if at all and how (as much as I remember now there are some packages with slightly different names in CentOS as in Fedora...). I had to rebuild quite some dependencies anyway, so no big problem for me also to rebuild Fedora packages. Besides, I am facing some small annoyances from time to time also on my Fedora notebook (Fedora 29, 30 and 31 now...).

I've started to build also git commits due to some issues with released packages (memory leaks and so, already in CentOS 7...), and got used to it by now. I don't think I contribute much to the issues...

> [rave@mother ~]$ gsettings get org.mate.session.required-components panel
'mate-panel'

Exactly the same in my case:
`[root@c8-v1 ~]# gsettings get org.mate.session.required-components panel`
`'mate-panel'`

As said, I have the same issue also building with 1.25.0 tarball (based on adapted 1.24.0-5.fc33 spec file).

**Comment by lukefromdc** [comment] 2020-07-23 19:50
This is a duplicate of 
https://github.com/mate-desktop/mate-panel/issues/1091
which was caused by the change to using libegg from mate-submodules and was closed by 
https://github.com/mate-desktop/mate-panel/commit/fa89a226dbe00e00580555e7cd0364301c2e07a9


If you build and install current 1.25 using current mate-submodules you should not have this problem unless something else is wrong.

**Closed by lukefromdc** 2020-07-23 19:50 UTC
