### ISSUE TITLE
notification area tooltip placement bug

### ISSUE THREAD

**Issue by IndichRMV** [mate-desktop/mate-panel#229] opened 2014-08-22 18:14 UTC
The tooltips generated for icons in the notification area are inconsistent with those generated for such as the clock, the show desktop button, the minimized windows, etc.

They're being rendered either far away and to the left, or close up to the right, as opposed to centered under/over as with everything else. See attached images.

Normal tooltip example (notice how the tooltip is centered above the window's button):
![tooltip_normal](https://cloud.githubusercontent.com/assets/8524773/4015073/7f91b80e-2a27-11e4-8f2c-ac410fc904bb.png)

Tooltips with issues examples:
(I will try to attach these separately -- I keep getting error messages when I try to attach ...)
##

**Comment by monsta** [comment] 2015-07-02 12:23
I can't reproduce the "far away" part. Tooltips are always displayed close to the mouse pointer for me.

**Comment by IndichRMV** [comment] 2015-07-21 14:29
In Fedora 20, the tooltip would sometimes appear all the way to the left side of the screen. In Fedora 22, I can often (always) get the Thunderbird tooltip to appear at the very bottom of the screen:

![very-far-away](https://cloud.githubusercontent.com/assets/8524773/8803151/47558eda-2f93-11e5-83a1-1bcd468520ec.png)

**Comment by IndichRMV** [comment] 2015-07-21 14:58
I think it has something to do with the compositing manager. Try enabling as follows:
gsettings set org.mate.Marco.general compositing-manager true;

Then enable the FireTray addon for Thunderbird, as I seem to have a much higher reproduction rate with this. Then reboot. Then hover mouse over Thunderbird tray icon.

I noticed that the bug immediately disappeared when I turned off the compositing manager. Re-enabling the compositing manager did not make the bug re-appear until after rebooting.

One way to address this bug would seem to be to make it so that tray icons use the same tooltip positioning as everything else. Gnome 2 switched to the centered tooltips a long time ago, but apparently forgot to update the tooltips for tray icons. The centered tooltips aren't affected by this bug. I can't think of any reason the tray icons should have tooltip positioning which is inconsistent with the rest of the desktop environment...?

**Comment by monsta** [comment] 2015-07-23 09:07
> Gnome 2 switched to the centered tooltips a long time ago

I don't see that in window list and other applets in MATE 1.10.

**Comment by NiceandGently** [comment] 2015-07-23 14:27
fedora 20 with mate-1.8 is EOL since 2 months and will never get an update anymore.

**Comment by IndichRMV** [comment] 2015-07-30 00:23
NiceandGently, the problem still exists in Fedora 22.

monsta,
Which theme are you using? I wonder if this is theme dependent, though I'm not able to get tooltips placed like yours in any of the themes installed in Fedora 22.

The "new" tooltip behavior (the centering) has been in place since Gnome 2.28. The new behavior was upsetting to some users because the tooltips obscure menu items with their new positioning. Reference the following bug:
https://bugzilla.redhat.com/show_bug.cgi?id=532305

**Comment by monsta** [comment] 2015-08-01 11:01
I'm using Mint-X (the default theme in Mint), but I get the same behavior with e.g. Menta or BlackMATE.

**Comment by IndichRMV** [comment] 2015-08-02 14:53
I've confirmed that the tooltip behavior is different in a default installation of Mint as compared with a default installation of Fedora.

I'm trying to figure out what the difference is ... any ideas?

**Comment by raveit65** [comment] 2017-05-28 07:24
I don't see the issue any more with MATE gtk3 version in fedora, so closing this.

**Closed by raveit65** 2017-05-28 07:24 UTC
Labels: unconfirmed

**Comment by eotheeppu** [comment] 2017-08-03 20:57
actually, this bug is still present in Fedora 26 with Mate 1.18.0 (gtk3) ...

there's a difference in the tooltip for the tray icons between gtk2 application tray icons and gtk3 application tray icons, so e.g. the pidgin tray icon uses the gtk2 tooltip, and thunderbird (now compiled against gtk3) uses the gtk3 tooltip. i would have expected the tooltip to be determined based upon the gtk version of the tray itself, like the tooltip for each item in the window list is. is there a way to make the tray use gtk3 tooltips exclusively, like the window list does, rather than choosing the tooltip based upon the gtk version used by the individual application?

**Comment by lukefromdc** [comment] 2017-08-03 21:03
Anything coming from an icon in the tray comes from the application itself, not the tray. This is the way the tray supports GTK2, GTK3, and QT programs, each of which pop up menus, toolips, etc in their own widget toolkits etc. There are newer trays (cinnamon and cairo-dock come to mind) that in some way intercept all that and replace it with their own code (and thus in the panel's toolkit), but that was not done in GNOME 2 and thus not in MATE.

**Comment by raveit65** [comment] 2017-08-04 05:40
That's an easy task,.......you need to blame pidgin developer to switch to gtk3 ;-)
