### ISSUE TITLE
GTK3 clock applet width changing

### ISSUE THREAD

**Issue by MDykstra** [mate-desktop/mate-panel#491] opened 2016-10-19 00:52 UTC
Using GTK3 version of Mate 1.16.0 on Arch Linux.
Open calendar in clock applet, then fold down **'Locations'**. Notice small width:
![clock-applet-1](https://cloud.githubusercontent.com/assets/1680211/19501458/2e57b1a4-95a6-11e6-8ea8-69cd0c2512b0.png)

Toggle by clicking **'date, time'** twice on panel. Notice larger width; the correct width as it was under GTK2:
![clock-applet-2](https://cloud.githubusercontent.com/assets/1680211/19501536/bb122fa2-95a6-11e6-9511-35e5e274a92e.png)

Now fold back **'Locations'** and notice confusion about width:
![clock-applet-3](https://cloud.githubusercontent.com/assets/1680211/19501579/fe8de348-95a6-11e6-96e1-ee3c6d36b88c.png)

**Comment by lukefromdc** [comment] 2016-10-19 02:07
Perhaps this is an interaction with one or more themes? I've used mate-panel
with every version of GTK3 back to 1.14, and every version of MATE back to 
1.9 (development) and never had this happen. I have the day of the week, the
date, and the time in 12 hour format without seconds in the clock button.

**Comment by raveit65** [comment] 2016-10-19 05:32
Confirmed with f24 gtk+-3.20, blue-submarine, Menta, BlackMATE, etc.
Here the calendar get a smaller width if you un-expand the location GtkExpander.
Looks like we need a minimum width for the calendar window which have the same width than the world map.
I never noticed that as locations are always expand here.

**Comment by lukefromdc** [comment] 2016-10-19 05:56
Ok, that explains why I never see this. In my theme (UbuntuStudio_Legacy) the calendar is expanded by padding around the days to fit a grid background image. The "Locations" section gets pulled out to that size, not the other way around. Thus, this can be controlled in themes, or with a hardcoded minimum width in the code. Might have to be different for GTK 3.14-18 and for GTK 3.20-22, the theming syntax is quite different as we all know.

**Comment by raveit65** [comment] 2016-10-19 06:10
Any chance to set this in code as i see that reporter don't use our themes?

**Comment by MDykstra** [comment] 2016-10-19 09:35
I use slightly altered `Greybird` theme from `Shimmer Project` inteded for Xfce. It was recently updated for GTK 3.20-22 in a separate branch. I noticed toggling `Locations` a few times, that the calendar extends outside the screen the second time the world map appears (with this theme).

**Comment by lukefromdc** [comment] 2016-10-19 20:45
Try https://github.com/mate-desktop/mate-panel/pull/492

**Comment by raveit65** [comment] 2016-10-20 18:46
merged https://github.com/mate-desktop/mate-panel/commit/83cb1da7086ec9f901d5cc7eea2d9e2c569f8266

**Closed by raveit65** 2016-10-20 18:46 UTC
Labels: confirmed

**Comment by lukefromdc** [comment] 2016-10-25 18:41
OK, what should we do for dev-gtk3-migration? The first commit of
this can go there unchanged as the GTK version selectors are not
used there.
