### ISSUE TITLE
Probable Memory Leak in mate-panel [$200]

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/mate-panel#479] opened 2016-09-12 08:19 UTC
Steps to reproduce:
- Fresh install
- Fire up a slideshow in Eye Of Mate in fullscreen mode on a folder containing a lot of big pictures
- Monitor memory consumption using:

``` bash
#! /bin/bash
panel=`ps axu | grep " [m]ate-panel" | tr -s '' ' ' | cut -d' ' -f2`
eom=`ps axu | grep " [e]om" | tr -s '' ' ' | cut -d' ' -f2`

top -b -d10 -p $panel,$eom | grep -E --line-buffered " $panel | $eom " | tee -a out.log
```

Plot output, feel free to verify the plotting script:
https://gist.github.com/epgfm/9b6f7d26dfe467c92daacbd44127db3e

Originally investigated here:
https://ubuntu-mate.community/t/possible-memory-leak-in-mate-panel/7717

Downstream bug report for Ubuntu MATE 16.04 LTS with MATE 1.12.1:
https://bugs.launchpad.net/ubuntu-mate/+bug/1608599

Filing this issue here because I have now successfully reproduced this under Fedora 24 (MATE spin) with MATE 1.14.1

```
[root@FedMATE Desktop]# inxi -S
System:    Host: FedMATE Kernel: 4.7.2-201.fc24.x86_64 x86_64 (64 bit) Desktop: MATE 1.14.1
           Distro: Fedora release 24 (Twenty Four)
```

![figure_1](https://cloud.githubusercontent.com/assets/10635269/18428897/dde24ed8-78d0-11e6-9982-f91c1dd02f54.png)

Full log file include monitoring of pluma but pluma curves are not plotted in the above figure.
[out.log.tar.gz](https://github.com/mate-desktop/mate-panel/files/466843/out.log.tar.gz)

Also few explanations: I sent SIGSTOP to eom at some point (Drop in CPU usage - memory flatlines), and SIGKILLed it later (Not in the graph because I couldn't figure out how to plot it) - memory used by mate-panel stayed the same after eom was SIGKILLed.
##

**Comment by epgfm** [comment] 2016-09-12 08:22
Full log file include monitoring of pluma but pluma curves are not plotted in the above figure.
[out.log.tar.gz](https://github.com/mate-desktop/mate-panel/files/466843/out.log.tar.gz)

**Comment by epgfm** [comment] 2016-09-18 14:08
Can someone please advise if more information is needed from that Fedora environment?
I'd like to re-purpose the machine and I don't want to have to reinstall Fedora.

**Comment by clbr** [comment] 2016-10-26 11:52
I tried to reproduce in Xubuntu 16.04, but couldn't. Either mate-panel defaults are different in the plain package vs Ubuntu Mate, or I should've used a few gb of different images instead of symlinks to the same image.

Can you install the debug packages for mate-panel and libgtk2.0.0, and grab valgrind logs from both valgrind and massif? A short run should be sufficient since you can reproduce, maybe 10min.

valgrind --log-file=valgrind.log --show-reachable=yes mate-panel --replace
valgrind --tool=massif mate-panel --replace; ms_print *massif* > massif.log

When I ran the above, valgrind showed no leaks vs a run without eye-of-mate, and massif showed no increase either.

**Comment by epgfm** [comment] 2016-10-26 13:05
> Can you install the debug packages for mate-panel and libgtk2.0.0

Hi, can you provide guidance on how to do that?
Sorry, kind of a noob here. :x

**Comment by clbr** [comment] 2016-10-26 15:37
Yeah, "apt-get install mate-panel-dbg libgtk-2.0.0-dbg" is enough, and that warning can be ignored, Ubuntu's valgrind is a bit old. Thanks, the logs show it's not a traditional leak with lost pointers, but rather a growing array/similar where the old elements are never freed. I'd say the function missing the free is panel_toplevel_unrealize, but I'm not yet sure what exactly.

Please grab a new valgrind log with these:
valgrind --log-file=valgrind.log --leak-check=full --show-reachable=yes mate-panel --replace

**Comment by epgfm** [comment] 2016-10-26 16:08
New valgrind log with --leak-check=full:
[valgrind.2.log.tar.gz](https://github.com/mate-desktop/mate-panel/files/553813/valgrind.2.log.tar.gz)

**Comment by clbr** [comment] 2016-10-26 18:19
Actually, this looks like a gtk bug. New files get added to the "Recent files" list, and this affects all running gtk2 apps.

Checking now if it's fixed in gtk3, whether it needs a backport or a targeted fix.

**Comment by clbr** [comment] 2016-10-26 18:27
Confirmed, that's the reason.

**Comment by clbr** [comment] 2016-10-26 19:06
http://pastebin.ca/3733209

Here's a POC that adds garbage data to the Recent Files list. Running it should be a quicker test than eom with lots of images.

Compile with
```
gcc -o killer killer.c `pkg-config --cflags --libs gtk+-2.0`
```

**Comment by clbr** [comment] 2016-10-26 19:22
The same issue affects gtk3. I will make a patch for both, perhaps tomorrow.

**Comment by epgfm** [comment] 2016-10-26 19:55
Damn.
Yeah, I can confirm your POC works. Running it in a loop is impressive.

**Comment by clbr** [comment] 2016-10-27 15:12
Patches available for three gtk versions at:
https://bugzilla.gnome.org/show_bug.cgi?id=773587

Once they're accepted, I'll open bugs against Ubuntu gtk2 and gtk3 to apply them.

**Comment by lukefromdc** [comment] 2016-10-27 17:42
Setting gtk-recent-files-max-age=0 in ~/.config/gtk-3.0/settings.ini should prevent this for now if you don't use recent files. This of course would not prevent one user of a muitiuser system from setting that to something else to DOS a whole system by consuming the RAM. GTK 3.22.2 just came out, without the proposed patch. Let's hope the patches get accepted for GTK 3.22.3 and the next GTK 2.24 version.  Otherwise we have to find a way to limit "recent files" additions in every single program that uses it.

**Comment by lukefromdc** [comment] 2016-11-14 05:44
Both gtk 2.24 and gtk3.22 just got commits stopping recent-files from growing to arbitrary size in their git branches, should be out in the next point releases.
For GTK 3 the commit is 
git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=bf560369f2401e2cdd16f962f248e98c890835d0

For GTK 2.24 the commit in question is
git.gnome.org/browse/gtk+/commit/?h=gtk-2-24&id=a3b2d6a65be9f592de9570c227df00f910167e9e

**Comment by clbr** [comment] 2016-11-14 08:29
Yeah, but there was a small mistake in them, so please hold for the second part to land.

**Comment by clbr** [comment] 2016-11-15 11:05
All in, relevant Ubuntu bugs:
https://bugs.launchpad.net/ubuntu/+source/gtk+2.0/+bug/1641912
https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1641914

**Comment by jbicha** [comment] 2016-11-22 21:40
@flexiondotorg Ping in case you're interested in SRUing the GTK+ fixes. (The GTK2 bug hasn't been fixed in zesty either).

**Comment by lukefromdc** [comment] 2016-11-23 03:41
GTK 3.22.4 has been released with the relevant bugfix, but it's been two months since GTK2 has had a point release. Mate-panel 1.17 is now GTK3 only, so if this came from the GTK recent files list it should be fixed by that.

**Comment by epgfm** [comment] 2016-11-23 16:51
> Otherwise we have to find a way to limit "recent files" additions in every single program that uses it.

So with the fixes coming in from upstream, this leak issue will soon be fixed.

However, the incoming fix set a large number of items (1000) as a hard limit.
I know updating every single program would take some work, but would that not be a better option in the long run?
Does an application really needs to store 1K recent files? I think even the badassest screen you can possibly buy now wouldn't have enough vertical space to display them all.
I know memory is cheap, but as shown in the graph CPU usage also grows with the recent file list.

**Comment by flexiondotorg** [comment] 2017-08-10 21:30
@clbr Supported Ubuntu versions now include your patches. I'm closing this issue. Please claim the Bounty ☺️

**Closed** 2017-08-10 21:31 UTC
Labels: bounty
