### ISSUE TITLE
Workspace GUI option "Allow workspace wrap around in switcher" does nothing.

### ISSUE THREAD

**Issue by BrotherAl** [mate-desktop/mate-panel#420] opened 2016-03-23 20:33 UTC
After some research into the the issue I've discovered that the GUI back end controlled by [workspace-switcher.c](https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/workspace-switcher.c) calls `wrap_workspaces_changed`. This attempts to set or clear a boolean value called `wrap-workspaces` which does not exist in the schema, and as a result does nothing. The preferences GUI suggests that the paging system only supports a horizontal layout of virtual desktops but the code in Marco clearly shows support for multiple rows and columns. The preferences GUI will have to be changed to reflect this and the `wrap_workspaces_changed` as well as `wrap_workspaces_toggled` functions will have to be rewritten to support the proper gsetting in **org.mate.Marco.WrapStyle**. This key is not a simple boolean but an enumerated list with the selections of "no wrap", "classic", and "toroidal" 
##

**Comment by BrotherAl** [comment] 2016-03-23 20:48
I'm wondering if the code from Marco should be changed to a boolean. Is there a reason to have a difference between "classic and "toroidal"?

**Comment by muesli4** [comment] 2017-03-19 16:44
I initially wrote this functionality. Upon updating to version 1.18 I noticed that it has been removed (See: https://github.com/mate-desktop/mate-panel/commit/d0ddaedffa7d417a699cafce73c1e418515c4a28#diff-6a52aa73583e754f64a0683c23ceba46). I don't know why you throw away code that worked perfectly fine and was very usable, just to leave it in a broken state.

**Comment by raveit65** [comment] 2017-03-19 17:15
well, shit happens.
This has to be done by a mistake.
@monsta 
Huston, we have a problem :-)

**Comment by raveit65** [comment] 2017-03-19 17:23
Ok, enable the function via gsettings is working.
So only the GUI is broken, Here changing the option doesn't change the value of the gsettings key.

**Comment by raveit65** [comment] 2017-03-19 17:27
> I'm wondering if the code from Marco should be changed to a boolean. Is there a reason to have a difference between "classic and "toroidal"?

There is a different see https://github.com/mate-desktop/marco/pull/303 for explanation

**Comment by muesli4** [comment] 2017-03-19 17:32
I have trouble following the code. Did the scroll event somehow move to https://github.com/mate-desktop/marco?

**Comment by muesli4** [comment] 2017-03-19 21:24
> There is a different see mate-desktop/marco#303 for explanation

It turns out that the *wrap style* chosen for *marco* only affects *marco* (i.e. switching with keybindings, where a little window pops up). What the new code seems to rely on is the *scroll event handler* from *libwnck* (thus always top-down then left-right, without end to start wrap). However, wouldn't it be nice if that behavior could be shared by *marco* and *mate-panel*? Any idea how? Other ideas?

**Comment by monsta** [comment] 2017-03-20 20:08
If I removed some code in that commit, it was because the code was for GTK+2 build only (unless I overlooked something). I need to check how it worked before...

**Comment by monsta** [comment] 2017-03-20 20:15
Oh. Just noticed that the report was created when even 1.14 wasn't released yet.

**Comment by muesli4** [comment] 2017-03-23 20:38
For now I restored the previous behavior. (Sharing the behavior with *marco* is probably not the best idea.)

**Comment by monsta** [comment] 2017-03-30 14:24
I found where the scroll handling was removed from GTK+3 build: https://github.com/mate-desktop/mate-panel/commit/0be1bd917ac00a4553bc6d3ace836aed44cd99a4. So the current behavior was there in GTK+3 build since 1.14.

**Comment by raveit65** [comment] 2017-04-02 21:18
Ok fix is in master.

**Closed by raveit65** 2017-04-02 21:18 UTC
Labels: confirmed

**Comment by knopancakes** [comment] 2019-05-09 18:09
This issue is back

**Comment by muesli4** [comment] 2019-05-09 18:56
I don't think so. There is no history change in this file that is related. You're probably using an old version. Don't report bugs without a version or any commit checksum. Use a proper distro that keeps packages up to date.

**Comment by knopancakes** [comment] 2019-05-10 02:55
@muesli4 I don't think so either. I just did a fresh install of Mate 18.04.2 Bionic LTS. This issue is present on more than one machine.

**Comment by muesli4** [comment] 2019-05-10 15:15
@knopancakes Please read my post again. It is painfully apparent that you haven't done that yet.

**Comment by knopancakes** [comment] 2019-05-10 23:56
@muesli4 I read your post. I'm trying to tell you there's a problem and you're being dismissive and unhelpful.

**Comment by vkareh** [comment] 2019-05-11 01:16
I can confirm this issue on Ubuntu MATE 19.04, with both mate-panel and marco built from `master`. However, this one was closed years ago and dealt with. Can you open a new one please? If this happens with Ubuntu, report it there (launchpad), then post the link in the new issue you open.

**Comment by muesli4** [comment] 2019-05-11 07:45
> @muesli4 I read your post. I'm trying to tell you there's a problem that seems related to this topic and you're being dismissive and unhelpful.

That's simply not true. I asked you to at least report a version or commit checksum. None of which you did. How is anyone supposed to debug this in your opinion? I even spent some of my time to look at the history of the file which didn't change in that regard. I'm not claiming you're not having these issues. I'm just saying the most logical explanation is  that it has nothing to do with the current state of the code (until you point out which version you have).

> Can you explain to me how I could have ended up with an old version if I have updated my packages using apt on 18.04?

Please use Ubuntu as a prefix, that is not self-explanatory. I can't tell you. But I have *mate-panel* 1.22 and it works for me (I can turn it on and off, and it wraps as expected).

**Comment by muesli4** [comment] 2019-05-11 07:59
@vkareh I can not confirm this issue. I built the latest commit of **mate-panel** and everything works properly (on Archlinux). There is something fishy going on with Ubuntu.

**Comment by vkareh** [comment] 2019-05-11 11:11
Hence the suggestion to report to launchpad.

I would appreciate not adding more to this thread, it's not helping any of us debug this.

**Comment by knopancakes** [comment] 2019-05-11 17:07
@vkareh Thank you, I would be happy to move this over to launchpad

**Comment by knopancakes** [comment] 2019-05-13 15:14
https://bugs.launchpad.net/ubuntu-mate/+bug/1828842
