### ISSUE TITLE
Panel issues in dual screen layouts (overlapping window decoration, broken hiding behavior) [$115]

### ISSUE THREAD

**Issue by phocean** [mate-desktop/mate-panel#803] opened 2018-05-04 17:40 UTC
#### Expected behaviour

Unless using maximus, whatever the screen layout is, the title bar of a maximized window should be displayed.

#### Actual behaviour

In a dual screen environment and vertical layout (external screen on top of primary), maximized windows on the primary do not have a title bar.

More precisely, the top bar overlaps on the title bar, hiding it.

It can be verified by setting the top bar to a small size so that a tiny portion of the title bar actually shows up.

#### Steps to reproduce the behaviour

1. Plug in an external monitor
2. Set a vertical layout with the external monitor on top of the primary
3. Put a panel at the top of the primary screen
4. Maximize any window in the primary monitor
5. The title bar is hidden by the panel

Normal maximized window in single monitor layout:

![capture du 2018-05-11 00-52-58](https://user-images.githubusercontent.com/4280885/39898147-d4d12e8c-54b5-11e8-9a48-9aea13967dfd.png)

Maximized window with decoration overlapped by the panel in dual screen vertical layout:

![capture du 2018-05-11 00-53-18](https://user-images.githubusercontent.com/4280885/39898166-eb536abc-54b5-11e8-9640-925050a2be61.png)

#### Linux Distribution

Ubuntu Mate 18.04

**Comment by phocean** [comment] 2018-05-10 22:51
I just found something that is probably related:

1. Plug in an external monitor
2 Set a vertical layout with the external monitor on top of the primary
3. Put a panel at the top of the primary screen
4. Set it to hide automatically
5. Observe how it "hides", actually moving/flipping to the screen at the top !

That's probably the "trick" that works to hide the panel when it is at a geometry edge, but it is totally broken in other layouts.

Settings:

![capture du 2018-05-11 00-45-47](https://user-images.githubusercontent.com/4280885/39897962-e88a0d82-54b4-11e8-8ecc-ee3f9b1e3536.png)

The mouse cursor is over the panel, so it is not hiding and displays normally on the primary screen:

![capture du 2018-05-11 00-48-40](https://user-images.githubusercontent.com/4280885/39898036-404ee4ca-54b5-11e8-8229-57fd1b70c236.png)

The mouse cursor is away, so the panel is "hiding", but still visible as it is simply flipped to the secondary screen at the top:

![capture du 2018-05-11 00-46-44](https://user-images.githubusercontent.com/4280885/39898066-69fb2b9e-54b5-11e8-88c3-2c9b5f712b5d.png)

**Comment by phocean** [comment] 2018-05-10 23:04
I just found issue #303 that seems related.

**Comment by vkareh** [comment] 2018-05-10 23:04
I marked it as confirmed, as I get this behavior as well :P

Also, the hide animation when starting the panel actually shows the panel on the top monitor before moving it down. Same issue

**Comment by vkareh** [comment] 2018-05-11 00:03
@raveit65 - if your primary is a laptop, I find that vertical is really nice. Just put the laptop right in front of the monitor (which I have propped to be just high enough for my laptop). Very nice setup :)

**Comment by sc0w** [comment] 2018-07-28 11:11
https://www.bountysource.com/issues/57959471-panel-issues-in-dual-screen-layouts-overlapping-window-decoration-broken-hiding-behavior

**Comment by WatIsDeze** [comment] 2020-01-06 02:56
This still isn't fixed it seems, I've actually had the sliding to another monitor happen from left to right visa versa. This is the case on the following system:

Note that the lower resolution screen is positioned left in Displays, and is using the Radeon it's DVI output. While the main high res screen is using its VGA output. (Wish it was otherwise.)

Nonetheless, I googled since I had a few issues getting panels going on this screen with the DVI input and ran into this same issue. Had to work my way around it a bit, managed to fetch it in time and was able to modify its properties though. In the end I had a top bar successfully but removed it nonetheless. Is there a chance it may be partially caused due to different screen resolutions?

"CPU:
  Topology: Quad Core model: Intel Core i5-2400 bits: 64 type: MCP 
  arch: Sandy Bridge rev: 7 L2 cache: 6144 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 24743 
  Speed: 2021 MHz min/max: 1600/3400 MHz Core speeds (MHz): 1: 2021 2: 2024 
  3: 2101 4: 2855 
Graphics:
  Device-1: AMD Cedar [Radeon HD 5000/6000/7350/8350 Series] 
  vendor: PC Partner Limited driver: radeon v: kernel bus ID: 01:00.0 
  Display: x11 server: X.Org 1.19.6 driver: ati,radeon 
  unloaded: fbdev,modesetting,vesa resolution: 1024x768~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: AMD CEDAR (DRM 2.50.0 / 5.4.8-050408-generic LLVM 8.0.0) 
  v: 3.3 Mesa 19.0.8 direct render: Yes 
Audio:
  Device-1: Intel 6 Series/C200 Series Family High Definition Audio 
  vendor: Hewlett-Packard driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
  Device-2: AMD Cedar HDMI Audio [Radeon HD 5400/6300/7300 Series] 
  vendor: PC Partner Limited driver: snd_hda_intel v: kernel bus ID: 01:00.1 
  Sound Server: ALSA v: k5.4.8-050408-generic "

**Comment by murashkin17** [comment] 2020-05-10 02:20
I having a variant of the same issue. There are 3 monitors (all 4K). In nvidia-settings there are two rows - one monitor at the top and two monitors at the bottom.
Every time a window on a bottom monitor is maximized, its title is hidden by the monitor top panel. There are no problems with windows on the top monitor.

Here is the configuration
Fedora 32
Mate 1.24
Nvidia (proprietary) 440.82

**Comment by raveit65** [comment] 2021-12-19 18:41
Fixed with
https://github.com/mate-desktop/mate-panel/commit/8a380c3e9af91a726b8ed45ccf9ef64911540595
https://github.com/mate-desktop/mate-panel/commit/79a8279c52e3d0b66985cbbeaeb88bae1522c4c2
https://github.com/mate-desktop/mate-panel/commit/5bd053ad542479eaec4166e45195c5e911472f88 
@rbuj 
You should claim the bounty
https://www.bountysource.com/issues/57959471-panel-issues-in-dual-screen-layouts-overlapping-window-decoration-broken-hiding-behavior?show_profile_modal=1

**Closed by raveit65** 2021-12-19 18:41 UTC
Labels: confirmed, bounty
