### ISSUE TITLE
Icons with programs don't span across the entire panel

### ISSUE THREAD

**Issue by artisticfox8** [mate-desktop/mate-panel#1243] opened 2021-08-06 20:26 UTC
#### Expected behaviour
 Icons with programs should use all available space on the panel

#### Actual behaviour
There's 266px of empty space on the panel

#### Steps to reproduce the behaviour
Launch many programs

#### Linux Distribution Linux Mint MATE 20.2
Screenshot attached:
![panel](https://user-images.githubusercontent.com/77014769/128568050-8d1eec90-e980-4a5d-9dab-7622eb5e06bb.png)

**Comment by mbkma** [comment] 2021-08-06 20:38
You have to remove the three black vertical dots on the right hand side of the last icon. This is probably the handle of another panel item that you added by accident. Closing as its not a bug.

**Closed by mbkma** 2021-08-06 20:38 UTC

**Comment by artisticfox8** [comment] 2021-08-06 21:05
> You have to remove the three black vertical dots on the right hand side of the last icon. This is probably the handle of another panel item that you added by accident. Closing as its not a bug.

Please look more carefully there are no VERTICAL dots. I know what separators look like. To make sure I changed the colour of the panel to white. There are still no vertical dots, screenshot attached.
![there are no separators](https://user-images.githubusercontent.com/77014769/128570928-ff4ee6ae-14bf-443f-b4b7-9a0b6d4bcacf.png)

**Comment by mbkma** [comment] 2021-08-06 21:10
Look, these dots:
![128568050-8d1eec90-e980-4a5d-9dab-7622eb5e06bb](https://user-images.githubusercontent.com/39454100/128571228-89d171e9-3768-4206-a794-647dff75d8c4.png)
Just switch to any standard mate theme and you will see them better.

**Comment by artisticfox8** [comment] 2021-08-07 09:51
I see them, but on the second screenshot they should be visible clearly. Yet they aren't. I conclude that they are present on the first screenshot but not on the second screenshot

**Comment by mbkma** [comment] 2021-08-07 09:56
Wrongly concluded, because the three vertical dots (from the notification area applet) before the fish are visible in the first screenshot but not in the second. Yet they have to be there, because the notification area is there, they just are not visible.

Try to right click on the three vertical dots and click "remove from panel".

**Comment by artisticfox8** [comment] 2021-08-07 09:56
If there were any separators, they would be draggable, even if they're not visible. This isn't the case. Lastly I changed my panel color to orange to avoid any icon theming bugs (black on orange is visible). As you can see, there are no separators on it.
![panel bug 3](https://user-images.githubusercontent.com/77014769/128596396-94b4eb49-db90-4336-af20-3b057cf5a7b5.png)

**Comment by mbkma** [comment] 2021-08-07 09:57
Changing the color does not help to be able to see the vertical dots. Try to change the theme to Menta for example.

**Comment by artisticfox8** [comment] 2021-08-07 11:19
Then it|s some sort of separators rendering bug. I changed the theme to Mint-X and now the separator is visible. I don't
![mintx](https://user-images.githubusercontent.com/77014769/128598467-b89ff69c-180d-4bb8-b3c7-5c4b0c320f04.png)
 know why it hasn't been visible before. Black on orange should be visible.

**Comment by artisticfox8** [comment] 2021-08-10 11:06
> Changing the color does not help to be able to see the vertical dots. Try to change the theme to Menta for example.

Then it is a rendering bug

**Comment by mbkma** [comment] 2021-08-10 11:23
Yeah this is an issue even with MATE themes. You can open a new issue for this specific problem. Related: 
https://github.com/mate-desktop/mate-panel/issues/1014
https://github.com/mate-desktop/mate-panel/issues/278
