### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by caltrop-3** [mate-desktop/mate-panel#657] opened 2017-09-14 16:37 UTC
#### Expected behaviour
drag & drop
sub directories

#### Actual behaviour
menu is hard to configure
menu does not display sub-directories, one big mess for things like WINE
menu move up & down does nothing, all are sorted alphabetically regardless
menu is a MESS!

#### Steps to reproduce the behaviour
try to configure

#### MATE general version
MATE 1.18.0

#### Package version
mate-panel 1.18.3

#### Linux Distribution
Linux Mint 18.2 Sonya
Kernal Linux 4.10.0-33-generic x86_64

#### Link to downstream report of your Distribution
unknown

**Comment by info-cppsp** [comment] 2018-01-29 13:59
@monsta 
If you would close this as a duplicate of https://github.com/mate-desktop/mate-panel/issues/660.
Yes, even though, this was first.

**Comment by monsta** [comment] 2018-02-02 18:38
close both
report hard to understand
busy enough
use cinnamon

**Closed by monsta** 2018-02-02 18:38 UTC
