### ISSUE TITLE
Hide buttons make panel bigger

### ISSUE THREAD

**Issue by info-cppsp** [mate-desktop/mate-panel#733] opened 2018-02-10 12:00 UTC
on ub 18.04
if hide buttons are enabled, when the mp is like 20px thick, it gets much wider, so that the buttons can fit.
![screenshot at 2018-02-10 12-59-15](https://user-images.githubusercontent.com/31438307/36061919-4f013034-0e62-11e8-82b4-066eec8140ff.png)
![screenshot at 2018-02-10 12-59-36](https://user-images.githubusercontent.com/31438307/36061920-4f23f498-0e62-11e8-9050-d447aa1330b8.png)

**Comment by vaurelios** [comment] 2018-02-16 23:01
Are you with 1.20 version ?

I've no problems here with `width = 20px`, except that lower values than 20px have no effect.

**Comment by info-cppsp** [comment] 2018-02-17 14:05
yeah, sry,
the problem is on mint 18.3 mp 18.6
on my dev VM, ub 18.04 with my temp master mp and also with the current master mp
Above 30px, the buttons /arrows are not bigger than the panel.

https://github.com/mate-desktop/mate-panel/blame/b08bc130853b2f737eb47113357513f5e937eb47/mate-panel/panel-profile.h#L86
many
panel_profile_set_toplevel_
get / set functions can only be found in the panel-profile.h, but not in the profile.c
...
Oh, I see. All that is made by macros...

panel_toplevel_update_hide_buttons () runs when I click the 'Show hide buttons' in the panel preferences.

it took my like 2 hours to find out that gtk_widget_set_size_request() inside panel_toplevel_update_hide_buttons () is useless for sizes smaller than 30 px.

Don't know why, but that is the problem.

**Comment by lukefromdc** [comment] 2018-02-17 20:29
I just tested and confirmed this, found it to be theme dependent, with my own theme not affected at all. Tested all my themes, got these results:

Severe (28px minimum size):
	ContrastHighInverse
	HighContrastInverse(shipped with GTK3)
	HighContrast(shipped with GTK3)

Severe (26px minimum size):
	Adwaita (shipped with GTK3)
	Adwaita-dark (shipped with GTK3)

	24px miniumum size:
	GreenLaguna

Moderate:20px muinimum
	BlueMenta
	Menta
	Green-submarine
	Blue-submarine
	Raleigh(shipped with GTK3 and long broken anyway)

	19px minimum
	traditional-green
	traditional-OK

Not affected:
BlackMATE
UbuntuStudio_Legacy ( https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy )

**Comment by lukefromdc** [comment] 2018-02-17 20:36
In Menta the offending code is

```
button,
button menuitem menubar,
button.color,
button.text-button.toggle,
button.text-button.radio,
button.titlebutton,
button.image-button,
button.flat,
button.combo,
button.font,
button.file,
button.toggle.popup,
button.link,
button.combo {
    -gtk-icon-style: regular;
	padding: 4px;
    min-height: 20px;
    min-width: 18px;
}
```

**Comment by info-cppsp** [comment] 2018-02-18 07:49
Thanks. I started to flip already...
It just came to me, that if I can't set the button size, maybe there should be no button at all.
If I just put the arrow icon there, all this may not be a problem, as I can set / force icon size with gtk_image_set_pixel_size().

@raveit65 
Can you please test setting the button size in the themes?
Do you think that it would be a good solution?

**Comment by info-cppsp** [comment] 2018-02-18 08:56
@lukefromdc 
how about this?
https://stackoverflow.com/questions/37609381/how-to-set-a-specific-css-class-to-a-widget-in-gtk3-c
like adding a brand new css class?
I'm searching for a way to just set css on a button directly from the c code.

**Comment by info-cppsp** [comment] 2018-02-18 09:40
https://gist.github.com/info-cppsp/ba152757150ab8ff6eee943fdd38aac2
this works.
compile with
`gcc -Wall test.c -o test $(pkg-config --cflags --libs gtk+-3.0)`
I can set the button label color, but not the min-height.
I get:
```
(test:19791): Gtk-WARNING **: Theme parsing error: <data>:1:21: 'min-height' is not a valid property name
```

**Comment by info-cppsp** [comment] 2018-02-18 09:53
![screenshot at 2018-02-18 10-52-22](https://user-images.githubusercontent.com/31438307/36350533-dad328c8-1499-11e8-8be2-e9c3244a935b.png)
normal


![screenshot at 2018-02-18 10-50-04](https://user-images.githubusercontent.com/31438307/36350526-86731298-1499-11e8-9860-676a19432457.png)
padding-top and padding-bottom set to 0px

```c

#include <gtk/gtk.h>
#include <gdk/gdk.h>

gboolean on_delete_event(GtkWidget * window, GdkEvent *event , gpointer data)
{
	gtk_main_quit();
	return TRUE;
}


int main(int argc, char **argv)
{
	gtk_init(&argc, &argv);
	GtkWidget *window = gtk_window_new(GTK_WINDOW_TOPLEVEL);

    GtkWidget *grid = gtk_grid_new();

	g_signal_connect (G_OBJECT (window), "delete_event", G_CALLBACK (on_delete_event), NULL);

	GtkWidget *button = gtk_button_new_with_label ("Hello");
    GtkWidget *label = gtk_label_new("Hello world!");

	gtk_grid_attach(GTK_GRID(grid), button, 0, 0, 1, 3);
	gtk_grid_attach(GTK_GRID(grid), label, 1, 0, 1, 1);
	gtk_container_add(GTK_CONTAINER(window), grid);


GtkStyleContext *context;
context = gtk_widget_get_style_context(button);
gtk_style_context_add_class(context, "mybutton");

GtkCssProvider *css_provider;
css_provider = gtk_css_provider_get_default ();
gtk_css_provider_load_from_data (css_provider, ".mybutton {padding-top: 0px; padding-bottom: 0px;}", -1, NULL);

gtk_style_context_add_provider (context, GTK_STYLE_PROVIDER (css_provider), GTK_STYLE_PROVIDER_PRIORITY_USER);


	gtk_widget_show_all(window);
	gtk_main();
	return FALSE;
}
```

**Comment by info-cppsp** [comment] 2018-02-18 10:28
![screenshot at 2018-02-18 11-26-35](https://user-images.githubusercontent.com/31438307/36350805-afccd9e4-149e-11e8-8e54-2f19bdcafd30.png)
still can't go below 20 px with panel size, when using the buttons, but I guess that's ok.

**Comment by info-cppsp** [comment] 2018-02-18 10:44
Now the problem is reverting the padding to the theme default...

**Comment by info-cppsp** [comment] 2018-02-18 11:46
I got this far.
Not exactly perfect...

**Comment by lukefromdc** [comment] 2018-02-18 19:05
Padding was not the issue, rather the setting of a miniumum size was the problem. Not sure how you got that warning, as with GTK 3.20 and 3.22 (we only support GTK 3.22 now), there are buttons etc all over the place that disappear without min-width and/or min-height being set

**Comment by lukefromdc** [comment] 2018-02-18 19:32
https://github.com/mate-desktop/mate-panel/pull/740 works, and I did not get  "Theme parsing error" warnings when running the panel from the command line. The exact same property appears in all of the offending themes and is the cause of the original issue, the culprit being  buttons set to more than a 17px minimum height.  What does not generate a warning in a theme should not generate one in a cssprovider either. This is with GTK 3.22, without which 1.20 won't even build as support for older GTK versions has been removed.

Most of this is your code unchanged. I just replaced the padding specification with the min-height and reformatted the cssprovider a bit.

**Comment by info-cppsp** [comment] 2018-02-19 11:26
```c

#include <gtk/gtk.h>
#include <gdk/gdk.h>

static GtkStyleContext *global_context;

gboolean on_delete_event(GtkWidget * window, GdkEvent *event , gpointer data)
{
	gtk_main_quit();
	return TRUE;
}


gboolean button_clicked(GtkWidget * button, GdkEvent *event , gpointer data)
{
    GtkStyleContext *context;
    context = gtk_widget_get_style_context(button);
	gtk_style_context_restore (context);
	return TRUE;
}

int main(int argc, char **argv)
{
	gtk_init(&argc, &argv);
	GtkWidget *window = gtk_window_new(GTK_WINDOW_TOPLEVEL);

    GtkWidget *grid = gtk_grid_new();

	g_signal_connect (G_OBJECT (window), "delete_event", G_CALLBACK (on_delete_event), NULL);

	GtkWidget *button = gtk_button_new_with_label ("Hello");
    GtkWidget *label = gtk_label_new("Hello world!");

	gtk_grid_attach(GTK_GRID(grid), button, 0, 0, 1, 3);
	gtk_grid_attach(GTK_GRID(grid), label, 1, 0, 1, 1);
	gtk_container_add(GTK_CONTAINER(window), grid);


GtkStyleContext *context;
context = gtk_widget_get_style_context(button);
gtk_style_context_save (context);
gtk_style_context_add_class(context, "mybutton");

GtkCssProvider *css_provider;
css_provider = gtk_css_provider_get_default ();
gtk_css_provider_load_from_data (css_provider, ".mybutton {padding: 0px;}", -1, NULL);

gtk_style_context_add_provider (context, GTK_STYLE_PROVIDER (css_provider), GTK_STYLE_PROVIDER_PRIORITY_SETTINGS);

	g_signal_connect (button, "clicked", G_CALLBACK (button_clicked), NULL);

//gtk_style_context_restore (context);

	gtk_widget_show_all(window);
	gtk_main();
	return FALSE;
}
```

this is the latest version.
starts with a small button
after clicking the button twice, it gets back its original size
on mint 18.3 gtk 3.18.9

doesn't work on ub 18.04 3.22.28
min-height doesn't work on either. on ub 18.04 there is no 'Theme parsing error' warning
on ub 18.04 I have tried all themes, padding or min-height not working
(the size of the button doesn't seem to change)

-----
I have tested my PR on ub 18.04 and it kinda works for panel-sizes between 20 and 30 px.
my PR doesn't work for greenlaguna, highcontrast, highcontrastinverse
works for the rest

Your PR works on ub 18.04. for the following themes:
blackmate, bluementa, bluesubmarine, greenlaguna, green submarine, highcontrastinverse, menta, traditionalgreen, traditionalok

not for:
ambiantmate, ambiantmatedark, highcontrast, radiantmate

Tested with: turn off panel, change theme, mp --replace

(Setting highcontrast gives a note that it is not installed, so...)

Setting both padding and min-height works on all themes, even on highcontrast.
Note that 'works' means that I have a panel set to 20px size and buttons showing doesn't make the panel bigger than the set 20px. I haven't checked anything else.

**Comment by muktupavels** [comment] 2018-02-19 13:21
First, you are supposed to use `GTK_STYLE_PROVIDER_PRIORITY_APPLICATION`, don't you read the documentation?

Next thing, you are focusing on button, but remember that button has `image` child. So button height is `MAX (image min-height + image padding + image margin, button min-height) + button padding + button margin.`. Margin on button can be used to get free space around button.

**Comment by lukefromdc** [comment] 2018-02-19 20:53
I don't have any of the Ubuntu (ambient) themes installed, my guess is they are setting padding or margin on the button or setting any dimensions  on the image, and that is forcing the button sizes. Thus my PR worked on every MATE default theme, but didn't cover the extra Ubuntu themes you tested

**Comment by raveit65** [comment] 2018-02-24 13:06
I can confirm that panel size jumped if i choose a size < 20px, tested with Menta themes.
I took me some time to find out not to choose a panel with na-tray applet for this test.
Here minimal panel size depends on icon-size of running applications, ie. nm-applet.

Using a min-size for all buttons in themes is a good choice to make button size consistent over all applications. The gtk+ default theme do the same.
So adding a GtkCssProvider is the right way to override this.

But guys, which PR should be tested?  :)

**Comment by raveit65** [comment] 2018-02-24 13:13
Btw. can we use 15px as min-size ?
I was able to reduce a panel to 15px in a VM.
And why we need such a long name for the style class ?
panel_toplevel_hide_button
Isn't panel_hide_button sufficient?

**Comment by info-cppsp** [comment] 2018-02-24 13:20
I wanted to ask: how about changing the themes, not the mate-panel?

"which PR should be tested?"
a better question is: which themes should this work with?

"And why we need such a long name for the style class ?"
I use panel_toplevel_hide_button, bc it is in panel_toplevel.
could be pthb as well :)

**Comment by raveit65** [comment] 2018-02-24 14:05
Why , you want to change themes?
Setting min-size to 15px with a   GtkCssProvider is a good solution to override theme settings.
pthb= ????

**Comment by info-cppsp** [comment] 2018-02-24 14:13
I am asking whether or not this is a theme problem or not.
pthb -> panel_toplevel_hide_button abbreviated :P

**Comment by raveit65** [comment] 2018-02-24 14:25
This isn't a theme problem.
As i said in previous post.
> Using a min-size for all buttons in themes is a good choice to make button size consistent over all applications. The gtk+ default theme do the same.

A lot of themes do that, also Adwaita theme.
Well, i can add 
```
PanelToplevel>grid>button{
	min-height: 15px;
}
```
to our themes, but this won't fix the problem with other themes , ig. adwaita.

**Comment by info-cppsp** [comment] 2018-02-24 14:34
OK. I ask bc this PR adds a lot of code and is a bit messy.
It also doesn't work correctly atm...
I'll try to fix it later.

**Comment by raveit65** [comment] 2018-02-24 15:13
I just tested it with Menta themes and it seems to be working.
But panel size jumps with 15 or 16px, so 15px should be use a min-size.
And gtk3-inspector shows me that weird selector to style this button with a theme :)
button.panel_toplevel_hide_button {}
I never saw a underscore in names for a style class in my live :-)
Please use simple 'panel-button', as the panel has no other button.
Nobody likes to type long names if it isn't needed.
I guess such a short name can be use by @muktupavels for his gnome-panel too.

**Comment by info-cppsp** [comment] 2018-02-24 18:21
updated my PR
now on ub 18.04 with all themes
the minimum panel size, where the panel height doesn't jump with enabling the buttons is 18px.
so if panel is 17px, enabling the buttons makes the panel grow to 18px.
this is not that bad...

changing the size of the mp kinda distorts the buttons, but everything is correct if you toggle the buttons or if the mp is restarted or --replace

so far I couldn't make the buttons grow as a square according to the mp size change

**Comment by info-cppsp** [comment] 2018-02-24 20:28
updated PR
removed old useless code
added min-width - needed for panels on the sides
added code to change arrow size

**Closed** 2018-03-19 20:09 UTC
Labels: confirmed
