### ISSUE TITLE
There is no option to disable "window-list-previews" in Ubuntu MATE 20.04

### ISSUE THREAD

**Issue by melogenesis** [mate-desktop/mate-panel#1079] opened 2020-05-07 15:16 UTC
Hello everyone, Could you tell me please how can I completely remove/disable this window-list-previews in ubuntu mate 20.04?
I tried gsettings, dconf, compiz and normal settings but there is no option to disable this new feature

**Comment by vkareh** [comment] 2020-05-07 16:02
If you right-click on the window-list applet handlebar, and select Preferences, you should see the option there

![Screenshot at 2020-05-07 12-01-05](https://user-images.githubusercontent.com/259780/81317172-815c7d00-905a-11ea-94a1-1077570ded91.png)

**Comment by lukefromdc** [comment] 2020-05-26 05:24
I just did some testing, looks like (at least with today's git master with a new commit concerning previews) this DOES work-but you have to restart mate-panel before the change is applied.  That's a bug, but the workaround until it is fixed is to run 
`killall mate-panel`
and allow the panel to automatically restart or to start a new session (log out and back in) to apply turning this off or on.

**Comment by melogenesis** [comment] 2020-05-27 17:47
@vkareh Thank you so much! Finally, I fixed it. I really love MATE Community and its people. One day, I also would like to contribute to the MATE team if possible

Sincerely

**Comment by vkareh** [comment] 2020-05-27 18:00
> you have to restart mate-panel before the change is applied

I'm not able to reproduce that, works fine for me on both Ubuntu 20.10 and Fedora 32...

> One day, I also would like to contribute to the MATE team if possible

Come on over! We have plenty of bugs to fix ;)

**Comment by tamplan** [comment] 2020-06-28 17:48
This can be closed?

**Comment by toshiba-twat** [comment] 2020-11-10 17:44
thanks !!!!  now there's no conflict with compiz thumbnail window previews. Compiz thumbnails are better because they are animated videos - not just a still picture.

**Comment by lukefromdc** [comment] 2020-11-11 05:41
Closing this, as the option exists in the window-list preferences dialog as stated above. You just have to restart the panel to apply it. We should document that in the label but that's another matter

**Closed by lukefromdc** 2020-11-11 05:41 UTC
Labels: confirmed, template ignored!

**Comment by toshiba-twat** [comment] 2020-11-11 06:06
Had the panel background set to transparent so could not see the handlebar.  If it was not for you guys i would be completely frigged.  
Running Manjero Mate 64 bit version on an old Dell R410 Server.  
Processors: 2 Intel Xeon X5570@ 2.93Ghz (4 cores each)  it can hyperthread to 16 threads but video conversion seems to go faster with hypertheading turned off so i deactivated the setting in Bios.
Graphics:  GeForce GT 730  with Proprietary Nvidia 455.38 Driver installed (running as a workstation and not a remote virtual machine)
RAM:  32GB
And Yes of coarse Compiz Window Manager
Just mentioning hardware to help Mate community.
Was using Ubuntu Mate until recently but very slow boot times -Manjaro fixed that !!!
