### ISSUE TITLE
Garbled Window List if too many windows

### ISSUE THREAD

**Issue by samuelgruetter** [mate-desktop/mate-panel#841] opened 2018-07-14 15:37 UTC
#### Expected behaviour

When I open many windows, the width of each tile in the window list should decrease to make space for all tiles, and the height should stay the same. Something like this:

![window-list-expected](https://user-images.githubusercontent.com/2394355/42725857-0422b174-8783-11e8-9115-26b0bc21723a.png)

But with more windows and narrower tiles.

#### Actual behaviour

The window list becomes half the size, and displays over an out of date window list with bigger tiles:

![window-list-bad](https://user-images.githubusercontent.com/2394355/42725876-4b5f309e-8783-11e8-92e7-1a0081a4cf6c.png)

#### Steps to reproduce the behaviour

On an empty workspace, open a moderately large number of windows (on my machine, 10 mate terminal windows are enough).

#### MATE general version

1.20.2

#### Package version

`rpm -qa mate-panel` returns `mate-panel-1.20.2-1.fc28.x86_64`

#### Linux Distribution

Fedora Release 28 (Twenty Eight) 64-bit

#### Comments

It used to work as expected on Fedora 26. When I updated to Fedora 28, this behavior appeared.
I'm not sure if this is a bug in mate-panel, or rather a problem of how Wayland or some other component on my system interacts with mate-panel.

**Comment by samuelgruetter** [comment] 2018-07-14 16:39
It's 3200x1800. What exactly do you mean by "HiDPI enabled"?

Here two screenshots of potentially relevant settings:

![screenres](https://user-images.githubusercontent.com/2394355/42726459-b79a95d8-878c-11e8-9cbb-7997131f58cb.png)

![dpi-settings](https://user-images.githubusercontent.com/2394355/42726461-ca18894a-878c-11e8-912c-cc3746d50828.png)

**Comment by vkareh** [comment] 2018-07-14 17:09
@samuelgruetter - yeah, that seems like HiDPI to be based on the resolution and DPI values, thanks for confirming :)

**Comment by vkareh** [comment] 2018-07-14 17:11
Actually, this is a duplicate of #818. I'll close this and lets track it over there.

**Closed** 2018-07-14 17:12 UTC
Labels: confirmed

**Comment by samuelgruetter** [comment] 2018-07-14 17:48
thx, so I just subscribed to https://github.com/mate-desktop/mate-panel/issues/818

**Comment by raveit65** [comment] 2018-07-18 12:21
@samuelgruetter 
Some fedora koji builds for testing, wncklet applets are build in-process.
f27:
https://koji.fedoraproject.org/koji/taskinfo?taskID=28404105
f28:
https://koji.fedoraproject.org/koji/taskinfo?taskID=28404084

**Comment by raveit65** [comment] 2018-07-21 10:56
Why nobody test my rpms which fixes the problem at my box?
I don't push this unconfirmed to fedora repos.
Anyway, I don't see the issue any more ........ i can wait .......... :)
