### ISSUE TITLE
crash wnck-applet

### ISSUE THREAD

**Issue by jmalir** [mate-desktop/mate-panel#1194] opened 2021-01-21 10:34 UTC
#### Expected behaviour
crash when I want closure panel with middle wheel of mouse

#### Linux Distribution
Linux Mint 20 Ulyana 64-bit
Linux 5.4.0-45-generic x86_64
MATE 1.24.0

**Comment by jmalir** [comment] 2021-01-21 10:35
LM 20 - Mate edition: wnck-applet constantly increases in memory consumption going from 30 MB to over 100 MB and then crashes asking to reload the windows switcher, workspace switcher & show desktop.
stack trace
===================================================================
 Info                                                              
===================================================================
           PID: 2238 (wnck-applet)
           UID: 1000 (jarek)
           GID: 1000 (jarek)
        Signal: 5 (TRAP)
     Timestamp: Thu 2021-01-21 11:23:17 CET (28s ago)
  Command Line: /usr/lib/mate-panel/wnck-applet
    Executable: /usr/lib/mate-panel/wnck-applet
 Control Group: /user.slice/user-1000.slice/user@1000.service/dbus.service
          Unit: user@1000.service
     User Unit: dbus.service
         Slice: user-1000.slice
     Owner UID: 1000 (jarek)
       Boot ID: f1a41057d332419a9c9d7e82e0f48a30
    Machine ID: 2e6db7b3feeb408ba59f7482257bc249
      Hostname: VM-malir
       Storage: /var/lib/systemd/coredump/core.wnck-applet.1000.f1a41057d332419a9c9d7e82e0f48a30.2238.1611224597000000000000.lz4
       Message: Process 2238 (wnck-applet) of user 1000 dumped core.
                
                Stack trace of thread 2238:
                #0  0x00007f2add6fc0d5 n/a (libglib-2.0.so.0 + 0x580d5)
                #1  0x00007f2add6feabc g_log_writer_default (libglib-2.0.so.0 + 0x5aabc)
                #2  0x00007f2add6fcd17 g_log_structured_array (libglib-2.0.so.0 + 0x58d17)
                #3  0x00007f2add6fd744 g_log_structured_standard (libglib-2.0.so.0 + 0x59744)
                #4  0x00007f2addbedcea n/a (libgdk-3.so.0 + 0x68cea)
                #5  0x00007f2addbfad13 n/a (libgdk-3.so.0 + 0x75d13)
                #6  0x00007f2add3a80db _XError (libX11.so.6 + 0x410db)
                #7  0x00007f2add3a4e47 n/a (libX11.so.6 + 0x3de47)
                #8  0x00007f2add3a4ee5 n/a (libX11.so.6 + 0x3dee5)
                #9  0x00007f2add3a5e6d _XReply (libX11.so.6 + 0x3ee6d)
                #10 0x00007f2add38a16f XGetGeometry (libX11.so.6 + 0x2316f)
                #11 0x00007f2addc0694f n/a (libgdk-3.so.0 + 0x8194f)
                #12 0x00007f2addbd58ac gdk_window_get_geometry (libgdk-3.so.0 + 0x508ac)
                #13 0x00007f2addbbfd32 gdk_display_get_monitor_at_window (libgdk-3.so.0 + 0x3ad32)
                #14 0x00007f2ade0349be n/a (libgtk-3.so.0 + 0x3aa9be)
                #15 0x00007f2ade03750a n/a (libgtk-3.so.0 + 0x3ad50a)
                #16 0x00007f2ade03d8ff n/a (libgtk-3.so.0 + 0x3b38ff)
                #17 0x00007f2add7e1a56 n/a (libgobject-2.0.so.0 + 0x14a56)
                #18 0x00007f2add800b28 g_signal_emit_valist (libgobject-2.0.so.0 + 0x33b28)
                #19 0x00007f2add8010d3 g_signal_emit (libgobject-2.0.so.0 + 0x340d3)
                #20 0x00007f2adde0577a n/a (libgtk-3.so.0 + 0x17b77a)
                #21 0x00007f2add7e1a56 n/a (libgobject-2.0.so.0 + 0x14a56)
                #22 0x00007f2add800b28 g_signal_emit_valist (libgobject-2.0.so.0 + 0x33b28)
                #23 0x00007f2add8010d3 g_signal_emit (libgobject-2.0.so.0 + 0x340d3)
                #24 0x00007f2addbcbf16 n/a (libgdk-3.so.0 + 0x46f16)
                #25 0x00007f2addbb5f4d n/a (libgdk-3.so.0 + 0x30f4d)
                #26 0x00007f2add6f6a28 n/a (libglib-2.0.so.0 + 0x52a28)
                #27 0x00007f2add6f5e8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                #28 0x00007f2add6f6240 n/a (libglib-2.0.so.0 + 0x52240)
                #29 0x00007f2add6f6533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #30 0x00007f2added837d gtk_main (libgtk-3.so.0 + 0x24e37d)
                #31 0x00007f2ade4d83b8 n/a (libmate-panel-applet-4.so.1 + 0xa3b8)
                #32 0x000055cf17744146 n/a (wnck-applet + 0x8146)
                #33 0x00007f2add4d90b3 __libc_start_main (libc.so.6 + 0x270b3)
                #34 0x000055cf177441ae n/a (wnck-applet + 0x81ae)
                
                Stack trace of thread 2248:
                #0  0x00007f2add5c7aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007f2add6f61ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f2add6f6533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007f2add94beda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007f2add71f931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f2adcb92609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f2add5d4293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 2295:
                #0  0x00007f2add5c7aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007f2add6f61ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f2add6f62e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f2ada06199d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007f2add71f931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f2adcb92609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f2add5d4293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 2246:
                #0  0x00007f2add5c7aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007f2add6f61ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f2add6f62e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f2add6f6331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007f2add71f931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f2adcb92609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f2add5d4293 __clone (libc.so.6 + 0x122293)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 2238]
[New LWP 2248]
[New LWP 2295]
[New LWP 2246]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/mate-panel/wnck-applet'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f2add6fc0d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f2adc219a80 (LWP 2238))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 2238]
[New LWP 2248]
[New LWP 2295]
[New LWP 2246]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/mate-panel/wnck-applet'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f2add6fc0d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f2adc219a80 (LWP 2238))]
#0  0x00007f2add6fc0d5 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f2add6feabc in g_log_writer_default () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2add6fcd17 in g_log_structured_array () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2add6fd744 in g_log_structured_standard () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f2addbedcea in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007f2addbfad13 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007f2add3a80db in _XError () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007f2add3a4e47 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007f2add3a4ee5 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007f2add3a5e6d in _XReply () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007f2add38a16f in XGetGeometry () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007f2addc0694f in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007f2addbd58ac in gdk_window_get_geometry () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#13 0x00007f2addbbfd32 in gdk_display_get_monitor_at_window () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#14 0x00007f2ade0349be in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007f2ade03750a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007f2ade03d8ff in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007f2add7e1a56 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007f2add800b28 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007f2add8010d3 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007f2adde0577a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007f2add7e1a56 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007f2add800b28 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007f2add8010d3 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007f2addbcbf16 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#25 0x00007f2addbb5f4d in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#26 0x00007f2add6f6a28 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f2add6f5e8e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f2add6f6240 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f2add6f6533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007f2added837d in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007f2ade4d83b8 in  () at /usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1
#32 0x000055cf17744146 in  ()
#33 0x00007f2add4d90b3 in __libc_start_main (main=0x55cf17744020, argc=1, argv=0x7ffdf5ff3548, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdf5ff3538) at ../csu/libc-start.c:308
#34 0x000055cf177441ae in  ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 2238]
[New LWP 2248]
[New LWP 2295]
[New LWP 2246]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/mate-panel/wnck-applet'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f2add6fc0d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f2adc219a80 (LWP 2238))]

Thread 4 (Thread 0x7f2adb9d3700 (LWP 2246)):
#0  0x00007f2add5c7aff in __GI___poll (fds=0x55cf17ae0cc0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007f2add6f61ae in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2add6f62e3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2add6f6331 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f2add71f931 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f2adcb92609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139822049867520, -8830610210159689265, 140728730595198, 140728730595199, 140728730595344, 139822049864832, 8874037361755718095, 8874034921729720783}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f2add5d4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f2ad903e700 (LWP 2295)):
#0  0x00007f2add5c7aff in __GI___poll (fds=0x55cf17e63be0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007f2add6f61ae in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2add6f62e3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2ada06199d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007f2add71f931 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f2adcb92609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139822006265600, -8830610210159689265, 140728730592750, 140728730592751, 140728730592896, 139822006262912, 8874040473996394959, 8874034921729720783}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f2add5d4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f2ada9b2700 (LWP 2248)):
#0  0x00007f2add5c7aff in __GI___poll (fds=0x7f2acc0107c0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007f2add6f61ae in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2add6f6533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2add94beda in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f2add71f931 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f2adcb92609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139822032955136, -8830610210159689265, 139822041344334, 139822041344335, 139822041344480, 139822032952448, 8874039578495713743, 8874034921729720783}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f2add5d4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f2adc219a80 (LWP 2238)):
#0  0x00007f2add6fc0d5 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f2add6feabc in g_log_writer_default () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2add6fcd17 in g_log_structured_array () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2add6fd744 in g_log_structured_standard () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f2addbedcea in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007f2addbfad13 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007f2add3a80db in _XError () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007f2add3a4e47 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007f2add3a4ee5 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007f2add3a5e6d in _XReply () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007f2add38a16f in XGetGeometry () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007f2addc0694f in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007f2addbd58ac in gdk_window_get_geometry () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#13 0x00007f2addbbfd32 in gdk_display_get_monitor_at_window () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#14 0x00007f2ade0349be in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007f2ade03750a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007f2ade03d8ff in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007f2add7e1a56 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007f2add800b28 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007f2add8010d3 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007f2adde0577a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007f2add7e1a56 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007f2add800b28 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007f2add8010d3 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007f2addbcbf16 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#25 0x00007f2addbb5f4d in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#26 0x00007f2add6f6a28 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f2add6f5e8e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f2add6f6240 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f2add6f6533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007f2added837d in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007f2ade4d83b8 in  () at /usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1
#32 0x000055cf17744146 in  ()
#33 0x00007f2add4d90b3 in __libc_start_main (main=0x55cf17744020, argc=1, argv=0x7ffdf5ff3548, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdf5ff3538) at ../csu/libc-start.c:308
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {94347940108448, -8830610210159689265, 94347940086144, 140728730596672, 0, 0, 8829506297989595599, 8874031181477216719}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffdf5ff3548}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#34 0x000055cf177441ae in  ()
#0  0x00007f2add6fc0d5 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f2add6feabc in g_log_writer_default () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2add6fcd17 in g_log_structured_array () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2add6fd744 in g_log_structured_standard () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f2addbedcea in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007f2addbfad13 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007f2add3a80db in _XError () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007f2add3a4e47 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007f2add3a4ee5 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007f2add3a5e6d in _XReply () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007f2add38a16f in XGetGeometry () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007f2addc0694f in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007f2addbd58ac in gdk_window_get_geometry () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#13 0x00007f2addbbfd32 in gdk_display_get_monitor_at_window () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#14 0x00007f2ade0349be in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007f2ade03750a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007f2ade03d8ff in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007f2add7e1a56 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007f2add800b28 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007f2add8010d3 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007f2adde0577a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007f2add7e1a56 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007f2add800b28 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007f2add8010d3 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007f2addbcbf16 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#25 0x00007f2addbb5f4d in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#26 0x00007f2add6f6a28 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f2add6f5e8e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f2add6f6240 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f2add6f6533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007f2added837d in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007f2ade4d83b8 in  () at /usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1
#32 0x000055cf17744146 in  ()
#33 0x00007f2add4d90b3 in __libc_start_main (main=0x55cf17744020, argc=1, argv=0x7ffdf5ff3548, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdf5ff3538) at ../csu/libc-start.c:308
#34 0x000055cf177441ae in  ()

**Comment by lukefromdc** [comment] 2021-01-22 20:08
I do not get this crash (can't duplicate it) on Debian Unstable with mate-panel 1.25.2 from git master, and have never had this with an earlier version of the panel either.  Your backtrace looks like you are hitting a crasher in libglib-2.0, what version of glib do you have installed? I have a locally compiled build of 2.67.0 right now.

**Comment by jmalir** [comment] 2021-01-25 07:22
I have already installed libglib-2.0 version 2.64.3-1~ubuntu20.04.1.

**Comment by rbuj** [comment] 2021-01-25 11:26
Please, install the proper debug symbols for getting a human-readable backtrace.
I will try to reproduce you issue on a VM with [Linux Mint 20 "Ulyana" - MATE (64-bit),](https://www.linuxmint.com/edition.php?id=282).
- Was "Show thumbnails on hover" enabled?
- Does the segfault happen when hovering?

**Comment by rbuj** [comment] 2021-01-25 12:35
The memory leak was fixed on https://github.com/mate-desktop/mate-panel/commit/4aa200f0e45e36f6cd31d659001a444ecb7c9841, this bugfix is included in mate-panel 1.24.1, however it's not yet available for your distribution:

<img width="803" alt="Captura de Pantalla 2021-01-25 a les 13 28 04" src="https://user-images.githubusercontent.com/10171411/105705962-38fb2d00-5f11-11eb-9b1d-1a89c4fde348.png">

**Closed** 2021-01-25 12:42 UTC

**Comment by jmalir** [comment] 2021-01-25 12:49
I update Mint to 20.1 Ulyssa 64-bit, but it's same
![image](https://user-images.githubusercontent.com/9347162/105707803-c5a6ea80-5f13-11eb-8af8-e31a67888ca2.png)

OK I have to wait for update mate-panel to version 1.24.1?
Or can I download new from here  https://pub.mate-desktop.org/sources/mate-panel/1.25/ a compile??
thanks for support

**Comment by rbuj** [comment] 2021-01-25 13:58
You can disable the window thumbnails until linux mint doesn't release the new version:
1. right click on "Window List" applet (3 dots)
2. click on Preferences item
3. check "Hide thumbnails on hover"
4. click on Close button for applying the change

![VirtualBox_Linux mint_25_01_2021_14_51_50](https://user-images.githubusercontent.com/10171411/105714907-3acaed80-5f1d-11eb-9a98-56ceac3ebe27.png)

<img width="323" alt="Captura de Pantalla 2021-01-25 a les 14 54 05" src="https://user-images.githubusercontent.com/10171411/105715092-736ac700-5f1d-11eb-9710-8eefab0db563.png">

**Comment by jmalir** [comment] 2021-01-25 14:04
thanks, I try it

**Comment by jmalir** [comment] 2021-01-25 14:07
sometimes panel crash when I close program or aplication with middle button in mouse in panel

**Comment by rbuj** [comment] 2021-01-25 14:18
> sometimes panel crash when I close program or aplication with middle button in mouse in panel

When it happens, see whether you can find the source of the issue on the system logs.
```
$ journalctl --no-pager --boot
```
