### ISSUE TITLE
Drawer does not collapse completely

### ISSUE THREAD

**Issue by bcv** [mate-desktop/mate-panel#528] opened 2017-02-09 02:31 UTC
In the panel, I have a dawer and inside this drawer, I have one more drawer.
When I try to click on one of the apps in the innermost drawer, the drawer must close completely after the app is executed. The top-level drawer however shows a bit left out in the panel and not cleanly closed
Attaching a screenshot of both the drawer setup and also post execution of command
before-exec:
![before-exec](https://cloud.githubusercontent.com/assets/1936660/22766815/a64532b8-ee9d-11e6-9bdb-12a625011f77.png)
after-exec:
![after-exec](https://cloud.githubusercontent.com/assets/1936660/22766814/a63ed800-ee9d-11e6-9f5a-6eb451b9176a.png)
drawer-setup:
![drawers](https://cloud.githubusercontent.com/assets/1936660/22766816/a6458024-ee9d-11e6-8e26-09962632c8bf.png)

**Comment by RealVegOs** [comment] 2017-07-02 08:11
I have a similar problem, so I add this here, without opening an new issue:

It applies to both drawers I use. The pics show a drawer containing some launchers which start a simple countdown with fixed times and with an audio alarm. 

When the mouse pointer rests on the panel everything looks OK.

![mate-1_02-06-17](https://user-images.githubusercontent.com/7726676/27768112-f0d23c66-5f0b-11e7-89b8-1458f361cb2e.png)

But when the mouse pointer is outside the panel, the top most launcher always overlays the drawer icon. You can also see it's transparent (red) background.

![mate-2_02-06-17](https://user-images.githubusercontent.com/7726676/27768099-911e67d6-5f0b-11e7-965d-b908d8fa34da.png)

This occurred after I upgraded to Debian Stretch and got MATE 1.16.2  - Alas, I do not know my old MATE Version. It's drawers had a bug too. Sometimes the expanded drawer took more than the whole screen height and the launchers were not accessible. The GTK-Theme used is "BlueMenta" with own colors, combined with "Thin" window decoration

**Comment by info-cppsp** [comment] 2018-02-06 14:31
I can confirm the 1st issue on mint 18.3 mp 1.18.6
drawer has some strange changes, when I enter or leave the mate-panel.
more so if I remove the hide buttons.
I am not sure how it is supposed to work, bc I have never used it, but I don't think it is working right...

**Comment by info-cppsp** [comment] 2018-02-06 15:03
Okay, so this seems to be a size issue.
One drawer, size 24.
This adapts to my mate-panel size 19.
It only gets bigger if I open the drawer, still the size of the icon doesn't change, but the size of the drawer is 24.
![screenshot at 2018-02-06 15-52-19](https://user-images.githubusercontent.com/31438307/35865813-d26af82a-0b55-11e8-9a48-96efc6738dbe.png)

(See how the terminal icon is much bigger? That is 24, the drawer icon is 19.)

-----
Now you would expect that the same thing happens if there is a drawer inside the drawer, but no.
![screenshot at 2018-02-06 15-55-43](https://user-images.githubusercontent.com/31438307/35866000-455d6d68-0b56-11e8-88a2-5c6808b1fd19.png)

This is the double drawer. Both closed. Both set to 19, but they are 24 if the drawers are opened.
As you can see the outer drawer is 24, even if it is set to 19, therefore bigger than my panel.
Note that the icon is as small as it should be, only the background is bigger.

The 'funny' part is that even if I set my panel to be 24, the double drawer is still bigger than the panel...

-----
another issue is that the drawer doesn't close itself if an app is launched.
this may be responsible for the second comment and is a likely cause to #704

**Closed** 2018-02-15 19:57 UTC
