### ISSUE TITLE
Drawer panel stretched over the entire screen.

### ISSUE THREAD

**Issue by woox2k** [mate-desktop/mate-panel#120] opened 2013-09-20 13:06 UTC
It seems that quite randomly when i start up MATE and open drawers the panel that opens up stretches over the entire screen even if i only have 1 or 2 launchers in it. After restarting mate-panel it works fine again until next time.

Screenshots:
Bug: https://dl.dropboxusercontent.com/u/60804341/mate-panel-120-bug.png
Ok: https://dl.dropboxusercontent.com/u/60804341/mate-panel-120-ok.png

Because this issue appears quite randomly it's difficult to test different settings so i put current ones here:
Size: 48
Custom background image and icon
Show hide buttons: off
Drawer contents do not make any difference

General info:
OS: Archlinux x64 this bug also appeared in Mint 15 MATE
Desktop Environment: MATE
mate-panel version: 1.6.1-2

**Comment by samandiriel** [comment] 2015-09-04 16:10
I can verify the issue still occurs in Mint 17.2, using mate-panel 1.10.0 :(

It is buggy far more often than not, for me - I should be able to provide loads of data, if needed.

**Comment by ebrensi** [comment] 2015-11-20 16:46
I'm using Mint 17.2 with Mate 1.10.1 Panel.   I have been having this issue as well.  It seems to happen if I try to put more than two items in the drawer.  Or not.  But it has something to do with adding items to the drawer.

**Comment by nivag** [comment] 2015-12-15 00:35
This still happens on Fedora 23 with Mate 1.12.1.

I have from 4 to 7 entries in 4 drawers in my top panel.

Problem does not happen that often (and only at the start of a session), but it is annoying.  Deleting mate-panel usually does the trick, rarely do I have delete it twice.

**Comment by monsta** [comment] 2015-12-18 10:43
Guys, what are your drawers' settings?
- width (24 or custom?)
- icon (default or custom?)
- hide buttons (shown or not?)

Also for those who experience it only on session start: try restarting the panel (```killall mate-panel```) - does the issue happen after the panel reloads?

**Comment by woox2k** [comment] 2015-12-18 11:19
My settings are all on first post and the issue still remains for me too. Apparently this issue occurs randomly on mate-panel startup not session startup. Most of the time i kill it manually it starts up fine but sometimes it is still stretched over the screen and i have to kill it second time.

**Comment by monsta** [comment] 2015-12-18 12:09
I wonder if changing some of these settings could affect the bug somehow...

**Comment by nivag** [comment] 2015-12-18 19:10
On 18/12/15 23:43, monsta wrote:
>
> Guys, what are your drawers' settings?
>
>   * width (24 or custom?)
>   * icon (default or custom?)
>   * hide buttons (shown or not?)
>
> Also for those who experience it only on session start: try restarting 
> the panel (|killall mate-panel|) - does the issue happen after the 
> panel reloads?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mate-desktop/mate-panel/issues/120#issuecomment-165744755>.
>
width: 48
custom icon
Show hide buttons: unticked

Only happens at start of session, but in a minority of cases - killing 
mate mate-panel usually fixes it, sometimes I need to kill it a second time

**Comment by monsta** [comment] 2015-12-21 08:19
Damn these random bugs... sometimes I can reproduce it when adding items to a drawer that's currently open... sometimes not. A couple of times the bug appeared right after I simply did ```killall mate-panel```. :confused: 

And all that is happening only in Virtualbox. I'm yet to reproduce it on baremetal...

**Comment by monsta** [comment] 2015-12-21 12:35
Ok, reproduced on baremetal as well. Adding applets to drawer while it's open might trigger the bug. Sometimes it takes a few clicks on Add button (i.e. several identical applets will be added before the bug happens).

**Comment by monsta** [comment] 2015-12-23 12:09
Hopefully https://github.com/mate-desktop/mate-panel/commit/bdfdeaeabf8f5bd233126a826d59e5ddd3a1cc1e should fix it.

**Comment by raveit65** [comment] 2015-12-23 17:18
@nivag and other fedora people :)
fedora scratch build for testing the fix.
f22:
http://koji.fedoraproject.org/koji/taskinfo?taskID=12294903
f23:
http://koji.fedoraproject.org/koji/taskinfo?taskID=12294908
Please test.

**Comment by nivag** [comment] 2015-12-27 01:38
On 24/12/15 06:18, Wolfgang Ulbrich wrote:
>
> @nivag <https://github.com/nivag> and other fedora people :)
> fedora scratch build for testing the fix.
> f22:
> http://koji.fedoraproject.org/koji/taskinfo?taskID=12294903
> f23:
> http://koji.fedoraproject.org/koji/taskinfo?taskID=12294908
> Please test.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mate-desktop/mate-panel/issues/120#issuecomment-166948066>.
>
I am on F23, downloaded rpm's from 
http://koji.fedoraproject.org/koji/buildinfo?buildID=70329, but dnf told 
I had already got more up-to-date ones.  Possibly I've done something 
wrong (or at least, my understanding is insufficient!)?


Cheers,
Gavin

**Comment by raveit65** [comment] 2015-12-27 01:50
> I am on F23, downloaded rpm's from http://koji.fedoraproject.org/koji/buildinfo?buildID=70329, but dnf told I had already got more up-to-date ones. Possibly I've done something wrong (or at least, my understanding is insufficient!)?

weird, latest version in repos is mate-panel-1.12.1-1.fc23
http://koji.fedoraproject.org/koji/packageinfo?packageID=14801
So, mate-panel-1.12.1-2 should update the old version
x86_64
http://koji.fedoraproject.org/koji/taskinfo?taskID=12294910
i686
http://koji.fedoraproject.org/koji/taskinfo?taskID=12294911

**Comment by nivag** [comment] 2015-12-27 03:27
On 27/12/15 14:50, Wolfgang Ulbrich wrote:
>
>     I am on F23, downloaded rpm's from
>     http://koji.fedoraproject.org/koji/buildinfo?buildID=70329, but
>     dnf told I had already got more up-to-date ones. Possibly I've
>     done something wrong (or at least, my understanding is insufficient!)?
>
> weird, latest version in repos is mate-panel-1.12.1-1.fc23
> http://koji.fedoraproject.org/koji/packageinfo?packageID=14801
> So, mate-panel-1.12.1-2 should update the old version
> x86_64
> http://koji.fedoraproject.org/koji/taskinfo?taskID=12294910
> i686
> http://koji.fedoraproject.org/koji/taskinfo?taskID=12294911
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mate-desktop/mate-panel/issues/120#issuecomment-167374893>.
>
# dnf --enablerepo=*test* upgrade mate-panel*
Last metadata expiration check performed 0:00:11 ago on Sun Dec 27 
16:24:59 2015.
Dependencies resolved.
Nothing to do.
Complete!
# uname -a
Linux saturn 4.2.8-300.fc23.x86_64 #1 SMP Tue Dec 15 16:49:06 UTC 2015 
x86_64 x86_64 x86_64 GNU/Linux
#


Where do I find the rpm for mate-panel-1.12.1-2?

**Comment by raveit65** [comment] 2015-12-27 11:28
You need to download the rpms from the links which i gave you :smile:

**Comment by monsta** [comment] 2016-01-28 12:10
Fix released in 1.12.2. Check updates in your distros guys.

**Comment by monsta** [comment] 2016-03-25 08:05
Ok, 1.12.2 with the fix is in Mint 17.3 repos now. Mint users, please test it.

**Comment by monsta** [comment] 2016-04-09 09:22
Well, since there's no more feedback, I guess it's fixed for good now.

**Closed by monsta** 2016-04-09 09:22 UTC
Labels: confirmed
