### ISSUE TITLE
mate-applications.css: segfault libcairo .mate-panel-menu-bar background-image: -gtk-gradient

### ISSUE THREAD

**Issue by own3mall** [mate-desktop/mate-panel#1352] opened 2023-01-31 22:10 UTC
#### Expected behaviour

No segfault and background-image gradient works for .mate-panel-menu-bar styling.

#### Actual behaviour

I maintain and update a GTK2/3+ theme (http://winxp4life.tk/), and with the latest version of Mate in Ubuntu 22.04, my theme no longer works due to a segfault caused by this rule:

```
.mate-panel-menu-bar {
    background-image: -gtk-gradient (linear,
                      left top,
                      left bottom,
                      from (#3168d5),
                      color-stop (0.15, #4490e6),
                      color-stop (0.30, #235bd9),
                      color-stop (0.90, #2562de),
                      to (#1941a5));
    background-color: @selected_bg_color_top_menu;
    padding: 0px;
    color: @bg_color;
    text-shadow: none;
}

```

If I remove the background-image property, the theme works and the segfault doesn't happen. It appears that any -gtk-gradient set on background-image for .mate-panel-menu-bar doesn't work and causes Mate to segfault. I have to change the theme and restart to get things to work again.

```
Jan 31 13:17:41 -VirtualBox kernel: [ 3548.322902] mate-panel[1703]: segfault at 7f32e0027552 ip 00007f32dfc671eb sp 00007ffc063f08f8 error 7 in libcairo.so.2.11600.0[7f32dfc02000+d3000]
Jan 31 13:17:41 -VirtualBox kernel: [ 3548.322912] Code: 52 07 00 e8 87 c9 f9 ff 0f 1f 80 00 00 00 00 f3 0f 1e fa 48 89 f8 48 85 ff 74 14 8b 57 18 83 fa ff 74 0c 8b 57 18 85 d2 7e 06 <f0> 83 47 18 01 c3 50 48 8d 0d 17 56 07 00 ba a2 03 00 00 48 8d 35
Jan 31 13:17:41 -VirtualBox kernel: [ 3549.055408] traps: mate-panel[3931] general protection fault ip:7f486e9721dc sp:7ffe38388ac8 error:0 in libcairo.so.2.11600.0[7f486e90d000+d3000]
```

My complete rule:

```
.mate-panel-menu-bar,
MatePanelApplet > menubar,
PanelToplevel.background > *,
PanelWidget,
PanelFrame,
PanelAppletFrame,
MatePanelAppletFrameDBus,
MatePanelAppletContainer,
MatePanelApplet {
    background-image: -gtk-gradient (linear,
                      left top,
                      left bottom,
                      from (#3168d5),
                      color-stop (0.15, #4490e6),
                      color-stop (0.30, #235bd9),
                      color-stop (0.90, #2562de),
                      to (#1941a5));
    background-color: @selected_bg_color_top_menu;
    padding: 0px;
    color: @bg_color;
    text-shadow: none;
}
```

#### Steps to reproduce the behaviour

Set any background-image: -gtk-gradient (linear, rule for `.mate-panel-menu-bar`.

#### MATE general version

Mate 1.26.0

#### Package version

```
mate-panel:
  Installed: 1.26.2-1
  Candidate: 1.26.2-1
  Version table:
 *** 1.26.2-1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

#### Linux Distribution

Ubuntu 22.04

#### Link to bugreport of your Distribution (requirement)

https://bugs.launchpad.net/ubuntu/+source/mate-panel/+bug/2004432

**Comment by lukefromdc** [comment] 2023-02-02 06:41
gtk-gradient is deprecated and no longer supported. It often still works, but unsupported code can and does bit-rot as underlying libraries (such as GTK) change so it may not always work. 

In this case, replacing -gtk-gradient with linear-gradient should fix the problem.

I am using it on mate-panel in my UbuntuStudio-Legacy theme 
https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy
with no issues:

```
panel-toplevel.background,
PanelToplevel.mate-panel-menu-bar,
#PanelPlug{
	background-image: linear-gradient(to bottom,
						#303030,
						#1f1f1f 22%,
						#141414 32%,
						#040404 50%,
						#141414 68%,
						#1f1f1f 78%,
						#303030);
	color: white;
	outline-offset: 1px;
	outline-color: @theme_selected_bg_color;
}
```

**Comment by own3mall** [comment] 2023-02-02 19:22
@lukefromdc Thanks!  That syntax works for me as well.  However, do you know where the documentation states that `-gtk-gradient` css syntax is deprecated?  I'm having problems finding that.  I see this:  https://docs.gtk.org/gtk3/struct.Gradient.html   However, that seems to be more UI programming related.  Where is the CSS syntax deprecated?  

It's crazy how complicated it is to create a theme and have it work across multiple versions of GTK and different releases.  What a mess.

**Comment by lukefromdc** [comment] 2023-02-02 19:52
On the linked website is says right there

deprecated: 3.8 since: 3.0

meaning it wasn't even supported for very long. My guess
as as CSS gained features reimplementing them in GTK
was seen as a useless duplication of effort

**Comment by lukefromdc** [comment] 2023-02-02 19:53
what is deprecated is -gtk-gradient itself it seems

**Comment by raveit65** [comment] 2023-07-24 13:16
Issue was caused by using deprecated gtk-gradient. So it is not an mate-panel issue, closing.

**Closed by raveit65** 2023-07-24 13:16 UTC

**Comment by arrowgent** [comment] 2024-01-20 13:30
thanks for the fix.  upgrading caused my panel to segmentation fault
gdb mate-panel let me know what to look for: libcairo.so.2
it also mentioned -gtk-gradient

commented out in ~/.config/gtk3-0/gtk.css
/ * -gtk-gradient * /
then restarted mate-panel.
worked great
