### ISSUE TITLE
Themes TraditionalOK and TraditionalGreen lacks background color 

### ISSUE THREAD

**Issue by joakim-tjernlund** [mate-desktop/mate-panel#482] opened 2016-09-22 16:30 UTC
In Evolution, error/warning messages are displayed with white text on light grey background
which makes it hard to read the text.
Menta displays the same text with Green background
GreenLaguna displays with Red background.
When Customising the theme, above color is not present

Adwaita displays with Blue background although Appearance claims Adwaita is broken(Window manager theme is not installed). looks like Window Borders are missing, is this a MATE bugg too?

Mate 1.14, theme 3.20.11

**Comment by lukefromdc** [comment] 2016-09-22 17:59
I believe tha Adwaita issue is lack of a metacity theme, which GNOME no longer uses.

**Comment by joakim-tjernlund** [comment] 2016-09-22 21:38
I don't understand, what does the old metacity theme got to do with Adwaita?
Do you also see the same issue with Adwaita?

**Comment by lukefromdc** [comment] 2016-09-23 03:43
I was only discussing Adwaita.

In mate-appearance-properties, the code that draws the theme previews looks
for all the elements of an overall theme, including a window manager theme.
Since Adwaita no longer ships a metacity theme, some older versions of MATE will
show Adwaita as "broken." This was fixed in mate-control-center (or maybe elsewhere
in MATE?) for newer versions though I have forgotten when and cannot find the commit
 in question.

**Comment by joakim-tjernlund** [comment] 2016-09-23 06:23
I see, but I doubt the TraditionalOK and TraditionalGreen themes are fixed also.

**Comment by lukefromdc** [comment] 2016-09-23 06:33
None of them show the question mark on mate-appearance-properties with 
MATE 1.16 or with MATE 1.14 at least on my systems-but all of my systems
have MATE built with GTK3, NOT GTK2. Many GTK2 themes do not support
customizing colors-and no GTK3 theme does. The "colors" tab has been 
removed from the "customize" options in GTK3 builds for that reason. 

I myself can't help with GTK2 theme customizing as I dont have any GTK2
mate setups anymore.  I don't know if any of the MATE themes were designed
to support custom colors in GTK2 but if they were, using that option would cause
the GTK2 and GTK3 themes to become mismatched due to the inablity to recolor
any GTK3 theme.

**Comment by joakim-tjernlund** [comment] 2016-09-23 06:44
I have MATE 1.14 built with gtk2 but evolution is gtk3 and gtk2 vs. gtk3 does not explain why
why the other themes I tried worked but not TraditionalOK and TraditionalGreen.
This indicates to me that there is some gtk3 item missing in TraditionalOK and TraditionalGreen

The removal of custom colors explains why I could not find the color I was looking for.

**Comment by lukefromdc** [comment] 2016-09-23 18:09
I am not the maintainer of either TraditionalOK or TraditionalGreen but am familiar with the custom colors issue from other work I've done in GTK3 builds of MATE.

**Comment by joakim-tjernlund** [comment] 2016-09-24 12:27
Could you alert the TraditionalOK/TraditionalGreen maintainer? I have no idea who that is.

**Comment by raveit65** [comment] 2016-09-24 13:16
TraditionalOK/TraditionalGreen maintainer is allergic to alerts and his union says he have to go in holidays for the next 6 month ;)

**Comment by raveit65** [comment] 2016-09-24 13:18
PS: i do do not use evolution, i prefer claws-mail.

**Comment by joakim-tjernlund** [comment] 2016-09-24 15:39
I think he needs a new union :)

**Comment by joakim-tjernlund** [comment] 2016-09-27 09:03
BTW, even though you don't use Evolution I was hoping that the colour examples I listed above would be
enough to identify the missing colour setting?

**Comment by raveit65** [comment] 2016-09-27 09:43
TOK themes are old and limited and use only 2 colors in gtk.css
```
/*****************
 * error/warning *
 *****************/
@define-color error_color #cc0000;
@define-color warning_bg_color #faad3d;
```
Menta, modern and nice use 4 colors in gtk-main-common.css
```
/*********************
 * Error/Warning/... *
 *********************/
@define-color link_color #61bf00;
@define-color warning_color #f57900;
@define-color error_color #cc0000;
@define-color success_color #4e9a06;
```
Link and success color are green, but i don't think this is enough to identify the wrong setting.
Please post a screenshot with TOK and Menta theme where the issue is displayed.
And steps to reproduce it for me as i don't know how to use evolution with a single email address after installation and first setup.
..... and i don't want to learn it :P

**Comment by joakim-tjernlund** [comment] 2016-09-27 11:27
There is a link_color a few lines above. I added both to TOK but no change. 
Do I have to "compile" anything for such changes to be visible?

**Comment by raveit65** [comment] 2016-09-27 12:17
No, in gtk.css are only the definitions of the colors. You need to check where  link_color or success_color is used in Menta's css files.
There must be a setting which is responsible for the bg color.
But easier is to use gtk3-inspector for it which shows you the right widget class and where the wrong color is set up.
In fedora gtk3-inspector is part of the gtk3-devel package.
Than use this gsettings keys
```
[rave@mother ~]$ gsettings get org.gtk.Settings.Debug enable-inspector-keybinding
true
[rave@mother ~]$ gsettings get org.gtk.Settings.Debug inspector-warning
false
```
On top of the focused evolution window with the warning use this keybinding to fire up gtk3-inspector.
crtl+shift+d.
Than press the left button in inspectors headerbar and select the element in evolution where you want infos about.
And play a bit around to learn how gtk3-inspector works ;)

**Comment by joakim-tjernlund** [comment] 2016-09-27 12:33
That lead me to EAlertBar (Notice the word Alert :)
![screenshot at 2016-09-27 14-31-29](https://cloud.githubusercontent.com/assets/13720190/18873361/56603204-84bf-11e6-99c2-04de51b70c56.png)

**Comment by joakim-tjernlund** [comment] 2016-09-27 12:45
Oops, closed it by mistake

**Comment by raveit65** [comment] 2016-09-27 13:26
In g-i there is another view where a combobox is, choose here CSS-Selector.
This shows you the selector which should be use in css file.

You can test a setting in real time in CSS tab of g-i .

**Comment by raveit65** [comment] 2016-09-27 13:30
Btw., i guess it's 'infobar'.
Here are the settings in Menta theme.
https://github.com/mate-desktop/mate-themes/blob/gtk3.20/desktop-themes/Menta/gtk-3.0/gtk-widgets.css#L4885

**Comment by raveit65** [comment] 2016-09-27 13:40
Ok, use this setting from Menta theme
https://github.com/mate-desktop/mate-themes/blob/gtk3.20/desktop-themes/Menta/gtk-3.0/gtk-widgets.css#L4893
```
.info,
.question,
.warning,
.error {
	background-color: @infobar_bg_color;
	color: @infobar_fg_color;
	text-shadow: none;
	border-color: darker(@infobar_bg_color);
}
```
and define the infobar_bg_color (which is green) in gtk.css in TOK themes.
Like this:
https://github.com/mate-desktop/mate-themes/blob/gtk3.20/desktop-themes/Menta/gtk-3.0/gtk-main.css#L62

Looks like infobar_fg_color isn't defined in Menta theme :)

**Comment by joakim-tjernlund** [comment] 2016-09-27 14:10
You nailed it!:)

I ended up with:
 .error {
    background-color: @infobar_bg_color;
    color: @infobar_fg_color;
    text-shadow: none;
    border-color: darker(@infobar_bg_color);
}
and then 
@define-color infobar_bg_color rgb (51, 51, 38);

Otherwise this background shows up in other places too so minimal
change is the above.

**Comment by raveit65** [comment] 2016-09-28 05:17
Fine that it works but i want to fix/existing setting for it.
Does that work?
https://gist.github.com/raveit65/0d1787abe66042180521d779e6c3acc2

**Comment by joakim-tjernlund** [comment] 2016-09-28 06:33
Yes, it works just fine :)

Error are dark red bg with white text and inf/warning are Yellow with black text. Look good

**Comment by joakim-tjernlund** [comment] 2016-09-28 06:36
BTW, is there a way to set system default theme and Window Behaviour?

**Comment by raveit65** [comment] 2016-09-28 10:00
commited https://github.com/mate-desktop/mate-themes/commit/ae8d8a7e8da434bac5c774823254d2db30b9b5a7

> BTW, is there a way to set system default theme and Window Behaviour?

I don't get what you mean?
The theme is set in mate-appearance-properties, and there is a gsettings key for it.
Which window behaviour?
Please use more than 2 words......... ;)

**Closed by raveit65** 2016-09-28 10:00 UTC

**Comment by joakim-tjernlund** [comment] 2016-09-28 13:47
I always have problem finding the right settings, grepping for Traditional gets me 
gsettings list-recursively | grep Traditional
org.mate.Marco.general theme 'TraditionalOk'
org.mate.interface gtk-theme 'TraditionalOk'
org.mate.Marco.general theme 'TraditionalOk'

I guess I should set both keys then but why 2 identical entries?

Some digging for Window Behaviour I fond:
 gsettings list-recursively | grep focus-mode
org.mate.Marco.general focus-mode 'sloppy'
org.gnome.desktop.wm.preferences focus-mode 'click'
org.mate.Marco.general focus-mode 'sloppy'

Again 2 identical entries but now they are different?

**Comment by raveit65** [comment] 2016-09-28 15:37
```
[rave@mother ~]$ gsettings list-recursively | grep Blue-Submarine
org.gnome.metacity.theme name 'Blue-Submarine'
org.gnome.desktop.wm.preferences theme 'Blue-Submarine'
org.gnome.desktop.interface gtk-theme 'Blue-Submarine'
org.gnome.metacity.theme name 'Blue-Submarine'
org.cinnamon.desktop.wm.preferences theme 'Blue-Submarine'
org.cinnamon.desktop.interface gtk-theme 'Blue-Submarine'
org.mate.Marco.general theme 'Blue-Submarine'
org.mate.Marco.general theme 'Blue-Submarine'
org.mate.interface gtk-theme 'Blue-Submarine'
```
No idea why org.mate.Marco.general theme is double listed.
This setting is for the metacity theme and 'org.mate.interface gtk-theme' sets the gtk theme.
Of course you can create a gsettings override file to change  defaults.
I use  this for fedora as vendor /usr/share/glib-2.0/schemas/10_mate-fedora.gschema.override
As admin or user you can use a higher number than 10.
Example settings: http://pkgs.fedoraproject.org/cgit/rpms/mate-desktop.git/tree/mate-fedora-f25.gschema.override
You need to apply such a file with ' /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/' as root.

**Comment by joakim-tjernlund** [comment] 2016-09-28 15:56
I used dconf to set new defaults:
 cat /etc/dconf/db/site.d/default-theme 
[org/mate/interface]
gtk-theme='TraditionalOK'
[org/mate/Marco/general]
theme='TraditionalOk'
[org/mate/Marco/general]
focus-mode='sloppy'

Not sure if this has any drawbacks rather than schema.overides?

**Comment by joakim-tjernlund** [comment] 2016-09-30 08:49
This is probably off topic but I have noticed(for a very long time) that apps which you have
marked "Always on Visible Workspace" sometimes reverts back to "Only on this Workspace".
I have not been able to pin point what could cause this. Have you ever seen the same?
