### ISSUE TITLE
Removing any applet crashes mate-panel, at least in GTK3

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#447] opened 2016-06-08 03:36 UTC
With mate-panel from current GIT master buitl with GTK 3.21, applets add and run fine and I get no applet crashes, but removing any applet crashes the panel. In process or out, either way the panel crashes.

I got this error when removing the inhibit applet from the laptop's panel as a test:
traps: mate-panel[4355] general protection ip:42e22f sp:7ffe398a99c0 error:0 in mate-panel[400000+8b000]

Similar errors from removing any other applet, on any system with mate from current GIT master
##

**Comment by raveit65** [comment] 2016-06-08 11:01
I can reproduce this only in fedora rawhide (mate gtk3) tested with 1.14.1 release,
but not with f24.
Abrt gaves me a core_backtrace:
```
{   "signal": 11
,   "executable": "/usr/bin/mate-panel"
,   "only_crash_thread": true
,   "stacktrace":
      [ {   "crash_thread": true
        ,   "frames":
              [ {   "address": 93883586263423
                ,   "build_id": "982839219a40ac1131ce4a9a44bc3f834db52d6b"
                ,   "build_id_offset": 190847
                ,   "function_name": "mate_panel_applet_locked_change_notify"
                ,   "file_name": "/usr/bin/mate-panel"
                }
              , {   "address": 140087278436292
                ,   "build_id": "af0d4a312054e41039eb733581ccb819011a633d"
                ,   "build_id_offset": 73668
                ,   "function_name": "g_cclosure_marshal_VOID__STRINGv"
                ,   "file_name": "/usr/lib64/libgobject-2.0.so.0.4901.0"
                }
              , {   "address": 140087278425988
                ,   "build_id": "af0d4a312054e41039eb733581ccb819011a633d"
                ,   "build_id_offset": 63364
                ,   "function_name": "_g_closure_invoke_va"
                ,   "file_name": "/usr/lib64/libgobject-2.0.so.0.4901.0"
                }
              , {   "address": 140087278537945
                ,   "build_id": "af0d4a312054e41039eb733581ccb819011a633d"
                ,   "build_id_offset": 175321
                ,   "function_name": "g_signal_emit_valist"
                ,   "file_name": "/usr/lib64/libgobject-2.0.so.0.4901.0"
                }
              , {   "address": 140087278539583
                ,   "build_id": "af0d4a312054e41039eb733581ccb819011a633d"
                ,   "build_id_offset": 176959
                ,   "function_name": "g_signal_emit"
                ,   "file_name": "/usr/lib64/libgobject-2.0.so.0.4901.0"
                }
              , {   "address": 140087281623062
                ,   "build_id": "4436137e91521d1ec0d76f194146211bfca1d817"
                ,   "build_id_offset": 823318
                ,   "function_name": "g_settings_real_change_event"
                ,   "file_name": "/usr/lib64/libgio-2.0.so.0.4901.0"
                }
              , {   "address": 140087172283480
                ,   "build_id": "144cb76ce55d5f87ff78647a8807e2a47fa3bea5"
                ,   "build_id_offset": 23640
                ,   "function_name": "ffi_call_unix64"
                ,   "file_name": "/usr/lib64/libffi.so.6.0.2"
                }
              , {   "address": 140087172282042
                ,   "build_id": "144cb76ce55d5f87ff78647a8807e2a47fa3bea5"
                ,   "build_id_offset": 22202
                ,   "function_name": "ffi_call"
                ,   "file_name": "/usr/lib64/libffi.so.6.0.2"
                }
              , {   "address": 140087278428778
                ,   "build_id": "af0d4a312054e41039eb733581ccb819011a633d"
                ,   "build_id_offset": 66154
                ,   "function_name": "g_cclosure_marshal_generic_va"
                ,   "file_name": "/usr/lib64/libgobject-2.0.so.0.4901.0"
                }
              , {   "address": 140087278425988
                ,   "build_id": "af0d4a312054e41039eb733581ccb819011a633d"
                ,   "build_id_offset": 63364
                ,   "function_name": "_g_closure_invoke_va"
                ,   "file_name": "/usr/lib64/libgobject-2.0.so.0.4901.0"
                }
              , {   "address": 140087278536627
                ,   "build_id": "af0d4a312054e41039eb733581ccb819011a633d"
                ,   "build_id_offset": 174003
                ,   "function_name": "g_signal_emit_valist"
                ,   "file_name": "/usr/lib64/libgobject-2.0.so.0.4901.0"
                }
              , {   "address": 140087278539583
                ,   "build_id": "af0d4a312054e41039eb733581ccb819011a633d"
                ,   "build_id_offset": 176959
                ,   "function_name": "g_signal_emit"
                ,   "file_name": "/usr/lib64/libgobject-2.0.so.0.4901.0"
                }
              , {   "address": 140087281628175
                ,   "build_id": "4436137e91521d1ec0d76f194146211bfca1d817"
                ,   "build_id_offset": 828431
                ,   "function_name": "settings_backend_path_changed"
                ,   "file_name": "/usr/lib64/libgio-2.0.so.0.4901.0"
                }
              , {   "address": 140087281604954
                ,   "build_id": "4436137e91521d1ec0d76f194146211bfca1d817"
                ,   "build_id_offset": 805210
                ,   "function_name": "g_settings_backend_invoke_closure"
                ,   "file_name": "/usr/lib64/libgio-2.0.so.0.4901.0"
                }
              , {   "address": 140087275456858
                ,   "build_id": "570e52cef9d12e5c7d52be61b0d4336227cf34c4"
                ,   "build_id_offset": 301402
                ,   "function_name": "g_main_context_dispatch"
                ,   "file_name": "/usr/lib64/libglib-2.0.so.0.4901.0"
                }
              , {   "address": 140087275457808
                ,   "build_id": "570e52cef9d12e5c7d52be61b0d4336227cf34c4"
                ,   "build_id_offset": 302352
                ,   "function_name": "g_main_context_iterate.isra.29"
                ,   "file_name": "/usr/lib64/libglib-2.0.so.0.4901.0"
                }
              , {   "address": 140087275458610
                ,   "build_id": "570e52cef9d12e5c7d52be61b0d4336227cf34c4"
                ,   "build_id_offset": 303154
                ,   "function_name": "g_main_loop_run"
                ,   "file_name": "/usr/lib64/libglib-2.0.so.0.4901.0"
                }
              , {   "address": 140087311362741
                ,   "build_id": "7be84d803e3f8b871d4fad3a1079ae765013d2da"
                ,   "build_id_offset": 2398901
                ,   "function_name": "gtk_main"
                ,   "file_name": "/usr/lib64/libgtk-3.so.0.2100.2"
                }
              , {   "address": 93883586210326
                ,   "build_id": "982839219a40ac1131ce4a9a44bc3f834db52d6b"
                ,   "build_id_offset": 137750
                ,   "function_name": "main"
                ,   "file_name": "/usr/bin/mate-panel"
                } ]
        } ]
}
```
This looks like a problem or a change with gsetting in glib.
I will update a f24 VM to 1.15 if i have finished the release action.
I'm pretty sure that 1.15 won't crash in f24.

**Comment by raveit65** [comment] 2016-06-08 11:03
Fedora rawhide use glib2-2.49.1-2.fc25.x86_64

**Comment by raveit65** [comment] 2016-06-08 12:54
Btw, i recall that report https://github.com/mate-desktop/mate-panel/issues/414#issuecomment-200473500
Same issue and probably fixed with next glib stable release.

**Comment by monsta** [comment] 2016-06-15 11:40
Oh come on... will this re-appear with every new dev version of GLib? :smile:

**Comment by monsta** [comment] 2016-09-18 14:09
Do you still get it guys? I can't reproduce it in Ubuntu 16.10 with 2.49.6. GTK+ is 3.20.9, not sure if that matters for this issue.

**Comment by lukefromdc** [comment] 2016-09-18 19:05
Still goes on here, I've come to expect a panel crash and restart every time I remove an applet. I'm using GTK 3.21.7 from git master as of yesterday, this issue has never changed since I first reported it, but that was during the GTK 3.21 development cycle so it might be GTK version specific

**Comment by monsta** [comment] 2016-09-20 13:49
I can't reproduce it with 3.21.5 either, in another VM. Maybe it does matter that it's a VM.

**Comment by raveit65** [comment] 2016-10-01 05:59
I can't reproduce it any more with stable glib on bare metal (f25).
[rave@mother ~]$ rpm -qa glib2
glib2-2.50.0-1.fc25.x86_64
[rave@mother ~]$ rpm -qa gtk3
Tested with every applet and transparency panel.
......every half a year the same.
gtk3-3.22.0-2.fc25.x86_64

**Comment by monsta** [comment] 2016-11-25 13:38
Just for the record - I don't see any crashes when removing an applet with GTK+ 3.18.9. No in-process applets here (I always use the default build setting for that).

**Comment by willysr** [comment] 2016-11-25 14:57
Yes, i can confirm that in 3.18.9 removing applets will not crash the panel

**Comment by monsta** [comment] 2016-11-25 21:28
@lukefromdc: do you still get the crashes with 3.22?

**Comment by lukefromdc** [comment] 2016-11-25 23:57
Not at all. I am using out of process applets due to 
https://github.com/mate-desktop/mate-panel/issues/468
and can add and remove applets freely with GTK 3.22.4

**Comment by monsta** [comment] 2016-11-26 10:22
Should we close this issue then - and leave #468 open to remind us about in-process applets?

**Comment by raveit65** [comment] 2016-11-26 17:28
yes,....and done

**Closed by raveit65** 2016-11-26 17:28 UTC
