### ISSUE TITLE
Clock applet crashed once the first location was added

### ISSUE THREAD

**Issue by PSLLSP** [mate-desktop/mate-panel#1138] opened 2020-08-26 21:50 UTC
#### Expected behaviour

Just add location, do not crash.

#### Actual behaviour

Applet crashed, and dialog appeared with information that it crashed and offered an option to reload it. Reload worked.

#### Steps to reproduce the behaviour

Fresh install of Linux MINT. Add location to the clock applet on toolbar.

#### MATE general version

https://termbin.com/ub12

#### Linux Distribution

Linux Mint MATE 20.0

**Comment by vrozkovec** [comment] 2021-01-15 09:06
I second this. My clock applet crashes anytime I add location.
https://termbin.com/1cn2
[crash.tar.gz](https://github.com/mate-desktop/mate-panel/files/5819442/crash.tar.gz)

**Comment by lukefromdc** [comment] 2021-01-18 00:50
MATE 1.20 is now quite old, current release is 1.24

**Comment by vrozkovec** [comment] 2021-01-18 17:16
After updating Linux Mint to 20.1, MATE 1.24 came with it and the problem disappeared.

**Comment by vrozkovec** [comment] 2021-01-18 21:12
I was too quick. Still crashes:
https://termbin.com/bm7m
[crash.tar.gz](https://github.com/mate-desktop/mate-panel/files/5832412/crash.tar.gz)

**Comment by cramaker** [comment] 2021-03-01 03:02
This is still present in 1.24.1 and occurs after pressing 'OK' on the 'Choose Location' box. It's reproducible each time a location is added, not just the first location.

A stack trace is here if helpful: https://gist.github.com/cramaker/195465d25d3e705fb9ee36fb2cc4331b

**Comment by lukefromdc** [comment] 2021-03-01 03:32
I had this happen several times in an initially unrelated test yesterday, only to have the problem refuse to reappear in further tests in another session. As I have the panel built in-process, it led the whole panel to crash and repeatedly restart. Running mate-panel --replace brought it up with most or all of my in-process applet not being added. 

 Very strange. I was able to get this stacktrace before the problem quit and did not return. From the libgio references it looks like we are either hitting an issue in libglib or else feeding it bad data at some point. From my inconsistant results I wonder if a race condition (data not ready when a function is called maybe?) is involved:
```

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mate-panel...
(No debugging symbols found in mate-panel)
(gdb) run
Starting program: /usr/bin/mate-panel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff34ae700 (LWP 29619)]
[New Thread 0x7ffff2cad700 (LWP 29620)]
[New Thread 0x7ffff2421700 (LWP 29621)]
[New Thread 0x7ffff12da700 (LWP 29622)]
[New Thread 0x7ffff0957700 (LWP 29624)]
[New Thread 0x7fffe3554700 (LWP 29629)]

Thread 1 "mate-panel" received signal SIGSEGV, Segmentation fault.
0x00007ffff72d43a2 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
(gdb) thread apply all bt full


Thread 7 (Thread 0x7fffe3554700 (LWP 29629) "pool-mate-panel"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff714aab2 in g_cond_wait_until () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70cc4e1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff71240ba in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737007404800, -8506809394857305517, 140737488346798, 140737488346799, 140737007402112, 8396800, 8506872292365769299, 8506826935010662995}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7ffff0957700 (LWP 29624) "pool-mate-panel"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff714aab2 in g_cond_wait_until () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70cc4e1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff71240ba in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#4  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737229715200, -8506809394857305517, 140737488345950, 140737488345951, 140737229712512, 8396800, 8506838759945476691, 8506826935010662995}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7ffff12da700 (LWP 29622) "pool-mate-panel"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff714aab2 in g_cond_wait_until () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70cc4e1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff71240ba in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737239688960, -8506809394857305517, 140737488346702, 140737488346703, 140737239686272, 8396800, 8506841981707819603, 8506826935010662995}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev--Type <RET> for more, q to quit, c to continue without paging--
 = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7ffff2421700 (LWP 29621) "dconf worker"):
#0  0x00007ffff6c7c3ff in __GI___poll (fds=0x555555850140, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff70fb6a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70fb7af in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff35b738d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737257805568, -8506809394857305517, 140737488347214, 140737488347215, 140737257802880, 8396800, 8506835054462442067, 8506826935010662995}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ffff2cad700 (LWP 29620) "gdbus"):
#0  0x00007ffff6c7c3ff in __GI___poll (fds=0x5555556a3c20, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff70fb6a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70fb9eb in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7344896 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737266767616, -8506809394857305517, 140737488344526, 140737488344527, 140737266764928, 8396800, 8506834021522807379, 8506826935010662995}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ffff34ae700 (LWP 29619) "gmain"):
#0  0x00007ffff6c7c3ff in __GI___poll (fds=0x5555556905e0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff70fb6a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70fb7af in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff70fb801 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737275160320, -8506809394857305517, 140737488344158, 140737488344159, 140737275157632, 8396800, 8506837319520819795, 8506826935010662995}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
Thread 2 (Thread 0x7ffff34ae700 (LWP 29619) "gmain"):
#0  0x00007ffff6c7c3ff in __GI___poll (fds=0x5555556905e0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff70fb6a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70fb7af in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff70fb801 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737275160320, -8506809394857305517, 140737488344158, 140737488344159, 140737275157632, 8396800, 8506837319520819795, 8506826935010662995}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
Thread 1 (Thread 0x7ffff59e3f00 (LWP 29596) "mate-panel"):
#0  0x00007ffff72d43a2 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#1  0x00007ffff72ddb19 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#2  0x00007ffff72ddb59 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#3  0x00007ffff70fb38f in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff70fb708 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff70fb9eb in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff78fcc95 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x0000555555579118 in main ()


```

**Comment by zhuyaliang** [comment] 2021-03-01 09:49
@lukefromdc I fixed this problem, please test the effect

**Comment by rbuj** [comment] 2021-03-01 12:24
I was unable to reproduce the violation of the segment nor have I determined the cause of this by reading the backtrace which doesn't incorporate debug symbols.

In order to get a suitable backtrace, run the clock applet with the debug symbols in a separate terminal before adding it into the panel.

**Comment by lukefromdc** [comment] 2021-03-01 14:31
I cannot really test this because most of the time I cannot invoke the crash: it is intermittant on my system

**Comment by lukefromdc** [comment] 2021-03-01 14:40
Just tested  https://github.com/mate-desktop/mate-panel/pull/1208 to the extent I could, works fine but with the crash not reliably showing up on master I cannot confirm if the problem is fixed by it. Someone who always gets the crash needs to try it.

**Comment by zhuyaliang** [comment] 2021-03-01 15:05
> I cannot fully test this because most of the time I cannot invoke the crash: it is intermittant on my system

Code before change adding multiple cities in succession will result in segment error

**Comment by rbuj** [comment] 2021-03-01 15:20
With or without this PR, I haven't been able to replicate the segment violation either in a system with the latest MATE components installed from git (1), nor in a live media of Fedora 33 MATE Compiz spin up to date (2).

(1) https://gist.github.com/rbuj/bc62164be10a7290f5213c47711c7998#file-test-mate-desktop-sh
(2) https://www.dropbox.com/sh/madaacduuiffylj/AACGWh__uCPjb3QsNYfYyn34a?dl=0&lst=

**Comment by raveit65** [comment] 2023-07-21 20:51
Should be fixed.

**Closed by raveit65** 2023-07-21 20:51 UTC
Labels: confirmed
