### ISSUE TITLE
command applet preferences freeze during command execution

### ISSUE THREAD

**Issue by cheater** [mate-desktop/mate-panel#298] opened 2015-04-28 07:30 UTC
If the command takes long to execute, the preferences window will be frozen.

Discovered this when I set the interval to 1 second, and put "sleep 60" in the script it was executing.

This might be an issue if you can't modify the executable specified in the preferences.

**Comment by cheater** [comment] 2015-04-28 07:31
Note I'm fine with this not being fixed right now. It's a non-issue for my case. But it might be an issue for someone, so I put it here.

**Comment by monsta** [comment] 2016-04-22 06:10
The cause of this issue is the same as in https://github.com/mate-desktop/mate-applets/issues/163 (synchronous running of the command), therefore I'm closing this one. I'll make the command run asynchronously for 1.16 release, that should solve it.

**Closed by monsta** 2016-04-22 06:10 UTC
