### ISSUE TITLE
Please fix mate panel font issue.

### ISSUE THREAD

**Issue by infuerano** [mate-desktop/mate-panel#690] opened 2017-12-05 13:13 UTC
This particular issue not letting me update to the latest version of Linux mint mate or ubuntu mate. Everything was fine until ubuntu 16.04/ Mint 18.1. For me, the regular font in the status bar looks ugly. But I would ask if I can't even change the font from appearance setting then why it is there?

**Comment by lukefromdc** [comment] 2017-12-05 21:28
Duplicate of https://github.com/mate-desktop/mate-panel/issues/503

**Closed** 2017-12-06 11:48 UTC
