### ISSUE TITLE
applet widths too narrow with gtk 3.23.1

### ISSUE THREAD

**Issue by Safari77** [mate-desktop/mate-panel#843] opened 2018-07-19 06:29 UTC
#### Expected behaviour
applets displayed ok

#### Actual behaviour
applet widths cut to half

#### Steps to reproduce the behaviour
add clock applet when using gtk-3.23.1

#### MATE general version
1.21

#### Package version
1.21.1 git 7369482f848486c5e35f2883346b23b1cacc6f37

#### Linux Distribution
Fedora 28

#### Link to downstream report of your Distribution
![mate-panel-1 21 1 half](https://user-images.githubusercontent.com/3876865/42925245-ccf2a3fe-8b2d-11e8-92b7-e44c64c247c1.png)

**Comment by Safari77** [comment] 2018-07-19 06:31
```
gtk_widget_size_allocate(): attempt to underallocate MatePanelApplet's child GtkToggleButton 0x55f01c74fd80. Allocation is 131x32, but minimum required size is 262x33.
gtk_widget_size_allocate(): attempt to underallocate GtkToggleButton's child ClockBox 0x55f01cc7fa00. Allocation is 129x30, but minimum required size is 260x31.
gtk_widget_size_allocate(): attempt to underallocate ClockBox's child GtkLabel 0x55f01cc7ed50. Allocation is 260x30, but minimum required size is 260x31.
```

**Comment by raveit65** [comment] 2018-07-19 07:56
I don't see gtk+-3.23.1 in fedora repos.
https://koji.fedoraproject.org/koji/packageinfo?packageID=10393

**Comment by lukefromdc** [comment] 2018-07-19 17:54
You will get a lot more warnings with any odd-numbered (development) build of GTK3 with default build options. Release versions use(unless changed at configuration) --enable-debug=minimal, which minimizes warnings, while development versions default to --enable-debug=yes, and this is intended to allow finding and fixing these issues, which exist with or without the warnings. Do not use --enable-debug=no, as it removes runtime checks that can stop segfaults in programs with issues.

A build of GTK 3.22.30 with --enable-debug=yes would determine if the reported warnings concern issues limited to GTK 3.23 only or also present in GTK 3.22.30. They might be new, as I recall warning fix commits during the GTK 3.19 and 3.21 cycles. New GTK versions can change behavior or many widgets, thus the debug=yes default during development cycles

**Comment by Safari77** [comment] 2018-07-20 06:40
There were already several commits with notes about GTK 3.23 in mate-panel git, it led me believe it (3.23) might actually work.

**Comment by raveit65** [comment] 2018-07-20 08:02
> There were already several commits with notes about GTK 3.23 in mate-panel git, it led me believe it (3.23) might actually work.

I say it clear, gtk+-3.23.x isn't in fedora repos and if it comes than gnome guys will it push to f29.
Using development versions in a stable release is always a risk and you do it for you own risk.

**Comment by lukefromdc** [comment] 2018-07-20 19:06
The obvious use for a development version of a library with a development version of software using it (such as odd numbered GTK with odd numbered mate-panel) is to find and fix new bugs in the applications coming from changes in the library before rather than after they get to a release.  That's why the full debugging support by default.

GTK 3.23 does work with MATE, I use it every day.  Because I produce and develop on the same box(with a full backup system partition available if needed), I use --enable-debug=minimal so I don't fill up the 10GB system partitions with logs.

I still remember the mess created when Debian updated GTK to 3.22 before MATE 1.16 was out. Changes between 3.20 and 3.22 had badly broken the Caja desktop and it took months of work to fix it. Fortunately the first version of those fixes was already in the development version of Caja-but Debian waited for the release, and for weeks Caja simply did not work in Debian.  We had another nasty issue with panel custom backgrounds that came up with the GTK 1.18 to 1.20 transition, and again that was over a month to fix.

Having that come up after everything was released would be lots of "fun" for end users.

**Comment by lukefromdc** [comment] 2018-07-20 19:09
In the photo I don't see actual panel icons cut vertically (as they would be if not enough space was actually present), rather I see the message about the underallocation warnings, which seem to crop up with every new version of GTK3.

**Comment by Safari77** [comment] 2018-07-20 19:52
In the photo Sticky Notes is cut in half, and year and time is missing from clock applet.

**Comment by lukefromdc** [comment] 2018-07-20 20:00
I thought the photo itself was partial, and don't normally use Stickynotes so didn't notice that. On my box with gtk 3.23.1 (built today) I have no issues with the clock, and if I add Stickynotes it renders fullsize. What glib version are you using? If you are still using glib 2.56 with GTK 3.23 that might be the difference, or it may not be.

**Comment by Safari77** [comment] 2018-07-20 21:09
```glib 2.56.1``` and...

```
org.gnome.desktop.interface text-scaling-factor 2.0
org.gnome.desktop.interface scaling-factor uint32 0
org.mate.interface window-scaling-factor 2
org.mate.interface window-scaling-factor-qt-sync true
```

**Comment by lukefromdc** [comment] 2018-07-20 21:16
OK, this looks like we have more applet scaling bugs in HiDPI mode. I had to fix that for tray icons in 
https://github.com/mate-desktop/mate-panel/commit/3820f05688734c96f0668760bd8bd62ebb1e6d34#diff-71c6b44954135d46d4157fa4d624c523. There was a change in GTK 3.23 to fix an issue with HiDPI that we had gotten around by dividing width by the scaling factor. This turned out to be because of a bug in GTK 3.22, and the bug is fixed in GTK 3.23. Thus we need to go back to that workaround code and put it behind GTK 3.22 only buildtime selectors, just as I did for the tray .

**Comment by lukefromdc** [comment] 2018-07-20 21:22
Bug confirmed, if I set window-scaling=2 then out of process applets get cut too narrow. This is real and the warnings are for it. I will now prepare a PR to fix it.

**Comment by lukefromdc** [comment] 2018-07-20 21:42
Try
https://github.com/mate-desktop/mate-panel/pull/845
which should fix your problem. It worked here, I tested both GTK 3.22 and GTK 3.23 builds with their respective GTK versions.

**Comment by raveit65** [comment] 2018-07-21 11:35
Tray and clock applets looks broken with f29 + gtk+-3.23.1 + HIDPI
![tray-and-clock-applet-gtk-3 23 1](https://user-images.githubusercontent.com/961604/43035153-c46991d4-8cea-11e8-895b-880953cbacba.png)

**Comment by lukefromdc** [comment] 2018-07-21 18:41
Do you have https://github.com/mate-desktop/mate-panel/commit/3820f05688734c96f0668760bd8bd62ebb1e6d34 in f29 yet? That's the fix for the tray. If your clock is out-of-process (as I think you are building all out of process), https://github.com/mate-desktop/mate-panel/pull/845 should fix it.

**Comment by raveit65** [comment] 2018-07-21 19:35
opps, sorry for confusing.
I posted this to confirm the issue before i used your PR.
And yes, your PR fixes the problem.

**Closed** 2018-07-23 04:07 UTC
Labels: confirmed
