### ISSUE TITLE
Some GTK settings breaks Applications Places System menu bar.

### ISSUE THREAD

**Issue by rilian-la-te** [mate-desktop/mate-panel#549] opened 2017-04-03 14:15 UTC
To reproduce:
add to ~/.config/gtk-3.0/settings.ini
```
[Settings]
gtk-shell-shows-app-menu=true
gtk-shell-shows-menubar=true
```

Result:
Menu bar disappeared.
Expected result:
Menu bar stays in place.

**Comment by lukefromdc** [comment] 2017-04-04 00:04
What version of mate-panel, and what GTK3 version? I assume you have mate-panel built with GTK3?

I was unable to duplicate this with GTK 3.22.11 and MATE 1.19 built from current git master over Debian Unstable.

**Comment by rilian-la-te** [comment] 2017-04-04 00:37
It can be duplicated only if unity-gtk-module is in action. Ask Ubuntu Mate
developers, who test Global Menu.

**Comment by rilian-la-te** [comment] 2017-04-04 05:59
I created this as a result of discussion in
https://github.com/rilian-la-te/vala-panel-appmenu/issues/60

**Comment by raveit65** [comment] 2017-04-04 06:59
I am still wondering that gtk-shell-shows-app-menu has an influence for our menubars.
An app-menu is mostly the left button in headerbar of a csd window, right?

**Comment by rilian-la-te** [comment] 2017-04-04 07:11
> An app-menu is mostly the left button in headerbar of a csd window, right?

Yes. You are right, only gtk-shell-shows-menubar has influence.

> I am still wondering that gtk-shell-shows-app-menu has an influence for our menubars.

gtk-shell-shows-app-menu does not take influence, gtk-shell-shows menubar does.
unity-gtk-module does not knows, this is regular window menubar or panel menubar and just take menu away from window.
I found similar issue in vala-panel after vala-panel-appmenu initial release and included to my menumodel plugin (which displays Applications Places System on vala-panel):
```vala
        unowned Gtk.Settings gtksettings = this.get_settings();
        gtksettings.gtk_shell_shows_menubar = false;
```

**Comment by raveit65** [comment] 2017-04-04 07:24
I installed unity-gtk-module-common in my 17.04 VM and added the settings.ini file.
But i see our normal 3 menubars (Applications/Places/System) after a theme switch or session restart.
Do i miss something to reproduce the issue?

**Comment by rilian-la-te** [comment] 2017-04-04 07:27
Yes.
1. Install unity-gtk3-module.
2. Add to ```~/.config/gtk-3.0/settings.ini```:
```
[Settings]
gtk-modules = "unity-gtk-module"
gtk-shell-shows-app-menu=true
gtk-shell-shows-menubar=true
```
3. Relogin.
And see the issue.

**Comment by raveit65** [comment] 2017-04-04 07:37
```
root@ubuntu:/home/rave# aptitude install unity-gtk-module
Couldn't find any package whose name is "unity-gtk-module", but there are 3 packages which contain "unity-gtk-module" in their name:
  unity-gtk-module-autopilot unity-gtk-module-common 
  unity-gtk-module-common:i386 
Unable to apply some actions, aborting
root@ubuntu:/home/rave# aptitude search unity-gtk-module
p   unity-gtk-module-autopilot      - GtkMenuShell D-Bus Autopilot tests        
i   unity-gtk-module-common         - Gemeinsame Dateien für den GtkMenuShell-D-
v   unity-gtk-module-common:i386    -                                           
root@ubuntu:/home/rave#
```
Do i need unity-gtk-module-autopilot?

**Comment by rilian-la-te** [comment] 2017-04-04 07:38
You need ```unity-gtk3-module```
Notice 3 after gtk.

**Comment by raveit65** [comment] 2017-04-04 07:46
What do i wrong?
![bildschirmfoto zu 2017-04-04_09-45-30](https://cloud.githubusercontent.com/assets/961604/24646246/85042408-191b-11e7-8534-383f6c34ef24.png)

**Comment by raveit65** [comment] 2017-04-04 07:47
@flexiondotorg 
Can you reproduce it?

**Comment by rilian-la-te** [comment] 2017-04-04 07:48
Are you relogon after this?
If instructions above does not working, try all instructions from vala-panel-appmenu readme and get Global Menu. And issue must appear.

**Comment by raveit65** [comment] 2017-04-04 07:55
Yes, i relogon after this.
Ok, i will install vala-panel-appmenu and global-menu

**Comment by rilian-la-te** [comment] 2017-04-04 07:57
You does not need to install global menu.
You need only working unity-gtk-module (If running pluma from same terminal, which runs mate-panel, pluma menu must disappear).

**Comment by raveit65** [comment] 2017-04-04 08:09
I installed mate-applet-vala-panel-appmenu, added 'Global Application Menu' to the panel and restarted session, but our menubar is fine.
![bildschirmfoto zu 2017-04-04_10-05-22](https://cloud.githubusercontent.com/assets/961604/24647106/c0683d9c-191e-11e7-8482-9cfd13ee7def.png)

**Comment by rilian-la-te** [comment] 2017-04-04 08:16
You have double menus - so, unity-gtk-module is not working, Caja must look like this: 
![screenshot at 2017-04-04 12-15-42](https://cloud.githubusercontent.com/assets/1329638/24647306/0b51d0d0-1928-11e7-857b-a919f8d90de5.png)

When Caja will look like this after opening, your menubar (Applications Places System) will disappear.

**Comment by rilian-la-te** [comment] 2017-04-04 08:20
And, in Ubuntu Mate is patched by my patch. Enable Global Menu in gsettings org.mate.interface.gtk-shell-shows-menubar to true.

**Comment by rilian-la-te** [comment] 2017-04-04 08:20
And relogin and try.

**Comment by raveit65** [comment] 2017-04-04 08:29
OK,
```
rave@ubuntu:~$ gsettings get org.mate.interface gtk-shell-shows-menubar
true
```
destroys the menubar without relogon. wtf.......
Let see if this is reproducible in fedora without unity-gtk-module.

**Comment by rilian-la-te** [comment] 2017-04-04 08:36
I will tell you - no, without unity-gtk-module it is not reproducible, because no one want to scrap all menus from screen to Global Menu:))

**Comment by raveit65** [comment] 2017-04-04 08:39
Good :-)
Btw. what application installs those gsettings keys, i don't see theme here in fedora?

**Comment by rilian-la-te** [comment] 2017-04-04 08:42
> Btw. what application installs those gsettings keys, i don't see theme here in fedora

In fedora you must edit settings.ini.
About keys - this is from https://github.com/mate-desktop/mate-desktop/pull/256.
It is a replacement for
```
[Settings]
gtk-shell-shows-app-menu=true
gtk-shell-shows-menubar=true
```
for more convenience.
If you want to reproduce it in fedora - build unity-gtk-module from vala-panel-appmenu instructions, and use instructions from issue header to see the bug.

**Comment by raveit65** [comment] 2017-04-04 08:44
@flexiondotorg 
Can you please build a debian installer packe for 17.04 with https://github.com/mate-desktop/mate-panel/pull/550 ?
Otherwise i am not able to see if this PR heals the menubar.

**Comment by raveit65** [comment] 2017-04-04 08:47
> If you want to reproduce it in fedora - build unity-gtk-module from vala-panel-appmenu instructions, and use instructions from issue header to see the bug.
No thanks, i don't wanna see the issue in fedora :-)
Does that mean vala-panel-appmenu needs unity-gtk-module in other Distros ?  -_-

**Comment by rilian-la-te** [comment] 2017-04-04 08:50
It is very recommended to use it with (because most of GTK applications require unity-gtk-module to strip menu). But Qt applications does not use it.
Lucky, my little patch https://github.com/rilian-la-te/vala-project-packages/blob/master/archlinux/unity-gtk-module-standalone-bzr/unity-gtk-module-gsettings.patch
enables unity-gtk-module wonder for other distros (unity-gtk-module itself can be built and installed in any distro. It does not have specific ubuntu dependencies).

**Comment by raveit65** [comment] 2017-04-04 08:59
In fedora it called libunity-gtk3-parser
SRPM is unity-gtk-module.
https://koji.fedoraproject.org/koji/packageinfo?packageID=23169

**Comment by rilian-la-te** [comment] 2017-04-04 09:03
This is unpatched version AFAIK. I have a bug than proposes patch.
https://bugzilla.redhat.com/show_bug.cgi?id=1387884

**Comment by lukefromdc** [comment] 2017-04-04 16:47
I stil remember going out of my way to disable global menus in some older versions of Ubuntu. This sort of thing needs to be configurable and the default for MATE should not be to use  global menus unless nondefault packages to enable them have been installed.

**Comment by rilian-la-te** [comment] 2017-04-04 16:50
This is nondefault setting:)) If you wish, you can see, how long we have tried to enable global menu even in Ubuntu. So, it is definitely nondefault.
But I wish than this nondefault setting will not breaks everything.

**Comment by rilian-la-te** [comment] 2017-04-04 16:50
@lukefromdc why are you dislike global menus?

**Comment by lukefromdc** [comment] 2017-04-10 00:49
I just never liked them, I expect to see the menu in the application window. I have never been an Apple user and have never had a Mac, so before I started using Linux in the mid 2000's I learned on Windows, not Mac

**Comment by rilian-la-te** [comment] 2017-04-10 03:42
I started using Linux also in mid 2000s,  and also have never had a Mac. But I was a schoolboy and was want to be diverged from Windows:-)

**Comment by lukefromdc** [comment] 2017-04-10 04:22
Anyway, user tastes differ, one of GNOME 2's strong points (also one of KDE's) was being able to accomodate as many of them as possible. If this works right it will add to that.

**Comment by flexiondotorg** [comment] 2017-04-10 13:12
@raveit65 The patch from #550 is now available via a patched `mate-panel` in the `crazy-mate` PPA. It fixes the issue in my testing.

  * https://launchpad.net/~ubuntu-mate-dev/+archive/ubuntu/crazy-mate

**Comment by raveit65** [comment] 2017-04-10 17:10
@flexiondotorg 
Confirmed that the PR fixes the issue, i will approve it, but we should merged other PRs like m-s-d first, or not?
And here some other guys should review m-s-d.
@rilian-la-te 
Don't worry i think a lot of users will like it. Personal i don't use global menus, but it isn't the point if i like that as upstream or not ;-)

**Comment by flexiondotorg** [comment] 2017-04-10 18:57
I'm carrying all the patches in Ubuntu MATE 17.04. Unless the distro also includes vala-panel-appmenu, these changes are inert. Including them gives those people who like Global Menus (quite alot in my experience) the option to use them.

**Closed** 2017-04-10 22:04 UTC
Labels: confirmed

**Comment by lukefromdc** [comment] 2017-04-10 22:05
Approved by another and made no problems here in a non-global menu setup so merged

**Comment by raveit65** [comment] 2017-04-11 05:19
Hmm,
```
+	g_object_set(settings,"gtk-shell-shows-app-menu",FALSE,"gtk-shell-shows-menubar",FALSE,NULL);
```
Those settings depends on 
https://github.com/mate-desktop/mate-desktop/pull/256/commits/944455119ba916474288e340d781b6653d50bb1c
https://github.com/mate-desktop/mate-settings-daemon/pull/172/commits/978ef74f86b80116919b55ab69d7be0e8c59a839
Ideally this has to be merge first.
But 1.18 is branched and master is developing, so no need to remove it.

**Comment by lukefromdc** [comment] 2017-04-11 05:21
Seems to work fine for me with none of those settings set, but I suppose could segfault on some other distro over this. Let's get those other two done then

**Comment by flexiondotorg** [comment] 2017-04-11 06:43
Yes, Ubuntu MATE 17.04 is carrying all the required patches. This is so we can use 17.04, and the not yet started 17.10, and a test bed.

**Comment by raveit65** [comment] 2017-04-11 11:03
> This is unpatched version AFAIK. I have a bug than proposes patch.
https://bugzilla.redhat.com/show_bug.cgi?id=1387884

@rilian-la-te 
Does that mean w/o your patch vala-panel-appmenu does not work in fedora?
I compiled it but it does not work :-/

**Comment by rilian-la-te** [comment] 2017-04-11 11:05
Not, this does not means it:)

If vala-panel-appmenu does not work, then you misconfigured it.

Please, configure it as in README. I will help you, if it will not work after.

**Comment by raveit65** [comment] 2017-04-11 11:20
What i did:
- mate-desktop and m-s-d are updated (mate-panel will follow, i 'd like to see the issue again first :-)).
- both gsettings keys are enabled
- libunity and libunity-gtk3-parser are installed
- with cmake-gui i disabled vala-panel , xfce and budgie cmake options.
- installing and restarting session.
Result:
i see the single menu for an app in panel but any application menus.

Do i need to edit .bash_profile and .bashrc ?

**Comment by rilian-la-te** [comment] 2017-04-11 11:22
Show me GTK_MODULES variable, please
It must contain unity-gtk-module.
If not working - I will tell you what to do.

**Comment by raveit65** [comment] 2017-04-11 11:26
```
[rave@mother ~]$ set | grep GTK_MODULES 
GTK_MODULES=gail:atk-bridge:appmenu-gtk-module
```
Hmm adding 
```
if [ -n "$GTK_MODULES" ]; then
    GTK_MODULES="${GTK_MODULES}:appmenu-gtk-module"
else
    GTK_MODULES="appmenu-gtk-module"
fi

if [ -z "$UBUNTU_MENUPROXY" ]; then
    UBUNTU_MENUPROXY=1
fi

export GTK_MODULES
export UBUNTU_MENUPROXY
```
does not help

**Comment by rilian-la-te** [comment] 2017-04-11 11:27
Replace all occurences of `appmenu-gtk-module` to `unity-gtk-module`.

**Comment by rilian-la-te** [comment] 2017-04-11 11:27
And try after relogin.

**Comment by raveit65** [comment] 2017-04-11 11:33
Now
```
[rave@mother ~]$ set | grep GTK_MODULES 
GTK_MODULES=gail:atk-bridge:unity-gtk-module
```
but same result.
![bildschirmfoto zu 2017-04-11 13-32-44](https://cloud.githubusercontent.com/assets/961604/24907171/5f58bbe2-1ebb-11e7-9ee9-afb31d0fb849.png)

**Comment by rilian-la-te** [comment] 2017-04-11 11:34
Try this:
```
k.pugin@worklinux-suse:~> cat .config/gtk-3.0/settings.ini 
[Settings]
gtk-modules = "unity-gtk-module:gail:atk-bridge"
gtk-shell-shows-app-menu=true
gtk-shell-shows-menubar=true
```

**Comment by raveit65** [comment] 2017-04-11 11:39
No same result with adding gtk-modules = "unity-gtk-module:gail:atk-bridge"  there.
Looks like that unity-gtk-module does not work here.

**Comment by rilian-la-te** [comment] 2017-04-11 11:42
Unity-gtk-module is installed?
Package ```unity-gtk3-module```
[Here](https://kojipkgs.fedoraproject.org//packages/unity-gtk-module/0.0.0+17.04.20170403/1.fc27/x86_64/unity-gtk3-module-0.0.0+17.04.20170403-1.fc27.x86_64.rpm)

**Comment by raveit65** [comment] 2017-04-11 12:17
Thx, Package unity-gtk3-module is installed from fedora repos, but no luck.
It works for CSD-Apps like dconf-editor but not for normal applications.

**Comment by rilian-la-te** [comment] 2017-04-11 12:18
Unity-gtk-module not working, AFAIK. Can you open Caja in inspector?

**Comment by rilian-la-te** [comment] 2017-04-11 12:18
And see settings gtk-shell-shows-app-menu and gtk-settings-show-menubar.

**Comment by rilian-la-te** [comment] 2017-04-11 12:24
Show me a screenshot,please.

**Comment by raveit65** [comment] 2017-04-11 12:25
![bildschirmfoto zu 2017-04-11 14-25-02](https://cloud.githubusercontent.com/assets/961604/24909044/b0a5fcb0-1ec2-11e7-8460-674c8c3999ae.png)
Inspector looks good, imo.

**Comment by rilian-la-te** [comment] 2017-04-11 12:27
Yes, but unity-gtk-module is not in action. What terminal says? Especially env? And running pluma from terminal?

**Comment by raveit65** [comment] 2017-04-11 12:30
```
[rave@mother ~]$ env | grep gtk
QT_STYLE_OVERRIDE=gtk
GTK_MODULES=gail:atk-bridge:unity-gtk-module
GTK_IM_MODULE=gtk-im-context-simple

[rave@mother ~]$ pluma
Gtk-Message: Failed to load module ""unity-gtk-module"
Gtk-Message: Failed to load module "atk-bridge""
```
omg :-)

**Comment by raveit65** [comment] 2017-04-11 12:31
double quotes.....

**Comment by rilian-la-te** [comment] 2017-04-11 12:32
Try to remove quotes from settings.ini:)

**Comment by raveit65** [comment] 2017-04-11 12:44
\o/ i see the issue again :-)
Now i need to recompile mate-panel with PR.
It works with ie. caja, mate-terminal but not with firefox (gtk3), known issue?
![bildschirmfoto zu 2017-04-11 14-37-12](https://cloud.githubusercontent.com/assets/961604/24909513/7a758e06-1ec4-11e7-837e-1de93ba55d3f.png)
![bildschirmfoto zu 2017-04-11 14-38-44](https://cloud.githubusercontent.com/assets/961604/24909539/9888aa86-1ec4-11e7-8d62-d8f48e84dba7.png)

But i am not shure about my idea adding vala-panel-appmenu to fedora (official) for f26 if so much modifications are needed, especially starting unity-gtk-module.
Well, i need to find out what is really needed here.

**Comment by rilian-la-te** [comment] 2017-04-11 12:46
1. Firefox outside ubuntu is not supported.
2. unity-gtk-module not required. Since vala-panel-appmenu 0.4.4 it carried unity-gtk-module within, called appmenu-gtk-module
3. Modification of GTK_MODULES is GTK thing, I don't want to override it, I want choose for users.

**Comment by raveit65** [comment] 2017-04-11 12:48
> unity-gtk-module not required. Since vala-panel-appmenu 0.4.4 it carried unity-gtk-module within, called appmenu-gtk-module

Ok but i need to load it via bashrc or profile?

**Comment by raveit65** [comment] 2017-04-11 12:50
So firefox is patched in Ubuntu-17.04?

**Comment by rilian-la-te** [comment] 2017-04-11 12:53
Yes, and it was patched in Ubuntu since beginning of Unity. Ask @flexiondotorg for more info.

About gtk-module - I will look for easier alternative, if needed.

**Comment by rilian-la-te** [comment] 2017-04-11 12:55
We can load gtk-module via GtkSettings, AFAIK. But I don't know how to modify it system-wide by applet:(

**Comment by raveit65** [comment] 2017-04-11 12:58
> About gtk-module - I will look for easier alternative, if needed.

Thx, i will test it a bit more local and ask you at your repo when i want to package it.
For a official package i can't say to users 'please edit your .bashrc and editing /etc/profile i want to avoid.

**Comment by rilian-la-te** [comment] 2017-04-11 13:04
You can introduce systemd user unit for appmenu-gtk-module and GTK_MODULES variable after installing applet.

**Comment by rilian-la-te** [comment] 2017-04-11 13:05
I use in Arch package /etc/X11/xinit.d/ file.

**Comment by rilian-la-te** [comment] 2017-04-11 19:33
Try systemd user unit for gtk-module, please. I think this is most perspective.

**Comment by lestcape** [comment] 2018-01-04 12:24
I think that will be good if all configurations will be work inside the box and user will not need to know how to configured the module. I think issues like this one can be avoided then.

I'm working to make a patch for the gtk2 app, to be loaded the gtk-shell-show-menubar property without need to add more things. The idea it's install the property gtk-shell-show-menubar to the gtk2 settings on fly. Something like the ubuntu patch (https://code.launchpad.net/~attente/gtk/gtk-shell-shows-menubar/+merge/166911), but outside gtk and inside the module, when the gtk-module-module init. Something like this (not tested yet):

```
static void
sync_gtk2_settings(gboolean def_value)
{
#if GTK_MAJOR_VERSION < 3
  pspec = g_object_class_find_property (gtk_settings_get_type (), "gtk-shell-shows-menubar");
  if (!G_IS_PARAM_SPEC (pspec))
    {
      gtk_settings_install_property (g_param_spec_boolean (
        "gtk-shell-shows-menubar",
        _("Desktop shell shows the menubar"),
        _("Set to TRUE if the desktop environment is displaying the menubar, FALSE if the app should display it itself."),
        def_value,
        G_PARAM_READWRITE
      ));
    }
#endif
}

```

**Comment by lestcape** [comment] 2018-01-04 12:54
And here a good point of why will be good to moveall config to XSettings: https://www.freedesktop.org/wiki/Specifications/xsettings-spec/
