### ISSUE TITLE
high memory usage - mate-panel

### ISSUE THREAD

**Issue by sandeep-raman** [mate-desktop/mate-panel#1085] opened 2020-05-27 09:22 UTC
#### Expected behaviour
mate-panel does not consume 13G of memory

#### Actual behaviour
mate-panel consumes 13G memory over two to three days of uptime

#### Steps to reproduce the behaviour
Nothing specific. The system runs on mate-desktop-environment and used for day-to-day activities like browsing, chat.

#### MATE general version
MATE Desktop Environment - 1.24.0

#### Package version
mate-panel-1.24.0-4.fc32.x86_64

#### Linux Distribution
Fedora release 32 (Thirty Two)
5.6.13-300.fc32.x86_64

#### Additional information about memory usage
free -h
              total        used        free      shared  buff/cache   available
Mem:           30Gi        27Gi       1.5Gi       319Mi       1.3Gi       2.1Gi
Swap:         4.4Gi        44Mi       4.3Gi

![image](https://user-images.githubusercontent.com/2987825/83002494-1fe55980-9fdb-11ea-9199-40f83625b58f.png)

**Comment by sandeep-raman** [comment] 2020-05-27 20:10
There seems to be a downstream report for this issue and building an in-process applet seems to solve the problem. https://bugzilla.redhat.com/show_bug.cgi?id=1830885

**Comment by raveit65** [comment] 2020-05-27 20:54
Re-opened because the panel leaks memory when build applets in-process.
This needs to be fixed here at MATE upstream.
In-process is needed to run the panel in a wayland compositor.
But it seems that na-tray applet leaks memory especially when wine+ emule-applet is running, see rhbz.
I can confirm this high memory consumption.
Usually the panel starts with 60MB and end up with 180-300 MB after ~12hours when i shutdown my box.
So, the panel has definitely a leak when build in-process.
I will switch back to out-of-process build for f32 (no wayland support) to work around the problem.
@mate-desktop/core-team 
This is really a no-go for wayland.
On user in rhbz reported about 14 GB memory consumption!!!

**Comment by cwendling** [comment] 2020-05-28 08:08
Agreed we should definitely fix this.  Unfortunately I don't think it's only the in-process/out-of-process case, because I'm running out-of-process currently and I see the issue from time to time (probably not as badly, but mate-panel grows over time, sometimes to problematic levels).
I'm trying a Valgrind run I'll leave on for a couple of days or so, and see if I can gather any useful info.

**Comment by raveit65** [comment] 2020-05-29 11:43
I updated fedora 32 mate-panel build to use out-process-applets.
https://bodhi.fedoraproject.org/updates/FEDORA-2020-9b86f77580
Please leave karma if you have a fas account.

**Comment by vkareh** [comment] 2020-05-29 11:55
Whether out-of-process or in-process applets are the cause or not, having them built out-of-process makes debugging possible. MATE is not usable on Wayland yet, so I think moving back to out-of-process is a good idea until the memory leak can be plugged.

**Comment by muktupavels** [comment] 2020-05-29 12:00
If some applet is causing memory leak, changing from in-process to out-of-process won't fix anything - memory leak will move to other process...

**Comment by vkareh** [comment] 2020-05-29 12:02
Correct, that's the goal.

**Comment by raveit65** [comment] 2020-05-29 13:24
> If some applet is causing memory leak, changing from in-process to out-of-process won't fix anything - memory leak will move to other process...

Are you sure?
Because user in rhbz told me that memory consumption won't be increased with process of na-tray-applet. See https://bugzilla.redhat.com/show_bug.cgi?id=1830885#c7
He use wine and emule applet and memory increased to 14 GB sometimes (in-process)
My results was:
starting the process with ~60MB and ends with 180 -300Mb after 12-14 hours.
With out-process builds i didn't saw such a memory consumption with single processes.

And i never get rhbz report about this when build out-of-process.
Or the people observe only the mate-panel process and not the other ones.....

So, maybe it is stupid question, is it possible that something is wrong how we build the applets in-process?

**Comment by raveit65** [comment] 2020-05-29 13:30
https://bugzilla.redhat.com/show_bug.cgi?id=1830885#c10
```
Created attachment 1691028 [details]
Here's the memory consumption of the "Out Of Process" mate-panel after 4 days.

After 4 days of purposefully heavy usage I can see no trace of memory leaks in the mate-panel built with Out Of Process Plugins.
```

**Comment by muktupavels** [comment] 2020-05-29 20:29
How would Wine cause memory leaks in panel and/or applet? It might trigger something, but leak is still in panel and/or applets.

If this really happens with in-process applets only, maybe there is some in-process specific code that causes leak. No idea what changes you have or have not done...

Actually I had "interesting" bug:
https://gitlab.gnome.org/GNOME/gnome-panel/-/issues/21

Leak in cpufreq applet was visible because of bug in other applet from gnome-flashback. So maybe you have something similar? Maybe wine tray icon is updated very often that causes panel to re-allocate applet sizes? And leak is somewhere where applet is updated/refreshed!? Moving to out of process might "help" because then same allocation(?) code path is not reached because actual applet window size does not change and there is no need to update/refresh applet that is in separate process.

Try changing many times theme and/or icon theme. I think that should cause applets to re-allocate/update... If you start to see increase in memory every time you change theme, try to find applet which is responsible for that.

**Comment by murashkin17** [comment] 2020-05-31 00:10
I have similar issue with mate-panel-1.24.0-4.fc32.x86_64 on 2 PCs. It seems that the issue started after upgrade to Fedora 32.

Is there a way to trace the memory use by applet? I am not familiar with MATE development but here how I would to it in similar situation. Assuming that mutliple applets are called in the panel code one after another

- add environment variable that triggers the memory trace and specifies a trace file
- before calling applet code, use malloc facilities or just sbrk() to check the time, applet name, and current heap size and print it to the trace file

1st computer
mate-panel rss is 20 GB
mate-panel was started 3 weeks ago
there are 30 workspaces

2nd computer
mate-panel rss is 6.5 GB
mate-panel was started 3 days ago
there are 10 workspaces

I did not pay attention to it before, so I cannot tell how fast it was increasing.

**Comment by lukefromdc** [comment] 2020-06-12 06:25
I have mate-panel build with all possible applets in-process, but never have runtimes longer than about 8 hours at the most as security requires encrypted machines to be all the way off when not in use. I DO see excessive memory consumption, just saw 147MB but that's not multi-GB consumption. To produce 6.5 GB in 3 days i would expect to see a GB or so in my longer sessions. Note that I have only 4 workspaces. This suggests maybe the offending memory leak is in WNCKlet, thinking window list or workspace switcher?

**Comment by raveit65** [comment] 2020-07-23 11:37
Not all memleaks are fixed.

**Comment by zhangn1985** [comment] 2020-07-29 08:43
will these patches backport to old release?

**Comment by lukefromdc** [comment] 2020-08-07 22:17
I didn't expect any one of these to catch all the memleaks, rather it's like fixing up a very old boat: you find and fix the leaks, one at a time if necessary.

**Comment by lukefromdc** [comment] 2020-08-07 22:23
I've still got the issue (with wncklet in process) of window thumbnails running up mate-panel's ram, remember that if this also happens with the applet out of process it won't be shown as mate-panel using all that RAM. That one can of course be worked around by disabling window previews, in the boat/ship analogy shutting the watertight door to a known leaky compartment.

We should reopen this (it's basically a tracking issue) until most of all of the memory leaks are found. I remember in the old Ubuntu Hardy 32 bit days being able to run Ubuntu on a 128mb system (as a test) and see the old gnome-panel (1.24 I think it was) sit there at 32MB-and that was considered fat at least for such a system.

**Comment by raveit65** [comment] 2020-08-08 08:40
With current master and applets build in process. 8 workspaces and > 20 windows open
Memory consumption
after panel start = 68 MiB (only system-monitor windows is open)
first preview = 79,8 MiB (after opening 4 more windows)
second preview = 80,3 MiB
after second preview = 79,8 MiB (1)
third preview = 80,3 MiB
after third preview = 79,8 MiB
4th preview = 80,3 MiB
after 4th preview = 79,8 MiB
5th preview = 80,3 MiB
after 5th preview = 79,8 MiB
6th preview = 80,3 MiB
after 6th preview = 79,8 MiB
System after 3-4 hours ~ 110-120 MiB
Before shutdown system after 16-18 hours = not more than ***125 -130 MiB***

I only see a significant increase of memory consumption after the first use of a preview.
After that point (1) the memory of a preview goes always back to previous level.
Not sure if we really have a leak here with previews and only a cache is loaded the first time.
Maybe @vakaresh can tell us more how this feature work?

This are my results the last 4 days after i use latest memleak fixes from master.
For me this is a great improvement.

I will do a new release and a test build (in -process) for @sandeep-raman and user in rhbz report, to see what happens when a system never shutdown.

PS: I don't think you can't compare 12 years old computer systems (gnome2) with new boxes.
All Application use more memory when a system got 32 GB available RAM compare to an old system with let say 2-4 GB.

**Comment by lukefromdc** [comment] 2020-08-08 19:49
I did some detail testing after applying 
https://github.com/mate-desktop/mate-panel/pull/1135
and while I am not sure if RAM use is the same before and after, it looks like what I got with it was RAM use growing with each loaded thumbnail by 20-30MB (that's a big thumbnail), then stabilizing once all have been loaded. We are then keeping them in RAM, whether to do this for performance or ensure only one is loaded at a time and only when being displayed is a team decision. Probably some programmers would make that a runtime decision based on memory pressure but I doubt any of us have the time for that.

**Comment by raveit65** [comment] 2020-08-08 20:03
Which thumbnail-size are you using?
I am using 400 (px?) in preferences on a HIDPI system and marco as window-manager.

**Comment by lukefromdc** [comment] 2020-08-08 20:32
I have 200px set, but also on a 4K monitor with window-scaling=2, wonder if that's the issue. SHOULD be same as 400 on a non-hidpi setup but I don't know how this is being handled by GTK.

**Comment by raveit65** [comment] 2020-08-08 21:54
I am using 400px on a HDPI system.
Are you using compiz, wayfire or marco. Maybe this is related?

**Comment by lukefromdc** [comment] 2020-08-09 23:01
This is with compiz-reloaded, which I use all the time in Xorg unless testing marco. It would not be possible to use any part of wncklet (the window list included) in Wayland (wayfire is a wayland compositor borrowing features from compiz) as wnck is xorg-only.

**Comment by raveit65** [comment] 2020-08-10 09:21
It is great that you know that.
So, the different to my setup is using compiz-reloaded.
Did you ever try to test it with marco?

**Comment by rcaridade145** [comment] 2020-08-10 13:32
@lukefromdc Is there any option related to mipmap you haven't select by any chance?

**Comment by lukefromdc** [comment] 2020-08-10 16:44
I just retested with marco, got the same results: thumbnails loading once and staying loaded, using about the same amount of RAM as before. I have a local build of compiz 0.8.18 with a hacked version of gtk-window-decorator that supports hidpi. At any rate, that's not running when testing in marco, and thumbnails are undecorated as well

**Comment by lukefromdc** [comment] 2020-08-10 16:48
Also, I got the comment below in an email  for 
https://github.com/mate-desktop/mate-panel/pull/1135/commits/f3dc2a11c5f3c80eb693b802ede13e555649e990
but it's no longer on the page. Same details are at
https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-The-GdkPixbuf-Structure.html#gdk-pixbuf-get-pixels


gdk_pixbuf_get_pixels ()

Returns

A pointer to the pixbuf's pixel data. Please see the section on image data for information about how the pixel data is stored in memory.

This function will cause an implicit copy of the pixbuf data if the pixbuf was created from read-only data.

**Comment by zhangn1985** [comment] 2020-08-11 08:05
this is my comment, and it's wrong, thus I delete. the PR is correct.

**Comment by tbzatek** [comment] 2020-08-11 13:02
> Also, I got the comment below in an email for
> [f3dc2a1](https://github.com/mate-desktop/mate-panel/commit/f3dc2a11c5f3c80eb693b802ede13e555649e990)
> but it's no longer on the page. Same details are at
> https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-The-GdkPixbuf-Structure.html#gdk-pixbuf-get-pixels

I think I checked that when doing the memleaks evaluation. If I remember correctly it wasn't the case of an implicit copy here and freeing the pixels data resulted in a crash. You may easily test that yourself anyway.

**Comment by lukefromdc** [comment] 2020-08-13 04:28
Sorry about that, the interaction between github and email is not the best. I think it's good that we are trying to turn all stones on this issue

**Comment by raveit65** [comment] 2021-04-05 10:46
Does the issue still exists with current master or >= mate-panel-1.24.1 ?

**Comment by amurashkin17** [comment] 2021-04-06 20:51
After running for 3 weeks, with mate-panel-1.24.1-1.fc33.x86_64 

1st computer
mate-panel RSS is 51 MiB
mate-panel was started 3 weeks ago
there are 30 workspaces

2nd computer
mate-panel RSS is 155 MiB
mate-panel was started 3 weeks ago
there are 10 workspaces

Looks good.

**Comment by amurashkin17** [comment] 2021-04-06 20:59
Forgot to mention that the workflow is similar to the case previously reported in https://github.com/mate-desktop/mate-panel/issues/1085#issuecomment-636401088_. For instance, there are many dozens of open windows and applets.

**Closed** 2023-07-21 20:03 UTC
