### ISSUE TITLE
updateing to the latest version of mate, the mate panel becomes unuseable with orca screen reader

### ISSUE THREAD

**Issue by mhussaincov** [mate-desktop/mate-panel#440] opened 2016-05-29 14:31 UTC
I am  able to get to the panel but when I tab around to get to the cpu applet or the network applet ore any other applet, i'm unable to.
there is no feedback from orca, i'm not sure if this is a mate issue or not but it happened after upgradeing to the latest version of mate
my distribution is
sonar  which is intern based on manjaro which is based on arch.
thanks,
Majid Hussain

**Comment by flexiondotorg** [comment] 2016-05-29 15:42
What version of MATE are Manjaro shipping and do you know if it is built against GTK2 or GTK3?

**Comment by mhussaincov** [comment] 2016-05-29 16:01
the version of mate being run  is
mate] v1.14, and we are using gtk2
the version of mate panel is
mate-panel-1.14.0-1
I hope this is of help?
Majid Hussain

**Comment by coffeeking** [comment] 2016-05-30 04:43
hi all
I can confirm this bug. After updating to mate 1.14.1 and the latest accessibility stack, which includes at-spi2-atk 2.20, at-spi2-core 2.20, atk 2.20 and orca 3.20, the mate panel is completely inaccessible. I can no longer tab my way along it and read the applets contained in it. To make sure this wasn't my setup, I've deleted the panel configuration, both through the mate interface by using "delete this panel" and by resetting it's gsettings using dconf reset -f /org/mate/panel. Nothing seems to work. I can't mark this bug as critical, but I can't stress this enough. This is a critical bug for us disabled users. In particular, I am a co developer of the sonar gnu linux distribution for blind and disabled users, and this bug will keep us from releasing until it's fixed. Please don't worry, we're still in alpha stage so there's time. I don't wish to demand that this bug get fixed, that's not how you behave in an open source community, but it is a very important bug and I'll do all I can to help you guys fix it. Would you guys mind contacting joanmeri diggs, the orca maintainer? She can tell you what mate panel is doing internally with the accessibility stack so you guys can fix it. You can contact her at, <jdiggs@igalia.com> If you guys don't have the time, I'd be happy to do so and post her comments hear.

**Comment by raveit65** [comment] 2016-05-30 06:23
I would simply try first to downgrade the components, to find out the culprit.
It should be possible to run Mate with with a 1.12.x panel version.
Or downgrade the accessibility stack to a version where it did work.

**Comment by raveit65** [comment] 2016-05-30 06:26
Btw. you're are very brave if you're are using a rolling release distro as base for sonar.
You will always the first one who run in bugs.

**Comment by coffeeking** [comment] 2016-05-30 06:35
hi
Downgrading mate panel from 1.14 to 1.12 fixes the problem, so it's definitely the panel. Where should we go from hear? I had to tell pacman, the arch linux package manager to ignore dependencies, since mate-panel wouldn't downgrade gracefully. How can I help with this bug?

**Comment by raveit65** [comment] 2016-05-30 08:26
That's good, are you familiar with using 'git bisect' ?
With that git command you can find out the commit which causes the issue.
https://git-scm.com/docs/git-bisect
Of course you need to install mate-panel local (or building a installer package) from every bisect step, to find out which version is good.

**Comment by coffeeking** [comment] 2016-05-30 08:42
hi
I'm actually not very familiar with git bisect but I'll be happy to try
to find the commit that causes the accessibility problem. Could you
maybe give me basic steps in how to use it? I've built mate components
from source so that's not a problem.


NO NAME wrote:

**Comment by coffeeking** [comment] 2016-05-30 10:39
hi
This is perfect. I'll do that right now, and comment with the culprit
commit.
Thanks
Kendell Clark


NO NAME wrote:

**Comment by coffeeking** [comment] 2016-05-30 11:20
hi
I've got the problem commit. I ran the git bisect twice just to make
sure I didn't accidentally mess up. I then removed the mate panel
directory, removed the copy from /usr/local, recloned mate-panel and
reverted the problem commit. After a rebuild and local install, the
panel worked beautifully again. Here's the problem commit:
1b7d949fd82fa646d9705b7a04e7090d4f5b9366
I don't really understand how fixing a build variable could've broken
accessibility but it did. Is there anything else I can do?
Thanks
Kendell Clark


NO NAME wrote:

**Comment by raveit65** [comment] 2016-05-30 11:42
Oh, i think i made a mistake
```
#if !GTK_CHECK_VERSION (3, 0, 0)
   GdkWindow *window = gtk_widget_get_window (widget);
#endif
```
If just a gtk version check does not work for gtk2 build than i forgot to add
```
#include <gtk/gtk.h>
```
to the file, means that line isn't used for both toolkit version :-/ 
Can you add this line so that it look like this
```
#include <gtk/gtk.h>
#include <gdk/gdk.h>
```
https://github.com/mate-desktop/mate-panel/blob/1b7d949fd82fa646d9705b7a04e7090d4f5b9366/applets/notification_area/na-tray-child.c#L28
This should fixes the issue.

**Comment by coffeeking** [comment] 2016-05-30 13:13
hi
I just got the comment about adding to the source code. I'm not sure I
can do that. Even if I could, I don't have push access to mate's
repositories. But I'm glad we know what causes accessibility to be
broken. While we're working on it, would you guys be willing to look
into some accessibility problems with the panel? The following applets
don't speak with orca. Universal access, clock, and the power applet if
there's no battery present. The clock applet reads as "click to select
month" instead of the time and date. Also, the panel will quite often
freeze, making orca unable to read the applets on it until it is
restarted with "mate-panel --replace". I've reported this to the orca
list and joanie thinks it might be old accessibility code in mate
somewhere but she isn't sure what or where. I can always file a new bug
if that would be easier, I just thought I'd ask while I was thinking
about it.
Thanks
Kendell Clark
 

NO NAME wrote:

**Comment by raveit65** [comment] 2016-05-30 13:42
> I just got the comment about adding to the source code. I'm not sure I can do that. Even if I could, I don't have push access to mate's repositories. But I'm glad we know what causes accessibility to be broken.

Sec, i wanted only to know if adding this code line works :)
Than i will commit it for myself.

> While we're working on it, would you guys be willing to look into some accessibility problems with the panel? The following applets don't speak with orca. Universal access, clock, and the power applet if there's no battery present. The clock applet reads as "click to select month" instead of the time and date.

Is this another regression or a known old problem?

> Also, the panel will quite often freeze, making orca unable to read the applets on it until it is restarted with "mate-panel --replace". I've reported this to the orca list and joanie thinks it might be old accessibility code in mate somewhere but she isn't sure what or where. I can always file a new bug if that would be easier, I just thought I'd ask while I was thinking about it. Thanks Kendell Clark

For this please file out a new report. I can look at the code of gnome-panel, maybe there are some deprecation fixes for atk.
But the main prob is that we are a very small team with 2-3 devs, and we are complete overloaded with working for Mate.
And i'm not really a coder, i'm good in theming for gtk3 and i do my best to help out in Mate code since other devs had left us.
But modernize the accessibility code is really to much for me.
We need to find a solution for this, maybe a crowd funding and we can look for an external dev who want to this?
What do you think?

**Comment by raveit65** [comment] 2016-05-30 15:55
@coffeeking 
Can you please test https://github.com/mate-desktop/mate-panel/commit/80171cb1deefad3e689c52d63051fe429d97b852
on top of 1.14.1 release?
I wanna be sure that it fixes the issue before i cherry-pick the commit to 1.14 branch.

**Comment by coffeeking** [comment] 2016-05-31 00:47
hi
I'm not sure if the applets not speaking are known or not, but they've
been around as long as mate's been accessible, and I'm pretty sure they
didn't speak in gnome 2.x. These aren't critical issues by any means,
I'm just bringing them up while we're working on accessibility but at
least the panel works now.
Thanks
Kendell Clark


NO NAME wrote:

**Comment by coffeeking** [comment] 2016-05-31 00:50
hi
Oh I completely understand. I'm overloaded myself. I file bugs for this
desktop, gnome, cinnamon, and I co develop a linux distribution so I'm
always overloaded as well. I'll file a new bug. You guys did a fantastic
job on this bug. I was expecting it to take months but it was fixed in
days. You guys might be a small team but you get a lot done. The gnome
project could learn a few lessons from the work you guys do. They have
much more people, but sometimes their accessibility bugs take a while to
get fixed.
Thanks
Kendell Clark


NO NAME wrote:

**Comment by coffeeking** [comment] 2016-05-31 05:34
hi
I've just filed a new issue against mate panel for the applets'
accessibility issues  and the freezing. The link can be found at:
https://github.com/mate-desktop/mate-panel/issues/441. What do you guys
think? Is this issue fixed? If so, would you guys mind releasing an
update mate panel release, maybe 1.14.1 with the accessibility fix? This
next issue isn't nearly as urgent. It's important, but not critical. I'm
determined to help you guys solve it, I don't expect it solved for me.
Thanks
Kendell Clark


kendell clark wrote:

**Comment by raveit65** [comment] 2016-06-02 22:33
merged in 1.14 branch https://github.com/mate-desktop/mate-panel/commit/b24f7fab61d11b04ab0714a5137073e668c677f5
We will release an new version in the next weeks, please use this as patch for your distro for the moment.
And give me a reminder before you get in release freeze, if i forget that.

**Comment by coffeeking** [comment] 2016-06-03 03:56
hi
Since this issue has been closed, this will probably be my final
comment. We're now in release freeze status. This month is the month of
our release so we've entered our beta period. No new software can be
added at this point, it's time to concentrate on ironing out bugs so a
new mate panel release would be helpful.
Thanks
Kendell Clark


kendell clark wrote:

**Comment by coffeeking** [comment] 2016-06-03 07:16
hi
I've just built a test version of mate panel using git. The bug seems to
be back. The accessibility one. Would someone mind reopening this issue?
I'm not sure how. I'll run another git bisect if you like since I
must've gotten the wrong commit, even though I did it twice.
Thanks
Kendell Clark


kendell clark wrote:

**Comment by raveit65** [comment] 2016-06-03 07:19
Did you use 1.14 branch?

**Comment by coffeeking** [comment] 2016-06-03 07:30
hi
no but I'll check that out and build a test version of mate panel. I'm
currently using master. Let me try that. I'll comment if the bug still
exists
Thanks
Kendell Clark


NO NAME wrote:

**Comment by coffeeking** [comment] 2016-06-03 07:35
hi
Ok, I feel stupid. The bug is gone in the 1.14 branch. Sorry for the
false alarm. Should I concentrate on the inaccessible applets now?
Thanks
Kendell Clark


NO NAME wrote:

**Comment by raveit65** [comment] 2016-06-03 08:35
Np, if you think the applets have also a regression you can try to bisect mate-applets too.

**Comment by coffeeking** [comment] 2016-06-03 11:27
hi
Although the bug that was filed has been fixed, would someone who knows
how to code mind looking into the accessibility code of mate panel? This
bug has been fixed but the panel is still quite flaky, prone to freezing
and not allowing orca to read the applets on it until it's restarted
with mate-panel --replace, an orca restart, or both. I hate to burden
you guys with more work, but this has been the case ever since mate was
formed, and joanmeri diggs, the orca maintainer says there's nothing she
can do until you guys improve the underlying accessibility code. I
really appreciate all you guys have done so far. Your prompt response to
the bug makes me really glad I use mate as my desktop of choice.

Thanks
Kendell Clark


kendell clark wrote:

**Comment by raveit65** [comment] 2016-06-03 11:40
@coffeeking can you please test 1.14 branch again, we added some more commits from master. I want to make make sure that we don't break something again, than i will do a new release.
Thank you

**Comment by coffeeking** [comment] 2016-06-03 11:44
hi
Right away. I'll comment with the results.
Thanks
Kendell Clark


NO NAME wrote:

**Comment by coffeeking** [comment] 2016-06-03 11:50
hi
Unfortunately something is still wrong. I can get to the inaccessible
"universal access" applet, but if I tab past that orca stops reading all
applets until I reset the panel with mate-panel --replace. If I go
backwards, using shift tab instead of tab, I can usually get to the
sound output volume applet, but tabbing past that freezes the panel. If
I'm lucky, I can get to the networking applet which shows me connected
via ethernet, but tabbing past that freezes the panel.
I'm so sorry for the bad news. To make sure I was using the latest
commit, I used the following commands
git checkout 1.14
git pull
I then did a make clean, followed by make && sudo make install. I then
restarted the panel and tried to navigate it.
Thanks
Kendell Clark

Kendell Clark


kendell clark wrote:

**Comment by coffeeking** [comment] 2016-06-03 12:04
hi
If you guys are willing to take a look at the panel's accessibility
code, I'd recommend contacting joanmeri diggs. She's the lead orca
developer, and can  not only look at your code but tell you what's going
on inside of orca and at-spi, which I can't do. Normally I wouldn't be
this persistent and I hope I'm not pushing you guys too far, but the
panel really needs a serious overhall of it's accessibility support. If
you want, you can contact her at: jdiggs@igalia.com. I'll happily help
you and her out with whatever you need, I'm not expecting all of this to
be done for me. If it helps at all, mate's panel is mate's only serious
accessibility problem. Mate itself is very accessible, and has only
gotten better. The exception is mate when built as gtk3, but that's a
separate bug.   
Thanks
Kendell Clark


kendell clark wrote:

**Comment by mhussaincov** [comment] 2016-06-03 12:06
hey all,
I would advise you go with this option, the more accessability issues
fixed, the more people will wish to transission to mate :)
thanks,
Majid Hussain

**Comment by raveit65** [comment] 2016-06-03 12:10
@coffeeking 
'git log' on command line on 1.14 branch should show you this commit on top.
```
added missing variable initialization 
```
I want to reproduced it for my self. Can you dive me detailed instruction how to use ocra please?
I never used it, of course i don't have a screen-reader hardware for it.
Thanks

**Comment by raveit65** [comment] 2016-06-03 12:24
The main prob is that all devs from us have no knowledge about how atk works, beside that we are a small team and have a work overload.
Also i didn't find any commit in gnome-panel or gnome-panel-applets git repo.
So, i can't back port anything.
Don't understand me wrong i want to help you and fixing this bugs is long time overdue.
Imo we should try to find a third part dev who knows more about atk and and how it works with different gtk+ version.
Mate gets donations and we can give someone something for this job, Maybe sonar team have also donations for this job?
And maybe ocra dev is the right person for this job.

Btw. if she have a github account you can add her to this report.

**Comment by raveit65** [comment] 2016-06-03 13:05
@coffeeking 
Can you give me a favor and remove the last 3 commits local step by step?
Using 'git log' shows you the commit id.
Than ' git revert last-commit-id'
Testing and than revert next commit-id.
I want to know which commit causes the regression again.

**Comment by coffeeking** [comment] 2016-06-04 00:46
hi
The only person I know that knows about atk and the accessibility stack
is joanmeri diggs. I've emailed her to ask if she would be willing to
help. I gave her address in a previous comment. She won't expect payment
for fixing these bugs because she gets paid to work on accessibility
issues. She's the lead developer of the orca screen reader. I completely
understand about being overloaded. I wish I knew c code well, I'd look
at the code and fix the issues in a heartbeat. I am one of three
developers of the sonar distribution, but I'm the only one that does
most of the work, and I can't code. Joanmeri would probably be your best
bet. If she says no though, you could try luke yelavich. He works over
at canonical and he could probably help. He's so overloaded though it
might take quite a while to produce any results.
thanks
Kendell Clark
 

NO NAME wrote:

**Comment by raveit65** [comment] 2016-06-04 14:07
@coffeeking can please test what i ask you in previous comment?

**Comment by coffeeking** [comment] 2016-06-04 14:09
hi
sure. What was I supposed to test again? If it was building a mate panel
based on either the latest master or 1.14 branch I've done both, and the
bug still exists in both, although the 1.14 branch isn't as bad. If not,
you'll need to remind me. Whatever it is, I'll gladly test.
Thanks
Kendell Clark


NO NAME wrote:

**Comment by raveit65** [comment] 2016-06-04 16:52
From 1.14 branch please. I want to know which of the latest 3 commits causes the regression again.
'na-try-child: add missing include for GTK_Version_Check' is the good commit which did fix the issue, but there are 3 more commits on top of them.

git pull
git log
git revert **latest-commit**
test please, if it is broken revert the next commit.
and so on.

**Comment by raveit65** [comment] 2016-06-04 16:53
@coffeeking   ^^^^

**Comment by coffeeking** [comment] 2016-06-05 02:29
hi
Got it. I'll do that right now.
Thanks
Kendell Clark


raveit65 wrote:

**Comment by raveit65** [comment] 2016-06-08 08:41
merged
https://github.com/mate-desktop/mate-panel/commit/e14d3305b6ea36bb68db6c410494824e3c64ab5d

**Closed by raveit65** 2016-06-08 08:41 UTC
