### ISSUE TITLE
notification area icons sometimes don't update on icon theme change

### ISSUE THREAD

**Issue by tdrusk** [mate-desktop/mate-panel#177] opened 2014-03-04 04:24 UTC
If I select a new group of icons in Appearance the icons in the notification area sometimes don't update. I have to run killall mate-panel to refresh it. It would be nice if it auto-updated correctly.
##

**Comment by monsta** [comment] 2015-05-07 08:57
I can confirm it happens with nm-applet icon - but all other icons refresh fine for me.
LMDE 2 Betsy (based on Debian Jessie), MATE 1.8.

**Comment by monsta** [comment] 2016-01-07 17:52
@raveit65: it's even more weird in GTK+3 build... I can't get icons of volume applet and nm-applet to change at all. Restarting panel doesn't help. Can you reproduce this?

**Comment by monsta** [comment] 2016-01-07 17:55
Hmm, logging out and in helps - icons of GTK+3 apps in notification area change. I have no idea why a simple panel restart doesn't work...

**Comment by raveit65** [comment] 2016-01-10 22:48
With gtk3:
A 'killall mate-panel' does not terminate na-tray applets. 'ps aux' shows that nm-applet, blueman, fusion-icon, volume applet or any other runs with the same process id after the panel is reloaded.
Use 'killall nm-applet' and start it from terminal and you will see that nm-applet use a new icon after theme change.

**Comment by monsta** [comment] 2016-01-12 10:48
Interesting... but it's an issue anyway. We need to make GTK+3 apps react to icon theme change...

**Comment by raveit65** [comment] 2016-06-29 17:19
I don't think that we any influence about nm- applet.
I suggest to close bugs which can't be fixed from our side

**Comment by monsta** [comment] 2016-06-30 09:32
Well, volume applet is still ours :smile:

**Comment by monsta** [comment] 2017-07-05 12:41
Ok, time to fix it: https://github.com/mate-desktop/mate-media/pull/93 and https://github.com/mate-desktop/mate-power-manager/pull/221. Hope I didn't miss any other apps with themed tray icons.

**Comment by raveit65** [comment] 2017-07-05 17:47
Thanks, 
...libmatekbd , flags and locale text applets
and leds for keyboard status, imo from m-s-d
...are missing.
I think that's all.
caja-dropbox status-icon code is third-party= problem other ppl ;-)

**Comment by lukefromdc** [comment] 2017-07-05 18:44
nm-applet I think we have ZERO influence over. I've been using a patched version to support my theme since 2015, that patch was never merged or even responded to at GNOME

**Comment by monsta** [comment] 2017-07-05 19:05
I think keyboard LED status and libmatekbd icons aren't themed... I mean they have icons that are shipped with the apps/libs, which are the same with any icon theme. But I could miss something.

As for nm-applet, I found it's an issue only in Debian Jessie (previous stable release). It properly reacts to icon theme change in Mint 18.x (based on Ubuntu 16.04) and Debian Stretch. But anyway, it's out of our scope indeed, and I tell that to users. :slightly_smiling_face:

**Comment by monsta** [comment] 2017-10-21 20:09
Well, anyway, it should be fixed in apps, it can't be fixed in the panel. If I missed any of our apps with this issue, we can open a new report there.

**Closed by monsta** 2017-10-21 20:09 UTC
Labels: confirmed
